// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `browser`
/// namespace.
library;

import '../../semantics_base.dart';
import '../browser.dart';
import '../user_agent.dart';

/// `browser` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum BrowserEntity implements OTelEntity {
  /// The web browser in which the application represented by the resource is
  /// running. The `browser.*` attributes MUST be used only for resources
  /// that represent applications running in a web browser (regardless of
  /// whether running on a mobile or desktop device).
  ///
  /// Stability: development
  browser(
    'browser',
    identifying: [],
    descriptive: [
      Browser.browserBrands,
      Browser.browserLanguage,
      Browser.browserMobile,
      Browser.browserPlatform,
      UserAgent.userAgentOriginal
    ],
  ),

  /// The web page document loaded in the browser.
  ///
  /// Stability: development
  browserDocument(
    'browser.document',
    identifying: [Browser.browserDocumentUrlFull],
    descriptive: [],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const BrowserEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
