// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `cicd`
/// namespace.
library;

import '../../semantics_base.dart';
import '../cicd.dart';

/// `cicd` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum CicdEntity implements OTelEntity {
  /// A pipeline is a series of automated steps that helps software teams
  /// deliver code.
  ///
  /// Stability: release_candidate
  cicdPipeline(
    'cicd.pipeline',
    identifying: [Cicd.cicdPipelineName],
    descriptive: [],
  ),

  /// A pipeline run is a singular execution of a given pipeline's tasks.
  ///
  /// Stability: release_candidate
  cicdPipelineRun(
    'cicd.pipeline.run',
    identifying: [Cicd.cicdPipelineRunId],
    descriptive: [Cicd.cicdPipelineRunUrlFull],
  ),

  /// A CI/CD worker is a component of the CI/CD system that performs work
  /// (eg. running pipeline tasks or performing sync).
  /// A single pipeline run may be distributed across multiple workers. Any
  /// OpenTelemetry signal associated with a worker should be associated to
  /// the worker that performed the corresponding work.
  /// For example, when a pipeline run involves several workers, its task run
  /// spans may reference the different `cicd.worker` resources corresponding
  /// to the workers that executed each task run. The pipeline run's parent
  /// span may instead reference the CI/CD controller as the `cicd.worker`
  /// resource.
  ///
  /// Stability: release_candidate
  cicdWorker(
    'cicd.worker',
    identifying: [Cicd.cicdWorkerId],
    descriptive: [Cicd.cicdWorkerName, Cicd.cicdWorkerUrlFull],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const CicdEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
