// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `cloud`
/// namespace.
library;

import '../../semantics_base.dart';
import '../cloud.dart';

/// `cloud` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum CloudEntity implements OTelEntity {
  /// A cloud environment (e.g. GCP, Azure, AWS)
  ///
  /// Stability: development
  cloud(
    'cloud',
    identifying: [],
    descriptive: [
      Cloud.cloudAccountId,
      Cloud.cloudAvailabilityZone,
      Cloud.cloudPlatform,
      Cloud.cloudProvider,
      Cloud.cloudRegion,
      Cloud.cloudResourceId
    ],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const CloudEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
