// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `cloudfoundry`
/// namespace.
library;

import '../../semantics_base.dart';
import '../cloudfoundry.dart';

/// `cloudfoundry` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum CloudfoundryEntity implements OTelEntity {
  /// The application which is monitored.
  ///
  /// Stability: development
  cloudfoundryApp(
    'cloudfoundry.app',
    identifying: [],
    descriptive: [
      Cloudfoundry.cloudfoundryAppId,
      Cloudfoundry.cloudfoundryAppName
    ],
  ),

  /// The organization of the application which is monitored.
  ///
  /// Stability: development
  cloudfoundryOrg(
    'cloudfoundry.org',
    identifying: [],
    descriptive: [
      Cloudfoundry.cloudfoundryOrgId,
      Cloudfoundry.cloudfoundryOrgName
    ],
  ),

  /// The process of the application which is monitored.
  ///
  /// Stability: development
  cloudfoundryProcess(
    'cloudfoundry.process',
    identifying: [],
    descriptive: [
      Cloudfoundry.cloudfoundryProcessId,
      Cloudfoundry.cloudfoundryProcessType
    ],
  ),

  /// The space of the application which is monitored.
  ///
  /// Stability: development
  cloudfoundrySpace(
    'cloudfoundry.space',
    identifying: [],
    descriptive: [
      Cloudfoundry.cloudfoundrySpaceId,
      Cloudfoundry.cloudfoundrySpaceName
    ],
  ),

  /// The system component which is monitored.
  ///
  /// Stability: development
  cloudfoundrySystem(
    'cloudfoundry.system',
    identifying: [],
    descriptive: [
      Cloudfoundry.cloudfoundrySystemId,
      Cloudfoundry.cloudfoundrySystemInstanceId
    ],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const CloudfoundryEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
