// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `container`
/// namespace.
library;

import '../../semantics_base.dart';
import '../container.dart';
import '../oci.dart';

/// `container` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum ContainerEntity implements OTelEntity {
  /// A container instance.
  ///
  /// Stability: development
  container(
    'container',
    identifying: [],
    descriptive: [
      ContainerAttributes.containerCommand,
      ContainerAttributes.containerCommandArgs,
      ContainerAttributes.containerCommandLine,
      ContainerAttributes.containerId,
      ContainerAttributes.containerLabel,
      ContainerAttributes.containerName,
      Oci.ociManifestDigest
    ],
  ),

  /// The image used for the container.
  ///
  /// Stability: development
  containerImage(
    'container.image',
    identifying: [],
    descriptive: [
      ContainerAttributes.containerImageId,
      ContainerAttributes.containerImageName,
      ContainerAttributes.containerImageRepoDigests,
      ContainerAttributes.containerImageTags
    ],
  ),

  /// The runtime being used to run the container
  ///
  /// Stability: development
  containerRuntime(
    'container.runtime',
    identifying: [
      ContainerAttributes.containerRuntimeName,
      ContainerAttributes.containerRuntimeVersion
    ],
    descriptive: [ContainerAttributes.containerRuntimeDescription],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const ContainerEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
