// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `deployment`
/// namespace.
library;

import '../../semantics_base.dart';
import '../deployment.dart';

/// `deployment` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum DeploymentEntity implements OTelEntity {
  /// The software deployment.
  ///
  /// Stability: development
  deployment(
    'deployment',
    identifying: [],
    descriptive: [Deployment.deploymentEnvironmentName],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const DeploymentEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
