// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `host`
/// namespace.
library;

import '../../semantics_base.dart';
import '../host.dart';

/// `host` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum HostEntity implements OTelEntity {
  /// A host is defined as a computing instance. For example, physical
  /// servers, virtual machines, switches or disk array.
  ///
  /// Stability: development
  host(
    'host',
    identifying: [],
    descriptive: [
      Host.hostArch,
      Host.hostId,
      Host.hostImageId,
      Host.hostImageName,
      Host.hostImageVersion,
      Host.hostIp,
      Host.hostMac,
      Host.hostName,
      Host.hostType
    ],
  ),

  /// A host's CPU information
  ///
  /// Stability: development
  hostCpu(
    'host.cpu',
    identifying: [],
    descriptive: [
      Host.hostCpuCacheL2Size,
      Host.hostCpuFamily,
      Host.hostCpuModelId,
      Host.hostCpuModelName,
      Host.hostCpuStepping,
      Host.hostCpuVendorId
    ],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const HostEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
