// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `k8s`
/// namespace.
library;

import '../../semantics_base.dart';
import '../k8s.dart';

/// `k8s` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum K8sEntity implements OTelEntity {
  /// A Kubernetes Cluster.
  ///
  /// Stability: development
  k8sCluster(
    'k8s.cluster',
    identifying: [K8s.k8sClusterUid],
    descriptive: [K8s.k8sClusterName],
  ),

  /// A container in a
  /// [PodTemplate](https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates)
  /// .
  ///
  /// Stability: development
  k8sContainer(
    'k8s.container',
    identifying: [K8s.k8sContainerName],
    descriptive: [
      K8s.k8sContainerRestartCount,
      K8s.k8sContainerStatusLastTerminatedReason
    ],
  ),

  /// A Kubernetes CronJob object.
  ///
  /// Stability: development
  k8sCronjob(
    'k8s.cronjob',
    identifying: [K8s.k8sCronjobUid],
    descriptive: [
      K8s.k8sCronjobAnnotation,
      K8s.k8sCronjobLabel,
      K8s.k8sCronjobName
    ],
  ),

  /// A Kubernetes DaemonSet object.
  ///
  /// Stability: development
  k8sDaemonset(
    'k8s.daemonset',
    identifying: [K8s.k8sDaemonsetUid],
    descriptive: [
      K8s.k8sDaemonsetAnnotation,
      K8s.k8sDaemonsetLabel,
      K8s.k8sDaemonsetName
    ],
  ),

  /// A Kubernetes Deployment object.
  ///
  /// Stability: development
  k8sDeployment(
    'k8s.deployment',
    identifying: [K8s.k8sDeploymentUid],
    descriptive: [
      K8s.k8sDeploymentAnnotation,
      K8s.k8sDeploymentLabel,
      K8s.k8sDeploymentName
    ],
  ),

  /// A Kubernetes HorizontalPodAutoscaler object.
  ///
  /// Stability: development
  k8sHpa(
    'k8s.hpa',
    identifying: [K8s.k8sHpaUid],
    descriptive: [
      K8s.k8sHpaName,
      K8s.k8sHpaScaletargetrefApiVersion,
      K8s.k8sHpaScaletargetrefKind,
      K8s.k8sHpaScaletargetrefName
    ],
  ),

  /// A Kubernetes Job object.
  ///
  /// Stability: development
  k8sJob(
    'k8s.job',
    identifying: [K8s.k8sJobUid],
    descriptive: [K8s.k8sJobAnnotation, K8s.k8sJobLabel, K8s.k8sJobName],
  ),

  /// A Kubernetes Namespace.
  ///
  /// Stability: development
  k8sNamespace(
    'k8s.namespace',
    identifying: [K8s.k8sNamespaceName],
    descriptive: [K8s.k8sNamespaceAnnotation, K8s.k8sNamespaceLabel],
  ),

  /// A Kubernetes Node object.
  ///
  /// Stability: development
  k8sNode(
    'k8s.node',
    identifying: [K8s.k8sNodeUid],
    descriptive: [K8s.k8sNodeAnnotation, K8s.k8sNodeLabel, K8s.k8sNodeName],
  ),

  /// A Kubernetes Node System Container.
  ///
  /// Stability: development
  k8sNodeSystemContainer(
    'k8s.node.system_container',
    identifying: [K8s.k8sNodeSystemContainerName],
    descriptive: [],
  ),

  /// A Kubernetes
  /// [PersistentVolume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
  ///  object.
  ///
  /// Stability: development
  k8sPersistentvolume(
    'k8s.persistentvolume',
    identifying: [K8s.k8sPersistentvolumeUid],
    descriptive: [
      K8s.k8sPersistentvolumeAnnotation,
      K8s.k8sPersistentvolumeLabel,
      K8s.k8sPersistentvolumeName,
      K8s.k8sPersistentvolumeReclaimPolicy,
      K8s.k8sStorageclassName
    ],
  ),

  /// A Kubernetes
  /// [PersistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)
  ///  object.
  ///
  /// Stability: development
  k8sPersistentvolumeclaim(
    'k8s.persistentvolumeclaim',
    identifying: [K8s.k8sPersistentvolumeclaimUid],
    descriptive: [
      K8s.k8sPersistentvolumeclaimAnnotation,
      K8s.k8sPersistentvolumeclaimLabel,
      K8s.k8sPersistentvolumeclaimName,
      K8s.k8sStorageclassName
    ],
  ),

  /// A Kubernetes Pod object.
  ///
  /// Stability: development
  k8sPod(
    'k8s.pod',
    identifying: [K8s.k8sPodUid],
    descriptive: [
      K8s.k8sPodAnnotation,
      K8s.k8sPodHostname,
      K8s.k8sPodIp,
      K8s.k8sPodLabel,
      K8s.k8sPodName,
      K8s.k8sPodStartTime
    ],
  ),

  /// A Kubernetes ReplicaSet object.
  ///
  /// Stability: development
  k8sReplicaset(
    'k8s.replicaset',
    identifying: [K8s.k8sReplicasetUid],
    descriptive: [
      K8s.k8sReplicasetAnnotation,
      K8s.k8sReplicasetLabel,
      K8s.k8sReplicasetName
    ],
  ),

  /// A Kubernetes ReplicationController object.
  ///
  /// Stability: development
  k8sReplicationcontroller(
    'k8s.replicationcontroller',
    identifying: [K8s.k8sReplicationcontrollerUid],
    descriptive: [K8s.k8sReplicationcontrollerName],
  ),

  /// A Kubernetes ResourceQuota object.
  ///
  /// Stability: development
  k8sResourcequota(
    'k8s.resourcequota',
    identifying: [K8s.k8sResourcequotaUid],
    descriptive: [K8s.k8sResourcequotaName],
  ),

  /// A Kubernetes Service object.
  ///
  /// Stability: development
  k8sService(
    'k8s.service',
    identifying: [K8s.k8sServiceUid],
    descriptive: [
      K8s.k8sServiceAnnotation,
      K8s.k8sServiceLabel,
      K8s.k8sServiceName,
      K8s.k8sServicePublishNotReadyAddresses,
      K8s.k8sServiceSelector,
      K8s.k8sServiceTrafficDistribution,
      K8s.k8sServiceType
    ],
  ),

  /// A Kubernetes StatefulSet object.
  ///
  /// Stability: development
  k8sStatefulset(
    'k8s.statefulset',
    identifying: [K8s.k8sStatefulsetUid],
    descriptive: [
      K8s.k8sStatefulsetAnnotation,
      K8s.k8sStatefulsetLabel,
      K8s.k8sStatefulsetName
    ],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const K8sEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
