// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `os`
/// namespace.
library;

import '../../semantics_base.dart';
import '../os.dart';

/// `os` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum OsEntity implements OTelEntity {
  /// The operating system (OS) on which the process represented by this
  /// resource is running.
  ///
  /// Stability: development
  os(
    'os',
    identifying: [],
    descriptive: [
      Os.osBuildId,
      Os.osDescription,
      Os.osName,
      Os.osType,
      Os.osVersion
    ],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const OsEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
