// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention entities for the `service`
/// namespace.
library;

import '../../semantics_base.dart';
import '../service.dart';

/// `service` entities from the OpenTelemetry semantic
/// conventions. Each member carries the entity type string plus the
/// attribute keys that identify and describe it.
enum ServiceEntity implements OTelEntity {
  /// A logical unit of an application or system that performs a specific
  /// function.
  service(
    'service',
    identifying: [Service.serviceName],
    descriptive: [Service.serviceCriticality, Service.serviceVersion],
  ),

  /// A unique instance of a logical service.
  serviceInstance(
    'service.instance',
    identifying: [Service.serviceInstanceId],
    descriptive: [],
  ),

  /// Groups related services that compose a system or application under a
  /// common namespace.
  serviceNamespace(
    'service.namespace',
    identifying: [Service.serviceNamespace],
    descriptive: [],
  );

  @override
  final String name;

  @override
  final List<OTelSemantic> identifying;

  @override
  final List<OTelSemantic> descriptive;

  const ServiceEntity(
    this.name, {
    required this.identifying,
    required this.descriptive,
  });

  @override
  String toString() => name;
}
