// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

/// Attribute keys that are **not yet in the OpenTelemetry semantic-convention
/// registry**, staged here as candidates for upstream contribution.
///
/// ## Why this exists, and why it is separate
///
/// Everything under `semconv/` is generated by OTel Weaver from the registry
/// and is regenerated wholesale — `generate.sh` deletes the directory first.
/// Nothing hand-written can live there. Everything here is hand-maintained
/// and covers concepts the registry does not define yet.
///
/// The two are kept apart on purpose. A consumer must always be able to tell
/// "this key is a published OpenTelemetry convention" from "this key is a
/// proposal we are prototyping", because those carry very different promises.
///
/// ## The contract
///
/// Every key here is **unstable**. It may be renamed, retyped or removed in a
/// minor release, and that will happen without a deprecation cycle whenever
/// upstream reaches a different conclusion. That is the point: these names
/// exist to be *tested against reality* and then proposed, not to be a private
/// dialect. When one is accepted upstream it disappears from this file and
/// reappears in the generated `semconv/` output, which is the signal that it
/// has become real.
///
/// ## On the namespaces
///
/// These use the `app.*`, `device.*` and `browser.*` namespaces — the same
/// ones the registry owns. The OTel naming rules advise against that for
/// private attributes:
///
/// > It is not recommended to use existing OpenTelemetry semantic convention
/// > namespace as a prefix for a new company- or application-specific
/// > attribute name. Doing so may result in a name clash in the future.
///
/// That rule is aimed at attributes which will never go upstream, where a
/// vendor namespace is plainly correct. These are the opposite case: the
/// semantic-conventions CONTRIBUTING guide asks that "non-trivial changes to
/// semantic conventions should be prototyped in the corresponding
/// instrumentation(s)", and a prototype has to carry the name being proposed
/// or it proves nothing about the name. Renaming into a vendor namespace and
/// back would also mean two wire changes instead of one.
///
/// The clash risk is real and accepted deliberately, which is why every key
/// here is `@experimental` and why the disposition of each is written down in
/// `doc/SEMCONV_CANDIDATES.md`.
library;

export 'app_candidates.dart';
export 'browser_candidates.dart';
export 'device_candidates.dart';
