// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

/// Attribute keys that are **not yet in the OpenTelemetry semantic-convention
/// registry**, staged here as candidates for upstream contribution.
///
/// ## Why this exists, and why it is separate
///
/// Everything under `semconv/` is generated by OTel Weaver from the registry
/// and is regenerated wholesale — `generate.sh` deletes the directory first.
/// Nothing hand-written can live there. Everything here is hand-maintained
/// and covers concepts the registry does not define yet.
///
/// The two are kept apart on purpose. A consumer must always be able to tell
/// "this key is a published OpenTelemetry convention" from "this key is a
/// proposal we are prototyping", because those carry very different promises.
///
/// ## The contract
///
/// Every key here is **unstable**. It may be renamed, retyped or removed in a
/// minor release, and that will happen without a deprecation cycle whenever
/// upstream reaches a different conclusion. These names exist to be *tested
/// against reality*, not to be a private dialect.
///
/// They are candidates in the weakest sense: each one **might** be proposed
/// upstream, and might be rejected, reshaped, or renamed when it is. Nothing
/// here has been accepted, and nothing here should be read as a commitment to
/// propose it. When one is accepted it disappears from this file and reappears
/// in the generated `semconv/` output, which is the signal that it became
/// real; when one is rejected it is deleted and the reason is recorded in
/// `doc/SEMCONV_CANDIDATES.md`.
///
/// ## On the namespaces
///
/// These use the `app.*`, `device.*` and `browser.*` namespaces — the same
/// ones the registry owns — and the naming rules are more permissive about
/// that than a first reading suggests, because they address two audiences
/// separately.
///
/// "Recommendations for **application developers**" is where the familiar
/// prohibition lives, and it is scoped precisely:
///
/// > It is not recommended to use existing OpenTelemetry semantic convention
/// > namespace as a prefix for a new **company- or application-specific**
/// > attribute name.
///
/// The same section then names the case these keys are in, and points the
/// other way:
///
/// > The name may be generally applicable to applications in the industry. In
/// > that case consider submitting a proposal to this specification to add a
/// > new name to the semantic conventions, and if necessary also to add a new
/// > namespace.
///
/// And "Recommendations for **OpenTelemetry authors**" — the audience you join
/// the moment you write such a proposal — asks for the opposite of avoidance:
///
/// > When coming up with a new semantic convention make sure to check existing
/// > namespaces to see if a similar namespace already exists.
/// >
/// > All names that are part of OpenTelemetry semantic conventions SHOULD be
/// > part of a namespace.
///
/// So the namespace choice is not a rule being bent. It is the rule for a
/// convention intended to be general, which is the only kind that belongs in
/// this directory — anything genuinely specific to Dartastic or to one
/// application should carry a reverse-domain prefix and does not go here.
///
/// What remains real is the *timing* risk: these are not accepted yet, and
/// until they are, upstream could take the same name for a different purpose.
/// That risk is the reason for the instability contract above and for
/// `@experimental` on every key.
///
library;

export 'app_candidates.dart';
export 'browser_candidates.dart';
export 'device_candidates.dart';
