// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `android`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/android/)
library;

import '../semantics_base.dart';

/// `android.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Android implements OTelSemantic {
  /// This attribute represents the state of the application.
  ///
  /// Examples: `created`
  ///
  /// Stability: development
  androidAppState('android.app.state'),

  /// Uniquely identifies the framework API revision offered by a version (
  /// `os.version`) of the android operating system. More information can be
  /// found in the
  /// [Android API levels documentation](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels)
  /// .
  ///
  /// Examples: `33, 32`
  ///
  /// Stability: development
  androidOsApiLevel('android.os.api_level'),

  /// Deprecated. Use `android.app.state` attribute instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `android.app.state`.')
  androidState('android.state');

  @override
  final String key;

  const Android(this.key);

  @override
  String toString() => key;
}

/// Values for `android.app.state`.
///
/// Stability: development
enum AndroidAppState implements OTelSemanticValue {
  /// Any time before Activity.onResume() or, if the app has no Activity,
  /// Context.startService() has been called in the app for the first time.
  ///
  /// Stability: development
  created('created'),

  /// Any time after Activity.onPause() or, if the app has no Activity,
  /// Context.stopService() has been called when the app was in the
  /// foreground state.
  ///
  /// Stability: development
  background('background'),

  /// Any time after Activity.onResume() or, if the app has no Activity,
  /// Context.startService() has been called when the app was in either the
  /// created or background states.
  ///
  /// Stability: development
  foreground('foreground');

  @override
  final String value;

  const AndroidAppState(this.value);

  @override
  String toString() => value;
}

/// Values for `android.state`.
///
/// Stability: development
@Deprecated('Replaced by `android.app.state`.')
enum AndroidState implements OTelSemanticValue {
  /// Any time before Activity.onResume() or, if the app has no Activity,
  /// Context.startService() has been called in the app for the first time.
  ///
  /// Stability: development
  created('created'),

  /// Any time after Activity.onPause() or, if the app has no Activity,
  /// Context.stopService() has been called when the app was in the
  /// foreground state.
  ///
  /// Stability: development
  background('background'),

  /// Any time after Activity.onResume() or, if the app has no Activity,
  /// Context.startService() has been called when the app was in either the
  /// created or background states.
  ///
  /// Stability: development
  foreground('foreground');

  @override
  final String value;

  const AndroidState(this.value);

  @override
  String toString() => value;
}
