// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `artifact`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/artifact/)
library;

import '../semantics_base.dart';

/// `artifact.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Artifact implements OTelSemantic {
  /// The provenance filename of the built attestation which directly relates
  /// to the build artifact filename. This filename SHOULD accompany the
  /// artifact at publish time. See the
  /// [SLSA Relationship](https://slsa.dev/spec/v1.0/distributing-provenance#relationship-between-artifacts-and-attestations)
  ///  specification for more information.
  ///
  /// Examples:
  /// `golang-binary-amd64-v0.1.0.attestation, docker-image-amd64-v0.1.0.intoto.json1, release-1.tar.gz.attestation, file-name-package.tar.gz.intoto.json1`
  ///
  /// Stability: development
  artifactAttestationFilename('artifact.attestation.filename'),

  /// The full
  /// [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf)
  /// , of the built attestation. Some envelopes in the
  /// [software attestation space](https://github.com/in-toto/attestation/tree/main/spec)
  ///  also refer to this as the **digest**.
  ///
  /// Examples:
  /// `1b31dfcd5b7f9267bf2ff47651df1cfb9147b9e4df1f335accf65b4cda498408`
  ///
  /// Stability: development
  artifactAttestationHash('artifact.attestation.hash'),

  /// The id of the build
  /// [software attestation](https://slsa.dev/attestation-model).
  ///
  /// Examples: `123`
  ///
  /// Stability: development
  artifactAttestationId('artifact.attestation.id'),

  /// The human readable file name of the artifact, typically generated
  /// during build and release processes. Often includes the package name and
  /// version in the file name.
  ///
  /// Examples:
  /// `golang-binary-amd64-v0.1.0, docker-image-amd64-v0.1.0, release-1.tar.gz, file-name-package.tar.gz`
  ///
  /// Stability: development
  artifactFilename('artifact.filename'),

  /// The full
  /// [hash value (see glossary)](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5.pdf)
  /// , often found in checksum.txt on a release of the artifact and used to
  /// verify package integrity.
  ///
  /// Examples:
  /// `9ff4c52759e2c4ac70b7d517bc7fcdc1cda631ca0045271ddd1b192544f8a3e9`
  ///
  /// Stability: development
  artifactHash('artifact.hash'),

  /// The [Package URL](https://github.com/package-url/purl-spec) of the
  /// [package artifact](https://slsa.dev/spec/v1.0/terminology#package-model)
  ///  provides a standard way to identify and locate the packaged artifact.
  ///
  /// Examples:
  /// `pkg:github/package-url/purl-spec@1209109710924, pkg:npm/foo@12.12.3`
  ///
  /// Stability: development
  artifactPurl('artifact.purl'),

  /// The version of the artifact.
  ///
  /// Examples: `v0.1.0, 1.2.1, 122691-build`
  ///
  /// Stability: development
  artifactVersion('artifact.version');

  @override
  final String key;

  const Artifact(this.key);

  @override
  String toString() => key;
}
