// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `aspnetcore`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/aspnetcore/)
library;

import '../semantics_base.dart';

/// `aspnetcore.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Aspnetcore implements OTelSemantic {
  /// The result of the authentication operation.
  ///
  /// Examples: `success, failure`
  ///
  /// Stability: development
  aspnetcoreAuthenticationResult('aspnetcore.authentication.result'),

  /// The identifier that names a particular authentication handler.
  ///
  /// Examples: `Cookies, Bearer, Identity.Application`
  ///
  /// Stability: development
  aspnetcoreAuthenticationScheme('aspnetcore.authentication.scheme'),

  /// The name of the authorization policy.
  ///
  /// Examples: `RequireAdminRole`
  ///
  /// Stability: development
  aspnetcoreAuthorizationPolicy('aspnetcore.authorization.policy'),

  /// The result of calling the authorization service.
  ///
  /// Examples: `success, failure`
  ///
  /// Stability: development
  aspnetcoreAuthorizationResult('aspnetcore.authorization.result'),

  /// ASP.NET Core exception middleware handling result.
  ///
  /// Examples: `handled, unhandled`
  aspnetcoreDiagnosticsExceptionResult(
      'aspnetcore.diagnostics.exception.result'),

  /// Full type name of the
  /// [`IExceptionHandler`](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.diagnostics.iexceptionhandler)
  ///  implementation that handled the exception.
  ///
  /// Examples: `Contoso.MyHandler`
  aspnetcoreDiagnosticsHandlerType('aspnetcore.diagnostics.handler.type'),

  /// The error code for a failed identity operation.
  ///
  /// Examples: `DefaultError, PasswordMismatch`
  ///
  /// Stability: development
  aspnetcoreIdentityErrorCode('aspnetcore.identity.error_code'),

  /// The result from checking the password.
  ///
  /// Examples: `success, failure`
  ///
  /// Stability: development
  aspnetcoreIdentityPasswordCheckResult(
      'aspnetcore.identity.password_check_result'),

  /// The result of the identity operation.
  ///
  /// Examples: `success, failure`
  ///
  /// Stability: development
  aspnetcoreIdentityResult('aspnetcore.identity.result'),

  /// Whether the sign in result was success or failure.
  ///
  /// Examples: `password, two_factor`
  ///
  /// Stability: development
  aspnetcoreIdentitySignInResult('aspnetcore.identity.sign_in.result'),

  /// The authentication type.
  ///
  /// Examples: `password, two_factor`
  ///
  /// Stability: development
  aspnetcoreIdentitySignInType('aspnetcore.identity.sign_in.type'),

  /// What the token will be used for.
  ///
  /// Examples: `success, failure`
  ///
  /// Stability: development
  aspnetcoreIdentityTokenPurpose('aspnetcore.identity.token_purpose'),

  /// The result of token verification.
  ///
  /// Examples: `success, failure`
  ///
  /// Stability: development
  aspnetcoreIdentityTokenVerified('aspnetcore.identity.token_verified'),

  /// The user update type.
  ///
  /// Examples: `update, user_name, reset_password`
  ///
  /// Stability: development
  aspnetcoreIdentityUserUpdateType('aspnetcore.identity.user.update_type'),

  /// The full name of the identity user type.
  ///
  /// Examples: `Contoso.ContosoUser`
  ///
  /// Stability: development
  aspnetcoreIdentityUserType('aspnetcore.identity.user_type'),

  /// The name of the library or subsystem using the memory pool instance.
  ///
  /// Examples: `kestrel, iis`
  ///
  /// Stability: development
  aspnetcoreMemoryPoolOwner('aspnetcore.memory_pool.owner'),

  /// Rate limiting policy name.
  ///
  /// Examples: `fixed, sliding, token`
  aspnetcoreRateLimitingPolicy('aspnetcore.rate_limiting.policy'),

  /// Rate-limiting result, shows whether the lease was acquired or contains
  /// a rejection reason
  ///
  /// Examples: `acquired, request_canceled`
  aspnetcoreRateLimitingResult('aspnetcore.rate_limiting.result'),

  /// Flag indicating if request was handled by the application pipeline.
  ///
  /// Examples: `true`
  aspnetcoreRequestIsUnhandled('aspnetcore.request.is_unhandled'),

  /// A value that indicates whether the matched route is a fallback route.
  ///
  /// Examples: `true`
  aspnetcoreRoutingIsFallback('aspnetcore.routing.is_fallback'),

  /// Match result - success or failure
  ///
  /// Examples: `success, failure`
  aspnetcoreRoutingMatchStatus('aspnetcore.routing.match_status'),

  /// A flag indicating whether the sign in is persistent.
  ///
  /// Stability: development
  aspnetcoreSignInIsPersistent('aspnetcore.sign_in.is_persistent'),

  /// A value that indicates whether the user is authenticated.
  ///
  /// Examples: `true`
  aspnetcoreUserIsAuthenticated('aspnetcore.user.is_authenticated');

  @override
  final String key;

  const Aspnetcore(this.key);

  @override
  String toString() => key;
}

/// Values for `aspnetcore.authentication.result`.
///
/// Stability: development
enum AspnetcoreAuthenticationResult implements OTelSemanticValue {
  /// Authentication was successful.
  ///
  /// Stability: development
  success('success'),

  /// Authentication failed.
  ///
  /// Stability: development
  failure('failure'),

  /// No authentication information returned.
  ///
  /// Stability: development
  none('none');

  @override
  final String value;

  const AspnetcoreAuthenticationResult(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.authorization.result`.
///
/// Stability: development
enum AspnetcoreAuthorizationResult implements OTelSemanticValue {
  /// Authorization was successful.
  ///
  /// Stability: development
  success('success'),

  /// Authorization failed.
  ///
  /// Stability: development
  failure('failure');

  @override
  final String value;

  const AspnetcoreAuthorizationResult(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.diagnostics.exception.result`.
enum AspnetcoreDiagnosticsExceptionResult implements OTelSemanticValue {
  /// Exception was handled by the exception handling middleware.
  handled('handled'),

  /// Exception was not handled by the exception handling middleware.
  unhandled('unhandled'),

  /// Exception handling was skipped because the response had started.
  skipped('skipped'),

  /// Exception handling didn't run because the request was aborted.
  aborted('aborted');

  @override
  final String value;

  const AspnetcoreDiagnosticsExceptionResult(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.identity.password_check_result`.
///
/// Stability: development
enum AspnetcoreIdentityPasswordCheckResult implements OTelSemanticValue {
  /// Password check was successful.
  ///
  /// Stability: development
  success('success'),

  /// Password check was successful however the password was encoded using a
  /// deprecated algorithm and should be rehashed and updated.
  ///
  /// Stability: development
  successRehashNeeded('success_rehash_needed'),

  /// Password check failed.
  ///
  /// Stability: development
  failure('failure'),

  /// Password check couldn't proceed because the password was missing from
  /// the user.
  ///
  /// Stability: development
  passwordMissing('password_missing'),

  /// Password check couldn't proceed because the user was missing.
  ///
  /// Stability: development
  userMissing('user_missing');

  @override
  final String value;

  const AspnetcoreIdentityPasswordCheckResult(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.identity.result`.
///
/// Stability: development
enum AspnetcoreIdentityResult implements OTelSemanticValue {
  /// Identity operation was successful.
  ///
  /// Stability: development
  success('success'),

  /// Identity operation failed.
  ///
  /// Stability: development
  failure('failure');

  @override
  final String value;

  const AspnetcoreIdentityResult(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.identity.sign_in.result`.
///
/// Stability: development
enum AspnetcoreIdentitySignInResult implements OTelSemanticValue {
  /// Sign in was successful.
  ///
  /// Stability: development
  success('success'),

  /// User is locked out.
  ///
  /// Stability: development
  lockedOut('locked_out'),

  /// User is not allowed to sign in.
  ///
  /// Stability: development
  notAllowed('not_allowed'),

  /// User requires two factory authentication to sign in.
  ///
  /// Stability: development
  requiresTwoFactor('requires_two_factor'),

  /// Sign in failed.
  ///
  /// Stability: development
  failure('failure');

  @override
  final String value;

  const AspnetcoreIdentitySignInResult(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.identity.sign_in.type`.
///
/// Stability: development
enum AspnetcoreIdentitySignInType implements OTelSemanticValue {
  /// Sign in with password.
  ///
  /// Stability: development
  password('password'),

  /// Sign in with two factory recovery code.
  ///
  /// Stability: development
  twoFactorRecoveryCode('two_factor_recovery_code'),

  /// Sign in with two factor authenticator app.
  ///
  /// Stability: development
  twoFactorAuthenticator('two_factor_authenticator'),

  /// Sign in with a two factor provider.
  ///
  /// Stability: development
  twoFactor('two_factor'),

  /// Sign in with a previously registered third-party login.
  ///
  /// Stability: development
  external('external'),

  /// Sign in with passkey.
  ///
  /// Stability: development
  passkey('passkey');

  @override
  final String value;

  const AspnetcoreIdentitySignInType(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.identity.token_purpose`.
///
/// Stability: development
enum AspnetcoreIdentityTokenPurpose implements OTelSemanticValue {
  /// The token is for resetting a user password.
  ///
  /// Stability: development
  resetPassword('reset_password'),

  /// The token is for changing a user phone number.
  ///
  /// Stability: development
  changePhoneNumber('change_phone_number'),

  /// The token is for confirming user email address.
  ///
  /// Stability: development
  emailConfirmation('email_confirmation'),

  /// The token is for changing the user email address.
  ///
  /// Stability: development
  changeEmail('change_email'),

  /// The token is for changing user two factor settings.
  ///
  /// Stability: development
  twoFactor('two_factor'),

  /// Any token purpose that the instrumentation has no prior knowledge of.
  ///
  /// Stability: development
  other('_OTHER');

  @override
  final String value;

  const AspnetcoreIdentityTokenPurpose(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.identity.token_verified`.
///
/// Stability: development
enum AspnetcoreIdentityTokenVerified implements OTelSemanticValue {
  /// Token verification was successful.
  ///
  /// Stability: development
  success('success'),

  /// Token verification failed.
  ///
  /// Stability: development
  failure('failure');

  @override
  final String value;

  const AspnetcoreIdentityTokenVerified(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.identity.user.update_type`.
///
/// Stability: development
enum AspnetcoreIdentityUserUpdateType implements OTelSemanticValue {
  /// Identity user updated.
  ///
  /// Stability: development
  update('update'),

  /// Identity user name updated.
  ///
  /// Stability: development
  userName('user_name'),

  /// Identity user password added.
  ///
  /// Stability: development
  addPassword('add_password'),

  /// Identity user password changed.
  ///
  /// Stability: development
  changePassword('change_password'),

  /// Identity user security stamp updated.
  ///
  /// Stability: development
  securityStamp('security_stamp'),

  /// Identity user password reset.
  ///
  /// Stability: development
  resetPassword('reset_password'),

  /// Identity user login removed.
  ///
  /// Stability: development
  removeLogin('remove_login'),

  /// Identity user login added.
  ///
  /// Stability: development
  addLogin('add_login'),

  /// Identity user claims added.
  ///
  /// Stability: development
  addClaims('add_claims'),

  /// Identity user claim replaced.
  ///
  /// Stability: development
  replaceClaim('replace_claim'),

  /// Identity user claims removed.
  ///
  /// Stability: development
  removeClaims('remove_claims'),

  /// Identity user added to roles.
  ///
  /// Stability: development
  addToRoles('add_to_roles'),

  /// Identity user removed from roles.
  ///
  /// Stability: development
  removeFromRoles('remove_from_roles'),

  /// Identity user email set.
  ///
  /// Stability: development
  setEmail('set_email'),

  /// Identity user email confirmed.
  ///
  /// Stability: development
  confirmEmail('confirm_email'),

  /// Identity user password rehashed.
  ///
  /// Stability: development
  passwordRehash('password_rehash'),

  /// Identity user password removed.
  ///
  /// Stability: development
  removePassword('remove_password'),

  /// Identity user email changed.
  ///
  /// Stability: development
  changeEmail('change_email'),

  /// Identity user phone number set.
  ///
  /// Stability: development
  setPhoneNumber('set_phone_number'),

  /// Identity user phone number changed.
  ///
  /// Stability: development
  changePhoneNumber('change_phone_number'),

  /// Identity user two-factor authentication enabled or disabled.
  ///
  /// Stability: development
  setTwoFactorEnabled('set_two_factor_enabled'),

  /// Identity user lockout enabled or disabled.
  ///
  /// Stability: development
  setLockoutEnabled('set_lockout_enabled'),

  /// Identity user lockout end date set.
  ///
  /// Stability: development
  setLockoutEndDate('set_lockout_end_date'),

  /// Identity user access failure recorded.
  ///
  /// Stability: development
  accessFailed('access_failed'),

  /// Identity user access failure count reset.
  ///
  /// Stability: development
  resetAccessFailedCount('reset_access_failed_count'),

  /// Identity user authentication token set.
  ///
  /// Stability: development
  setAuthenticationToken('set_authentication_token'),

  /// Identity user authentication token removed.
  ///
  /// Stability: development
  removeAuthenticationToken('remove_authentication_token'),

  /// Identity user authenticator key reset.
  ///
  /// Stability: development
  resetAuthenticatorKey('reset_authenticator_key'),

  /// Identity user new two-factor recovery codes generated.
  ///
  /// Stability: development
  generateNewTwoFactorRecoveryCodes('generate_new_two_factor_recovery_codes'),

  /// Identity user two-factor recovery code redeemed.
  ///
  /// Stability: development
  redeemTwoFactorRecoveryCode('redeem_two_factor_recovery_code'),

  /// Identity user passkey set.
  ///
  /// Stability: development
  setPasskey('set_passkey'),

  /// Identity user passkey removed.
  ///
  /// Stability: development
  removePasskey('remove_passkey'),

  /// Any update type that the instrumentation has no prior knowledge of.
  ///
  /// Stability: development
  other('_OTHER');

  @override
  final String value;

  const AspnetcoreIdentityUserUpdateType(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.rate_limiting.result`.
enum AspnetcoreRateLimitingResult implements OTelSemanticValue {
  /// Lease was acquired
  acquired('acquired'),

  /// Lease request was rejected by the endpoint limiter
  endpointLimiter('endpoint_limiter'),

  /// Lease request was rejected by the global limiter
  globalLimiter('global_limiter'),

  /// Lease request was canceled
  requestCanceled('request_canceled');

  @override
  final String value;

  const AspnetcoreRateLimitingResult(this.value);

  @override
  String toString() => value;
}

/// Values for `aspnetcore.routing.match_status`.
enum AspnetcoreRoutingMatchStatus implements OTelSemanticValue {
  /// Match succeeded
  success('success'),

  /// Match failed
  failure('failure');

  @override
  final String value;

  const AspnetcoreRoutingMatchStatus(this.value);

  @override
  String toString() => value;
}
