// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `az`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/az/)
library;

import '../semantics_base.dart';

/// `az.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Az implements OTelSemantic {
  /// Deprecated, use `azure.resource_provider.namespace` instead.
  ///
  /// Examples: `Microsoft.Storage, Microsoft.KeyVault, Microsoft.ServiceBus`
  ///
  /// Stability: development
  @Deprecated('Replaced by `azure.resource_provider.namespace`.')
  azNamespace('az.namespace'),

  /// Deprecated, use `azure.service.request.id` instead.
  ///
  /// Examples: `00000000-0000-0000-0000-000000000000`
  ///
  /// Stability: development
  @Deprecated('Replaced by `azure.service.request.id`.')
  azServiceRequestId('az.service_request_id');

  @override
  final String key;

  const Az(this.key);

  @override
  String toString() => key;
}
