// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `azure`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/azure/)
library;

import '../semantics_base.dart';

/// `azure.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Azure implements OTelSemantic {
  /// The unique identifier of the client instance.
  ///
  /// Examples: `3ba4827d-4422-483f-b59f-85b74211c11d, storage-client-1`
  ///
  /// Stability: development
  azureClientId('azure.client.id'),

  /// Cosmos client connection mode.
  ///
  /// Stability: development
  azureCosmosdbConnectionMode('azure.cosmosdb.connection.mode'),

  /// Account or request
  /// [consistency level](https://learn.microsoft.com/azure/cosmos-db/consistency-levels)
  /// .
  ///
  /// Examples:
  /// `Eventual, ConsistentPrefix, BoundedStaleness, Strong, Session`
  ///
  /// Stability: development
  azureCosmosdbConsistencyLevel('azure.cosmosdb.consistency.level'),

  /// List of regions contacted during operation in the order that they were
  /// contacted. If there is more than one region listed, it indicates that
  /// the operation was performed on multiple regions i.e. cross-regional
  /// call.
  ///
  /// Examples:
  /// `["North Central US", "Australia East", "Australia Southeast"]`
  ///
  /// Stability: development
  azureCosmosdbOperationContactedRegions(
      'azure.cosmosdb.operation.contacted_regions'),

  /// The number of request units consumed by the operation.
  ///
  /// Examples: `46.18, 1.0`
  ///
  /// Stability: development
  azureCosmosdbOperationRequestCharge(
      'azure.cosmosdb.operation.request_charge'),

  /// Request payload size in bytes.
  ///
  /// Stability: development
  azureCosmosdbRequestBodySize('azure.cosmosdb.request.body.size'),

  /// Cosmos DB sub status code.
  ///
  /// Examples: `1000, 1002`
  ///
  /// Stability: development
  azureCosmosdbResponseSubStatusCode('azure.cosmosdb.response.sub_status_code'),

  /// The name of the Azure
  /// [resource group](https://learn.microsoft.com/azure/azure-resource-manager/management/manage-resource-groups-portal)
  ///  the resource belongs to.
  ///
  /// Examples: `my-resource-group, rg-myapp-prod`
  ///
  /// Stability: development
  azureResourceGroupName('azure.resource_group.name'),

  ///
  /// [Azure Resource Provider Namespace](https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers)
  ///  as recognized by the client.
  ///
  /// Examples: `Microsoft.Storage, Microsoft.KeyVault, Microsoft.ServiceBus`
  ///
  /// Stability: development
  azureResourceProviderNamespace('azure.resource_provider.namespace'),

  /// The unique identifier of the service request. It's generated by the
  /// Azure service and returned with the response.
  ///
  /// Examples: `00000000-0000-0000-0000-000000000000`
  ///
  /// Stability: development
  azureServiceRequestId('azure.service.request.id');

  @override
  final String key;

  const Azure(this.key);

  @override
  String toString() => key;
}

/// Values for `azure.cosmosdb.connection.mode`.
///
/// Stability: development
enum AzureCosmosdbConnectionMode implements OTelSemanticValue {
  /// Gateway (HTTP) connection.
  ///
  /// Stability: development
  gateway('gateway'),

  /// Direct connection.
  ///
  /// Stability: development
  direct('direct');

  @override
  final String value;

  const AzureCosmosdbConnectionMode(this.value);

  @override
  String toString() => value;
}

/// Values for `azure.cosmosdb.consistency.level`.
///
/// Stability: development
enum AzureCosmosdbConsistencyLevel implements OTelSemanticValue {
  /// Strong
  ///
  /// Stability: development
  strong('Strong'),

  /// Bounded Staleness
  ///
  /// Stability: development
  boundedStaleness('BoundedStaleness'),

  /// Session
  ///
  /// Stability: development
  session('Session'),

  /// Eventual
  ///
  /// Stability: development
  eventual('Eventual'),

  /// Consistent Prefix
  ///
  /// Stability: development
  consistentPrefix('ConsistentPrefix');

  @override
  final String value;

  const AzureCosmosdbConsistencyLevel(this.value);

  @override
  String toString() => value;
}
