// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0
// (registry v1.44.0 @ e10a9308).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `browser`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/browser/)
library;

import '../semantics_base.dart';

/// `browser.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Browser implements OTelSemantic {
  /// Array of brand name and version separated by a space
  ///
  /// Examples: `[" Not A;Brand 99", "Chromium 99", "Chrome 99"]`
  ///
  /// Stability: development
  browserBrands('browser.brands'),

  /// Absolute URL of the current browser document according to
  /// [RFC3986](https://www.rfc-editor.org/rfc/rfc3986).
  ///
  /// Examples: `https://www.example.com/search?q=OpenTelemetry#SemConv`
  ///
  /// Stability: development
  browserDocumentUrlFull('browser.document.url.full'),

  /// Preferred language of the user using the browser
  ///
  /// Examples: `en, en-US, fr, fr-FR`
  ///
  /// Stability: development
  browserLanguage('browser.language'),

  /// A boolean that is true if the browser is running on a mobile device
  ///
  /// Stability: development
  browserMobile('browser.mobile'),

  /// The platform on which the browser is running
  ///
  /// Examples: `Windows, macOS, Android`
  ///
  /// Stability: development
  browserPlatform('browser.platform'),

  /// The delta between the current value and the last-reported value. See
  /// [delta](https://github.com/GoogleChrome/web-vitals?tab=readme-ov-file#report-only-the-delta-of-changes)
  /// .
  ///
  /// Examples: `0.2`
  ///
  /// Stability: development
  browserWebVitalDelta('browser.web_vital.delta'),

  /// A unique ID representing this particular metric instance.
  ///
  /// Examples: `v3-1677874579383-6381583661209`
  ///
  /// Stability: development
  browserWebVitalId('browser.web_vital.id'),

  /// Name of the web vital.
  ///
  /// Examples: `cls`
  ///
  /// Stability: development
  browserWebVitalName('browser.web_vital.name'),

  /// The type of navigation, as reported by the
  /// [Navigation Timing API](https://developer.mozilla.org/docs/Web/API/PerformanceNavigationTiming/type)
  /// , with additional values reported by the web-vitals library.
  ///
  /// Examples: `navigate`
  ///
  /// Stability: development
  browserWebVitalNavigationType('browser.web_vital.navigation_type'),

  /// The rating of the web vital value against the "good", "needs
  /// improvement", and "poor" thresholds defined for the metric.
  ///
  /// Examples: `good`
  ///
  /// Stability: development
  browserWebVitalRating('browser.web_vital.rating'),

  /// Value of the web vital.
  ///
  /// Examples: `1.0`
  ///
  /// Stability: development
  browserWebVitalValue('browser.web_vital.value');

  @override
  final String key;

  const Browser(this.key);

  @override
  String toString() => key;
}

/// Values for `browser.web_vital.name`.
///
/// Stability: development
enum BrowserWebVitalName implements OTelSemanticValue {
  /// Cumulative Layout Shift. See [cls](https://web.dev/articles/cls).
  ///
  /// Stability: development
  cls('cls'),

  /// Largest Contentful Paint. See [lcp](https://web.dev/articles/lcp).
  ///
  /// Stability: development
  lcp('lcp'),

  /// First Contentful Paint. See [fcp](https://web.dev/articles/fcp).
  ///
  /// Stability: development
  fcp('fcp'),

  /// Interaction to Next Paint. See [inp](https://web.dev/articles/inp).
  ///
  /// Stability: development
  inp('inp'),

  /// Time to First Byte. See [ttfb](https://web.dev/articles/ttfb).
  ///
  /// Stability: development
  ttfb('ttfb'),

  /// First Input Delay. See [fid](https://web.dev/articles/fid).
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by Interaction to Next Paint (`inp`), which became a Core Web Vital in March 2024. See [inp](https://web.dev/articles/inp).')
  fid('fid');

  @override
  final String value;

  const BrowserWebVitalName(this.value);

  @override
  String toString() => value;
}

/// Values for `browser.web_vital.navigation_type`.
///
/// Stability: development
enum BrowserWebVitalNavigationType implements OTelSemanticValue {
  /// Navigation started by clicking a link, entering a URL, form submission,
  /// or a script operation.
  ///
  /// Stability: development
  navigate('navigate'),

  /// Navigation through a reload operation or a `Location.reload()` call.
  ///
  /// Stability: development
  reload('reload'),

  /// Navigation through the browser's history traversal (e.g. back/forward
  /// buttons).
  ///
  /// Stability: development
  backForward('back-forward'),

  /// Navigation restoring a page from the back/forward cache (bfcache).
  ///
  /// Stability: development
  backForwardCache('back-forward-cache'),

  /// Navigation to a page that was prerendered.
  ///
  /// Stability: development
  prerender('prerender'),

  /// Navigation restoring a page that was previously discarded by the
  /// browser.
  ///
  /// Stability: development
  restore('restore');

  @override
  final String value;

  const BrowserWebVitalNavigationType(this.value);

  @override
  String toString() => value;
}

/// Values for `browser.web_vital.rating`.
///
/// Stability: development
enum BrowserWebVitalRating implements OTelSemanticValue {
  /// The metric value is within the "good" threshold.
  ///
  /// Stability: development
  good('good'),

  /// The metric value is within the "needs improvement" threshold.
  ///
  /// Stability: development
  needsImprovement('needs-improvement'),

  /// The metric value is within the "poor" threshold.
  ///
  /// Stability: development
  poor('poor');

  @override
  final String value;

  const BrowserWebVitalRating(this.value);

  @override
  String toString() => value;
}
