// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `cicd`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/cicd/)
library;

import '../semantics_base.dart';

/// `cicd.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Cicd implements OTelSemantic {
  /// The kind of action a pipeline run is performing.
  ///
  /// Examples: `BUILD, RUN, SYNC`
  ///
  /// Stability: release_candidate
  cicdPipelineActionName('cicd.pipeline.action.name'),

  /// The human readable name of the pipeline within a CI/CD system.
  ///
  /// Examples:
  /// `Build and Test, Lint, Deploy Go Project, deploy_to_environment`
  ///
  /// Stability: release_candidate
  cicdPipelineName('cicd.pipeline.name'),

  /// The result of a pipeline run.
  ///
  /// Examples: `success, failure, timeout, skip`
  ///
  /// Stability: release_candidate
  cicdPipelineResult('cicd.pipeline.result'),

  /// The unique identifier of a pipeline run within a CI/CD system.
  ///
  /// Examples: `120912`
  ///
  /// Stability: release_candidate
  cicdPipelineRunId('cicd.pipeline.run.id'),

  /// The pipeline run goes through these states during its lifecycle.
  ///
  /// Examples: `pending, executing, finalizing`
  ///
  /// Stability: release_candidate
  cicdPipelineRunState('cicd.pipeline.run.state'),

  /// The [URL](https://wikipedia.org/wiki/URL) of the pipeline run,
  /// providing the complete address in order to locate and identify the
  /// pipeline run.
  ///
  /// Examples:
  /// `https://github.com/open-telemetry/semantic-conventions/actions/runs/9753949763?pr=1075`
  ///
  /// Stability: release_candidate
  cicdPipelineRunUrlFull('cicd.pipeline.run.url.full'),

  /// The human readable name of a task within a pipeline. Task here most
  /// closely aligns with a
  /// [computing process](https://wikipedia.org/wiki/Pipeline_(computing)) in
  /// a pipeline. Other terms for tasks include commands, steps, and
  /// procedures.
  ///
  /// Examples: `Run GoLang Linter, Go Build, go-test, deploy_binary`
  ///
  /// Stability: release_candidate
  cicdPipelineTaskName('cicd.pipeline.task.name'),

  /// The unique identifier of a task run within a pipeline.
  ///
  /// Examples: `12097`
  ///
  /// Stability: release_candidate
  cicdPipelineTaskRunId('cicd.pipeline.task.run.id'),

  /// The result of a task run.
  ///
  /// Examples: `success, failure, timeout, skip`
  ///
  /// Stability: release_candidate
  cicdPipelineTaskRunResult('cicd.pipeline.task.run.result'),

  /// The [URL](https://wikipedia.org/wiki/URL) of the pipeline task run,
  /// providing the complete address in order to locate and identify the
  /// pipeline task run.
  ///
  /// Examples:
  /// `https://github.com/open-telemetry/semantic-conventions/actions/runs/9753949763/job/26920038674?pr=1075`
  ///
  /// Stability: release_candidate
  cicdPipelineTaskRunUrlFull('cicd.pipeline.task.run.url.full'),

  /// The type of the task within a pipeline.
  ///
  /// Examples: `build, test, deploy`
  ///
  /// Stability: release_candidate
  cicdPipelineTaskType('cicd.pipeline.task.type'),

  /// The name of a component of the CI/CD system.
  ///
  /// Examples: `controller, scheduler, agent`
  ///
  /// Stability: release_candidate
  cicdSystemComponent('cicd.system.component'),

  /// The unique identifier of a worker within a CI/CD system.
  ///
  /// Examples: `abc123, 10.0.1.2, controller`
  ///
  /// Stability: release_candidate
  cicdWorkerId('cicd.worker.id'),

  /// The name of a worker within a CI/CD system.
  ///
  /// Examples: `agent-abc, controller, Ubuntu LTS`
  ///
  /// Stability: release_candidate
  cicdWorkerName('cicd.worker.name'),

  /// The state of a CI/CD worker / agent.
  ///
  /// Examples: `available, busy, offline`
  ///
  /// Stability: release_candidate
  cicdWorkerState('cicd.worker.state'),

  /// The [URL](https://wikipedia.org/wiki/URL) of the worker, providing the
  /// complete address in order to locate and identify the worker.
  ///
  /// Examples: `https://cicd.example.org/worker/abc123`
  ///
  /// Stability: release_candidate
  cicdWorkerUrlFull('cicd.worker.url.full');

  @override
  final String key;

  const Cicd(this.key);

  @override
  String toString() => key;
}

/// Values for `cicd.pipeline.action.name`.
///
/// Stability: release_candidate
enum CicdPipelineActionName implements OTelSemanticValue {
  /// The pipeline run is executing a build.
  ///
  /// Stability: release_candidate
  build('BUILD'),

  /// The pipeline run is executing.
  ///
  /// Stability: release_candidate
  run('RUN'),

  /// The pipeline run is executing a sync.
  ///
  /// Stability: release_candidate
  sync('SYNC');

  @override
  final String value;

  const CicdPipelineActionName(this.value);

  @override
  String toString() => value;
}

/// Values for `cicd.pipeline.result`.
///
/// Stability: release_candidate
enum CicdPipelineResult implements OTelSemanticValue {
  /// The pipeline run finished successfully.
  ///
  /// Stability: release_candidate
  success('success'),

  /// The pipeline run did not finish successfully, eg. due to a compile
  /// error or a failing test. Such failures are usually detected by non-zero
  /// exit codes of the tools executed in the pipeline run.
  ///
  /// Stability: release_candidate
  failure('failure'),

  /// The pipeline run failed due to an error in the CI/CD system, eg. due to
  /// the worker being killed.
  ///
  /// Stability: release_candidate
  error('error'),

  /// A timeout caused the pipeline run to be interrupted.
  ///
  /// Stability: release_candidate
  timeout('timeout'),

  /// The pipeline run was cancelled, eg. by a user manually cancelling the
  /// pipeline run.
  ///
  /// Stability: release_candidate
  cancellation('cancellation'),

  /// The pipeline run was skipped, eg. due to a precondition not being met.
  ///
  /// Stability: release_candidate
  skip('skip');

  @override
  final String value;

  const CicdPipelineResult(this.value);

  @override
  String toString() => value;
}

/// Values for `cicd.pipeline.run.state`.
///
/// Stability: release_candidate
enum CicdPipelineRunState implements OTelSemanticValue {
  /// The run pending state spans from the event triggering the pipeline run
  /// until the execution of the run starts (eg. time spent in a queue,
  /// provisioning agents, creating run resources).
  ///
  /// Stability: release_candidate
  pending('pending'),

  /// The executing state spans the execution of any run tasks (eg. build,
  /// test).
  ///
  /// Stability: release_candidate
  executing('executing'),

  /// The finalizing state spans from when the run has finished executing
  /// (eg. cleanup of run resources).
  ///
  /// Stability: release_candidate
  finalizing('finalizing');

  @override
  final String value;

  const CicdPipelineRunState(this.value);

  @override
  String toString() => value;
}

/// Values for `cicd.pipeline.task.run.result`.
///
/// Stability: release_candidate
enum CicdPipelineTaskRunResult implements OTelSemanticValue {
  /// The task run finished successfully.
  ///
  /// Stability: release_candidate
  success('success'),

  /// The task run did not finish successfully, eg. due to a compile error or
  /// a failing test. Such failures are usually detected by non-zero exit
  /// codes of the tools executed in the task run.
  ///
  /// Stability: release_candidate
  failure('failure'),

  /// The task run failed due to an error in the CI/CD system, eg. due to the
  /// worker being killed.
  ///
  /// Stability: release_candidate
  error('error'),

  /// A timeout caused the task run to be interrupted.
  ///
  /// Stability: release_candidate
  timeout('timeout'),

  /// The task run was cancelled, eg. by a user manually cancelling the task
  /// run.
  ///
  /// Stability: release_candidate
  cancellation('cancellation'),

  /// The task run was skipped, eg. due to a precondition not being met.
  ///
  /// Stability: release_candidate
  skip('skip');

  @override
  final String value;

  const CicdPipelineTaskRunResult(this.value);

  @override
  String toString() => value;
}

/// Values for `cicd.pipeline.task.type`.
///
/// Stability: release_candidate
enum CicdPipelineTaskType implements OTelSemanticValue {
  /// build
  ///
  /// Stability: release_candidate
  build('build'),

  /// test
  ///
  /// Stability: release_candidate
  test('test'),

  /// deploy
  ///
  /// Stability: release_candidate
  deploy('deploy');

  @override
  final String value;

  const CicdPipelineTaskType(this.value);

  @override
  String toString() => value;
}

/// Values for `cicd.worker.state`.
///
/// Stability: release_candidate
enum CicdWorkerState implements OTelSemanticValue {
  /// The worker is not performing work for the CI/CD system. It is available
  /// to the CI/CD system to perform work on (online / idle).
  ///
  /// Stability: release_candidate
  available('available'),

  /// The worker is performing work for the CI/CD system.
  ///
  /// Stability: release_candidate
  busy('busy'),

  /// The worker is not available to the CI/CD system (disconnected / down).
  ///
  /// Stability: release_candidate
  offline('offline');

  @override
  final String value;

  const CicdWorkerState(this.value);

  @override
  String toString() => value;
}
