// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `client`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/client/)
library;

import '../semantics_base.dart';

/// `client.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Client implements OTelSemantic {
  /// Client address - domain name if available without reverse DNS lookup;
  /// otherwise, IP address or Unix domain socket name.
  ///
  /// Examples: `client.example.com, 10.1.2.80, /tmp/my.sock`
  clientAddress('client.address'),

  /// Client port number.
  ///
  /// Examples: `65123`
  clientPort('client.port');

  @override
  final String key;

  const Client(this.key);

  @override
  String toString() => key;
}
