// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `cloudfoundry`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/cloudfoundry/)
library;

import '../semantics_base.dart';

/// `cloudfoundry.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Cloudfoundry implements OTelSemantic {
  /// The guid of the application.
  ///
  /// Examples: `218fc5a9-a5f1-4b54-aa05-46717d0ab26d`
  ///
  /// Stability: development
  cloudfoundryAppId('cloudfoundry.app.id'),

  /// The index of the application instance. 0 when just one instance is
  /// active.
  ///
  /// Examples: `0, 1`
  ///
  /// Stability: development
  cloudfoundryAppInstanceId('cloudfoundry.app.instance.id'),

  /// The name of the application.
  ///
  /// Examples: `my-app-name`
  ///
  /// Stability: development
  cloudfoundryAppName('cloudfoundry.app.name'),

  /// The guid of the CloudFoundry org the application is running in.
  ///
  /// Examples: `218fc5a9-a5f1-4b54-aa05-46717d0ab26d`
  ///
  /// Stability: development
  cloudfoundryOrgId('cloudfoundry.org.id'),

  /// The name of the CloudFoundry organization the app is running in.
  ///
  /// Examples: `my-org-name`
  ///
  /// Stability: development
  cloudfoundryOrgName('cloudfoundry.org.name'),

  /// The UID identifying the process.
  ///
  /// Examples: `218fc5a9-a5f1-4b54-aa05-46717d0ab26d`
  ///
  /// Stability: development
  cloudfoundryProcessId('cloudfoundry.process.id'),

  /// The type of process.
  ///
  /// Examples: `web`
  ///
  /// Stability: development
  cloudfoundryProcessType('cloudfoundry.process.type'),

  /// The guid of the CloudFoundry space the application is running in.
  ///
  /// Examples: `218fc5a9-a5f1-4b54-aa05-46717d0ab26d`
  ///
  /// Stability: development
  cloudfoundrySpaceId('cloudfoundry.space.id'),

  /// The name of the CloudFoundry space the application is running in.
  ///
  /// Examples: `my-space-name`
  ///
  /// Stability: development
  cloudfoundrySpaceName('cloudfoundry.space.name'),

  /// A guid or another name describing the event source.
  ///
  /// Examples: `cf/gorouter`
  ///
  /// Stability: development
  cloudfoundrySystemId('cloudfoundry.system.id'),

  /// A guid describing the concrete instance of the event source.
  ///
  /// Examples: `218fc5a9-a5f1-4b54-aa05-46717d0ab26d`
  ///
  /// Stability: development
  cloudfoundrySystemInstanceId('cloudfoundry.system.instance.id');

  @override
  final String key;

  const Cloudfoundry(this.key);

  @override
  String toString() => key;
}
