// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `code`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/code/)
library;

import '../semantics_base.dart';

/// `code.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Code implements OTelSemantic {
  /// Deprecated, use `code.column.number`
  ///
  /// Examples: `16`
  ///
  /// Stability: development
  @Deprecated('Replaced by `code.column.number`.')
  codeColumn('code.column'),

  /// The column number in `code.file.path` best representing the operation.
  /// It SHOULD point within the code unit named in `code.function.name`.
  /// This attribute MUST NOT be used on the Profile signal since the data is
  /// already captured in 'message Line'. This constraint is imposed to
  /// prevent redundancy and maintain data integrity.
  ///
  /// Examples: `16`
  codeColumnNumber('code.column.number'),

  /// The source code file name that identifies the code unit as uniquely as
  /// possible (preferably an absolute file path). This attribute MUST NOT be
  /// used on the Profile signal since the data is already captured in
  /// 'message Function'. This constraint is imposed to prevent redundancy
  /// and maintain data integrity.
  ///
  /// Examples: `/usr/local/MyApplication/content_root/app/index.php`
  codeFilePath('code.file.path'),

  /// Deprecated, use `code.file.path` instead
  ///
  /// Examples: `/usr/local/MyApplication/content_root/app/index.php`
  ///
  /// Stability: development
  @Deprecated('Replaced by `code.file.path`.')
  codeFilepath('code.filepath'),

  /// Deprecated, use `code.function.name` instead
  ///
  /// Examples: `serveRequest`
  ///
  /// Stability: development
  @Deprecated(
      'Value should be included in `code.function.name` which is expected to be a fully-qualified name.')
  codeFunction('code.function'),

  /// The method or function fully-qualified name without arguments. The
  /// value should fit the natural representation of the language runtime,
  /// which is also likely the same used within `code.stacktrace` attribute
  /// value. This attribute MUST NOT be used on the Profile signal since the
  /// data is already captured in 'message Function'. This constraint is
  /// imposed to prevent redundancy and maintain data integrity.
  ///
  /// Examples:
  /// `com.example.MyHttpService.serveRequest, GuzzleHttp\Client::transfer, fopen`
  codeFunctionName('code.function.name'),

  /// The line number in `code.file.path` best representing the operation. It
  /// SHOULD point within the code unit named in `code.function.name`. This
  /// attribute MUST NOT be used on the Profile signal since the data is
  /// already captured in 'message Line'. This constraint is imposed to
  /// prevent redundancy and maintain data integrity.
  ///
  /// Examples: `42`
  codeLineNumber('code.line.number'),

  /// Deprecated, use `code.line.number` instead
  ///
  /// Examples: `42`
  ///
  /// Stability: development
  @Deprecated('Replaced by `code.line.number`.')
  codeLineno('code.lineno'),

  /// Deprecated, namespace is now included into `code.function.name`
  ///
  /// Examples: `com.example.MyHttpService`
  ///
  /// Stability: development
  @Deprecated(
      'Value should be included in `code.function.name` which is expected to be a fully-qualified name.')
  codeNamespace('code.namespace'),

  /// A stacktrace as a string in the natural representation for the language
  /// runtime. The representation is identical to
  /// [`exception.stacktrace`](/docs/exceptions/exceptions-spans.md#stacktrace-representation)
  /// . This attribute MUST NOT be used on the Profile signal since the data
  /// is already captured in 'message Location'. This constraint is imposed
  /// to prevent redundancy and maintain data integrity.
  ///
  /// Examples:
  /// `at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\n at com.example.GenerateTrace.methodA(GenerateTrace.java:9)\n at com.example.GenerateTrace.main(GenerateTrace.java:5) `
  codeStacktrace('code.stacktrace');

  @override
  final String key;

  const Code(this.key);

  @override
  String toString() => key;
}
