// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `container`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/container/)
library;

import '../semantics_base.dart';

/// `container.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum ContainerAttributes implements OTelSemantic {
  /// The command used to run the container (i.e. the command name).
  ///
  /// Examples: `otelcontribcol`
  ///
  /// Stability: development
  containerCommand('container.command'),

  /// All the command arguments (including the command/executable itself) run
  /// by the container.
  ///
  /// Examples: `["otelcontribcol", "--config", "config.yaml"]`
  ///
  /// Stability: development
  containerCommandArgs('container.command_args'),

  /// The full command run by the container as a single string representing
  /// the full command.
  ///
  /// Examples: `otelcontribcol --config config.yaml`
  ///
  /// Stability: development
  containerCommandLine('container.command_line'),

  /// Deprecated, use `cpu.mode` instead.
  ///
  /// Examples: `user, kernel`
  ///
  /// Stability: development
  @Deprecated('Replaced by `cpu.mode`.')
  containerCpuState('container.cpu.state'),

  /// The name of the CSI (
  /// [Container Storage Interface](https://github.com/container-storage-interface/spec)
  /// ) plugin used by the volume.
  ///
  /// Examples: `pd.csi.storage.gke.io`
  ///
  /// Stability: development
  containerCsiPluginName('container.csi.plugin.name'),

  /// The unique volume ID returned by the CSI (
  /// [Container Storage Interface](https://github.com/container-storage-interface/spec)
  /// ) plugin.
  ///
  /// Examples: `projects/my-gcp-project/zones/my-gcp-zone/disks/my-gcp-disk`
  ///
  /// Stability: development
  containerCsiVolumeId('container.csi.volume.id'),

  /// Container ID. Usually a UUID, as for example used to
  /// [identify Docker containers](https://docs.docker.com/engine/containers/run/#container-identification)
  /// . The UUID might be abbreviated.
  ///
  /// Examples: `a3bf90e006b2`
  containerId('container.id'),

  /// Runtime specific image identifier. Usually a hash algorithm followed by
  /// a UUID.
  ///
  /// Examples:
  /// `sha256:19c92d0a00d1b66d897bceaa7319bee0dd38a10a851c60bcec9474aa3f01e50f`
  ///
  /// Stability: development
  containerImageId('container.image.id'),

  /// Name of the image the container was built on.
  ///
  /// Examples: `gcr.io/opentelemetry/operator`
  containerImageName('container.image.name'),

  /// Repo digests of the container image as provided by the container
  /// runtime.
  ///
  /// Examples:
  /// `["example@sha256:afcc7f1ac1b49db317a7196c902e61c6c3c4607d63599ee1a82d702d249a0ccb", "internal.registry.example.com:5000/example@sha256:b69959407d21e8a062e0416bf13405bb2b71ed7a84dde4158ebafacfa06f5578"]`
  containerImageRepoDigests('container.image.repo_digests'),

  /// Container image tags. An example can be found in
  /// [Docker Image Inspect](https://docs.docker.com/reference/api/engine/version/v1.52/#tag/Image/operation/ImageInspect)
  /// . Should be only the `<tag>` section of the full name for example from
  /// `registry.example.com/my-org/my-image:<tag>`.
  ///
  /// Examples: `["v1.27.1", "3.5.7-0"]`
  containerImageTags('container.image.tags'),

  /// Container labels, `<key>` being the label name, the value being the
  /// label value.
  ///
  /// Examples: `nginx`
  ///
  /// Stability: development
  containerLabel('container.label'),

  /// Deprecated, use `container.label` instead.
  ///
  /// Examples: `nginx`
  ///
  /// Stability: development
  @Deprecated('Replaced by `container.label`.')
  containerLabels('container.labels'),

  /// Container name used by container runtime.
  ///
  /// Examples: `opentelemetry-autoconf`
  ///
  /// Stability: development
  containerName('container.name'),

  /// The container runtime managing this container.
  ///
  /// Examples: `docker, containerd, rkt`
  ///
  /// Stability: development
  @Deprecated('Replaced by `container.runtime.name`.')
  containerRuntime('container.runtime'),

  /// A description about the runtime which could include, for example
  /// details about the CRI/API version being used or other customizations.
  ///
  /// Examples: `docker://19.3.1 - CRI: 1.22.0`
  ///
  /// Stability: development
  containerRuntimeDescription('container.runtime.description'),

  /// The container runtime managing this container.
  ///
  /// Examples: `docker, containerd, rkt`
  ///
  /// Stability: development
  containerRuntimeName('container.runtime.name'),

  /// The version of the runtime of this process, as returned by the runtime
  /// without modification.
  ///
  /// Examples: `1.0.0`
  ///
  /// Stability: development
  containerRuntimeVersion('container.runtime.version');

  @override
  final String key;

  const ContainerAttributes(this.key);

  @override
  String toString() => key;
}

/// Values for `container.cpu.state`.
///
/// Stability: development
@Deprecated('Replaced by `cpu.mode`.')
enum ContainerCpuState implements OTelSemanticValue {
  /// When tasks of the cgroup are in user mode (Linux). When all container
  /// processes are in user mode (Windows).
  ///
  /// Stability: development
  user('user'),

  /// When CPU is used by the system (host OS)
  ///
  /// Stability: development
  system('system'),

  /// When tasks of the cgroup are in kernel mode (Linux). When all container
  /// processes are in kernel mode (Windows).
  ///
  /// Stability: development
  kernel('kernel');

  @override
  final String value;

  const ContainerCpuState(this.value);

  @override
  String toString() => value;
}
