// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `destination`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/destination/)
library;

import '../semantics_base.dart';

/// `destination.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Destination implements OTelSemantic {
  /// Destination address - domain name if available without reverse DNS
  /// lookup; otherwise, IP address or Unix domain socket name.
  ///
  /// Examples: `destination.example.com, 10.1.2.80, /tmp/my.sock`
  ///
  /// Stability: development
  destinationAddress('destination.address'),

  /// Destination port number
  ///
  /// Examples: `3389, 2888`
  ///
  /// Stability: development
  destinationPort('destination.port');

  @override
  final String key;

  const Destination(this.key);

  @override
  String toString() => key;
}
