// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `dns`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/dns/)
library;

import '../semantics_base.dart';

/// `dns.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Dns implements OTelSemantic {
  /// The list of IPv4 or IPv6 addresses resolved during DNS lookup.
  ///
  /// Examples: `["10.0.0.1", "2001:0db8:85a3:0000:0000:8a2e:0370:7334"]`
  ///
  /// Stability: development
  dnsAnswers('dns.answers'),

  /// The name being queried.
  ///
  /// Examples: `www.example.com, opentelemetry.io`
  ///
  /// Stability: development
  dnsQuestionName('dns.question.name');

  @override
  final String key;

  const Dns(this.key);

  @override
  String toString() => key;
}
