// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `dotnet`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/dotnet/)
library;

import '../semantics_base.dart';

/// `dotnet.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Dotnet implements OTelSemantic {
  /// Name of the garbage collector managed heap generation.
  ///
  /// Examples: `gen0, gen1, gen2`
  dotnetGcHeapGeneration('dotnet.gc.heap.generation');

  @override
  final String key;

  const Dotnet(this.key);

  @override
  String toString() => key;
}

/// Values for `dotnet.gc.heap.generation`.
enum DotnetGcHeapGeneration implements OTelSemanticValue {
  /// Generation 0
  gen0('gen0'),

  /// Generation 1
  gen1('gen1'),

  /// Generation 2
  gen2('gen2'),

  /// Large Object Heap
  loh('loh'),

  /// Pinned Object Heap
  poh('poh');

  @override
  final String value;

  const DotnetGcHeapGeneration(this.value);

  @override
  String toString() => value;
}
