// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `elasticsearch`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/elasticsearch/)
library;

import '../semantics_base.dart';

/// `elasticsearch.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Elasticsearch implements OTelSemantic {
  /// Represents the human-readable identifier of the node/instance to which
  /// a request was routed.
  ///
  /// Examples: `instance-0000000001`
  ///
  /// Stability: development
  elasticsearchNodeName('elasticsearch.node.name');

  @override
  final String key;

  const Elasticsearch(this.key);

  @override
  String toString() => key;
}
