// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `exception`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/exception/)
library;

import '../semantics_base.dart';

/// `exception.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum ExceptionAttributes implements OTelSemantic {
  /// Indicates that the exception is escaping the scope of the span.
  @Deprecated(
      'It\'s no longer recommended to record exceptions that are handled and do not escape the scope of a span.')
  exceptionEscaped('exception.escaped'),

  /// The exception message.
  ///
  /// Examples:
  /// `Division by zero, Can't convert 'int' object to str implicitly`
  exceptionMessage('exception.message'),

  /// A stacktrace as a string in the natural representation for the language
  /// runtime. The representation is to be determined and documented by each
  /// language SIG.
  ///
  /// Examples:
  /// `Exception in thread "main" java.lang.RuntimeException: Test exception\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\n at com.example.GenerateTrace.methodA(GenerateTrace.java:9)\n at com.example.GenerateTrace.main(GenerateTrace.java:5) `
  exceptionStacktrace('exception.stacktrace'),

  /// The type of the exception (its fully-qualified class name, if
  /// applicable). The dynamic type of the exception should be preferred over
  /// the static type in languages that support it.
  ///
  /// Examples: `java.net.ConnectException, OSError`
  exceptionType('exception.type');

  @override
  final String key;

  const ExceptionAttributes(this.key);

  @override
  String toString() => key;
}
