// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `faas`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/faas/)
library;

import '../semantics_base.dart';

/// `faas.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Faas implements OTelSemantic {
  /// A boolean that is true if the serverless function is executed for the
  /// first time (aka cold-start).
  ///
  /// Stability: development
  faasColdstart('faas.coldstart'),

  /// A string containing the schedule period as
  /// [Cron Expression](https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm)
  /// .
  ///
  /// Examples: `0/5 * * * ? *`
  ///
  /// Stability: development
  faasCron('faas.cron'),

  /// The name of the source on which the triggering operation was performed.
  /// For example, in Cloud Storage or S3 corresponds to the bucket name, and
  /// in Cosmos DB to the database name.
  ///
  /// Examples: `myBucketName, myDbName`
  ///
  /// Stability: development
  faasDocumentCollection('faas.document.collection'),

  /// The document name/table subjected to the operation. For example, in
  /// Cloud Storage or S3 is the name of the file, and in Cosmos DB the table
  /// name.
  ///
  /// Examples: `myFile.txt, myTableName`
  ///
  /// Stability: development
  faasDocumentName('faas.document.name'),

  /// Describes the type of the operation that was performed on the data.
  ///
  /// Stability: development
  faasDocumentOperation('faas.document.operation'),

  /// A string containing the time when the data was accessed in the
  /// [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)
  /// format expressed in [UTC](https://www.w3.org/TR/NOTE-datetime).
  ///
  /// Examples: `2020-01-23T13:47:06Z`
  ///
  /// Stability: development
  faasDocumentTime('faas.document.time'),

  /// The execution environment ID as a string, that will be potentially
  /// reused for other invocations to the same function/function version.
  ///
  /// Examples: `2021/06/28/[$LATEST]2f399eb14537447da05ab2a2e39309de`
  ///
  /// Stability: development
  faasInstance('faas.instance'),

  /// The invocation ID of the current function invocation.
  ///
  /// Examples: `af9d5aa4-a685-4c5f-a22b-444f80b3cc28`
  ///
  /// Stability: development
  faasInvocationId('faas.invocation_id'),

  /// The name of the invoked function.
  ///
  /// Examples: `my-function`
  ///
  /// Stability: development
  faasInvokedName('faas.invoked_name'),

  /// The cloud provider of the invoked function.
  ///
  /// Stability: development
  faasInvokedProvider('faas.invoked_provider'),

  /// The cloud region of the invoked function.
  ///
  /// Examples: `eu-central-1`
  ///
  /// Stability: development
  faasInvokedRegion('faas.invoked_region'),

  /// The amount of memory available to the serverless function converted to
  /// Bytes.
  ///
  /// Examples: `134217728`
  ///
  /// Stability: development
  faasMaxMemory('faas.max_memory'),

  /// The name of the single function that this runtime instance executes.
  ///
  /// Examples: `my-function, myazurefunctionapp/some-function-name`
  ///
  /// Stability: development
  faasName('faas.name'),

  /// A string containing the function invocation time in the
  /// [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)
  /// format expressed in [UTC](https://www.w3.org/TR/NOTE-datetime).
  ///
  /// Examples: `2020-01-23T13:47:06Z`
  ///
  /// Stability: development
  faasTime('faas.time'),

  /// Type of the trigger which caused this function invocation.
  ///
  /// Stability: development
  faasTrigger('faas.trigger'),

  /// The immutable version of the function being executed.
  ///
  /// Examples: `26, pinkfroid-00002`
  ///
  /// Stability: development
  faasVersion('faas.version');

  @override
  final String key;

  const Faas(this.key);

  @override
  String toString() => key;
}

/// Values for `faas.document.operation`.
///
/// Stability: development
enum FaasDocumentOperation implements OTelSemanticValue {
  /// When a new object is created.
  ///
  /// Stability: development
  insert('insert'),

  /// When an object is modified.
  ///
  /// Stability: development
  edit('edit'),

  /// When an object is deleted.
  ///
  /// Stability: development
  delete('delete');

  @override
  final String value;

  const FaasDocumentOperation(this.value);

  @override
  String toString() => value;
}

/// Values for `faas.invoked_provider`.
///
/// Stability: development
enum FaasInvokedProvider implements OTelSemanticValue {
  /// Alibaba Cloud
  ///
  /// Stability: development
  alibabaCloud('alibaba_cloud'),

  /// Amazon Web Services
  ///
  /// Stability: development
  aws('aws'),

  /// Microsoft Azure
  ///
  /// Stability: development
  azure('azure'),

  /// Google Cloud Platform
  ///
  /// Stability: development
  gcp('gcp'),

  /// Tencent Cloud
  ///
  /// Stability: development
  tencentCloud('tencent_cloud');

  @override
  final String value;

  const FaasInvokedProvider(this.value);

  @override
  String toString() => value;
}

/// Values for `faas.trigger`.
///
/// Stability: development
enum FaasTrigger implements OTelSemanticValue {
  /// A response to some data source operation such as a database or
  /// filesystem read/write
  ///
  /// Stability: development
  datasource('datasource'),

  /// To provide an answer to an inbound HTTP request
  ///
  /// Stability: development
  http('http'),

  /// A function is set to be executed when messages are sent to a messaging
  /// system
  ///
  /// Stability: development
  pubsub('pubsub'),

  /// A function is scheduled to be executed regularly
  ///
  /// Stability: development
  timer('timer'),

  /// If none of the others apply
  ///
  /// Stability: development
  other('other');

  @override
  final String value;

  const FaasTrigger(this.value);

  @override
  String toString() => value;
}
