// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `feature_flag`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/feature-flag/)
library;

import '../semantics_base.dart';

/// `feature_flag.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum FeatureFlag implements OTelSemantic {
  /// The unique identifier for the flag evaluation context. For example, the
  /// targeting key.
  ///
  /// Examples: `5157782b-2203-4c80-a857-dbbd5e7761db`
  ///
  /// Stability: release_candidate
  featureFlagContextId('feature_flag.context.id'),

  /// A message providing more detail about an error that occurred during
  /// feature flag evaluation in human-readable form.
  ///
  /// Examples:
  /// `Unexpected input type: string, The user has exceeded their storage quota`
  ///
  /// Stability: release_candidate
  featureFlagErrorMessage('feature_flag.error.message'),

  /// Deprecated, use `feature_flag.error.message` instead.
  ///
  /// Examples:
  /// `Flag 'header-color' expected type 'string' but found type 'number'`
  ///
  /// Stability: development
  @Deprecated('Replaced by `feature_flag.error.message`.')
  featureFlagEvaluationErrorMessage('feature_flag.evaluation.error.message'),

  /// Deprecated, use `feature_flag.result.reason` instead.
  ///
  /// Examples: `static, targeting_match, error, default`
  ///
  /// Stability: development
  @Deprecated('Replaced by `feature_flag.result.reason`.')
  featureFlagEvaluationReason('feature_flag.evaluation.reason'),

  /// The lookup key of the feature flag.
  ///
  /// Examples: `logo-color`
  ///
  /// Stability: release_candidate
  featureFlagKey('feature_flag.key'),

  /// Identifies the feature flag provider.
  ///
  /// Examples: `Flag Manager`
  ///
  /// Stability: release_candidate
  featureFlagProviderName('feature_flag.provider.name'),

  /// The reason code which shows how a feature flag value was determined.
  ///
  /// Examples: `static, targeting_match, error, default`
  ///
  /// Stability: release_candidate
  featureFlagResultReason('feature_flag.result.reason'),

  /// The evaluated value of the feature flag.
  ///
  /// Examples: `#ff0000, true, 3`
  ///
  /// Stability: release_candidate
  featureFlagResultValue('feature_flag.result.value'),

  /// A semantic identifier for an evaluated flag value.
  ///
  /// Examples: `red, true, on`
  ///
  /// Stability: release_candidate
  featureFlagResultVariant('feature_flag.result.variant'),

  /// The identifier of the
  /// [flag set](https://openfeature.dev/specification/glossary/#flag-set) to
  /// which the feature flag belongs.
  ///
  /// Examples: `proj-1, ab98sgs, service1/dev`
  ///
  /// Stability: release_candidate
  featureFlagSetId('feature_flag.set.id'),

  /// Deprecated, use `feature_flag.result.variant` instead.
  ///
  /// Examples: `red, true, on`
  ///
  /// Stability: development
  @Deprecated('Replaced by `feature_flag.result.variant`.')
  featureFlagVariant('feature_flag.variant'),

  /// The version of the ruleset used during the evaluation. This may be any
  /// stable value which uniquely identifies the ruleset.
  ///
  /// Examples: `1, 01ABCDEF`
  ///
  /// Stability: release_candidate
  featureFlagVersion('feature_flag.version');

  @override
  final String key;

  const FeatureFlag(this.key);

  @override
  String toString() => key;
}

/// Values for `feature_flag.evaluation.reason`.
///
/// Stability: development
@Deprecated('Replaced by `feature_flag.result.reason`.')
enum FeatureFlagEvaluationReason implements OTelSemanticValue {
  /// The resolved value is static (no dynamic evaluation).
  ///
  /// Stability: development
  static('static'),

  /// The resolved value fell back to a pre-configured value (no dynamic
  /// evaluation occurred or dynamic evaluation yielded no result).
  ///
  /// Stability: development
  default$('default'),

  /// The resolved value was the result of a dynamic evaluation, such as a
  /// rule or specific user-targeting.
  ///
  /// Stability: development
  targetingMatch('targeting_match'),

  /// The resolved value was the result of pseudorandom assignment.
  ///
  /// Stability: development
  split('split'),

  /// The resolved value was retrieved from cache.
  ///
  /// Stability: development
  cached('cached'),

  /// The resolved value was the result of the flag being disabled in the
  /// management system.
  ///
  /// Stability: development
  disabled('disabled'),

  /// The reason for the resolved value could not be determined.
  ///
  /// Stability: development
  unknown('unknown'),

  /// The resolved value is non-authoritative or possibly out of date
  ///
  /// Stability: development
  stale('stale'),

  /// The resolved value was the result of an error.
  ///
  /// Stability: development
  error('error');

  @override
  final String value;

  const FeatureFlagEvaluationReason(this.value);

  @override
  String toString() => value;
}

/// Values for `feature_flag.result.reason`.
///
/// Stability: release_candidate
enum FeatureFlagResultReason implements OTelSemanticValue {
  /// The resolved value is static (no dynamic evaluation).
  ///
  /// Stability: release_candidate
  static('static'),

  /// The resolved value fell back to a pre-configured value (no dynamic
  /// evaluation occurred or dynamic evaluation yielded no result).
  ///
  /// Stability: release_candidate
  default$('default'),

  /// The resolved value was the result of a dynamic evaluation, such as a
  /// rule or specific user-targeting.
  ///
  /// Stability: release_candidate
  targetingMatch('targeting_match'),

  /// The resolved value was the result of pseudorandom assignment.
  ///
  /// Stability: release_candidate
  split('split'),

  /// The resolved value was retrieved from cache.
  ///
  /// Stability: release_candidate
  cached('cached'),

  /// The resolved value was the result of the flag being disabled in the
  /// management system.
  ///
  /// Stability: release_candidate
  disabled('disabled'),

  /// The reason for the resolved value could not be determined.
  ///
  /// Stability: release_candidate
  unknown('unknown'),

  /// The resolved value is non-authoritative or possibly out of date
  ///
  /// Stability: release_candidate
  stale('stale'),

  /// The resolved value was the result of an error.
  ///
  /// Stability: release_candidate
  error('error');

  @override
  final String value;

  const FeatureFlagResultReason(this.value);

  @override
  String toString() => value;
}
