// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `gcp`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/gcp/)
library;

import '../semantics_base.dart';

/// `gcp.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Gcp implements OTelSemantic {
  /// The container within GCP where the AppHub application is defined.
  ///
  /// Examples: `projects/my-container-project`
  ///
  /// Stability: development
  gcpApphubApplicationContainer('gcp.apphub.application.container'),

  /// The name of the application as configured in AppHub.
  ///
  /// Examples: `my-application`
  ///
  /// Stability: development
  gcpApphubApplicationId('gcp.apphub.application.id'),

  /// The GCP zone or region where the application is defined.
  ///
  /// Examples: `us-central1`
  ///
  /// Stability: development
  gcpApphubApplicationLocation('gcp.apphub.application.location'),

  /// Criticality of a service indicates its importance to the business.
  ///
  /// Stability: development
  gcpApphubServiceCriticalityType('gcp.apphub.service.criticality_type'),

  /// Environment of a service is the stage of a software lifecycle.
  ///
  /// Stability: development
  gcpApphubServiceEnvironmentType('gcp.apphub.service.environment_type'),

  /// The name of the service as configured in AppHub.
  ///
  /// Examples: `my-service`
  ///
  /// Stability: development
  gcpApphubServiceId('gcp.apphub.service.id'),

  /// Criticality of a workload indicates its importance to the business.
  ///
  /// Stability: development
  gcpApphubWorkloadCriticalityType('gcp.apphub.workload.criticality_type'),

  /// Environment of a workload is the stage of a software lifecycle.
  ///
  /// Stability: development
  gcpApphubWorkloadEnvironmentType('gcp.apphub.workload.environment_type'),

  /// The name of the workload as configured in AppHub.
  ///
  /// Examples: `my-workload`
  ///
  /// Stability: development
  gcpApphubWorkloadId('gcp.apphub.workload.id'),

  /// The container within GCP where the AppHub destination application is
  /// defined.
  ///
  /// Examples: `projects/my-container-project`
  ///
  /// Stability: development
  gcpApphubDestinationApplicationContainer(
      'gcp.apphub_destination.application.container'),

  /// The name of the destination application as configured in AppHub.
  ///
  /// Examples: `my-application`
  ///
  /// Stability: development
  gcpApphubDestinationApplicationId('gcp.apphub_destination.application.id'),

  /// The GCP zone or region where the destination application is defined.
  ///
  /// Examples: `us-central1`
  ///
  /// Stability: development
  gcpApphubDestinationApplicationLocation(
      'gcp.apphub_destination.application.location'),

  /// Criticality of a destination workload indicates its importance to the
  /// business as specified in
  /// [AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)
  ///
  /// Stability: development
  gcpApphubDestinationServiceCriticalityType(
      'gcp.apphub_destination.service.criticality_type'),

  /// Software lifecycle stage of a destination service as defined
  /// [AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)
  ///
  /// Stability: development
  gcpApphubDestinationServiceEnvironmentType(
      'gcp.apphub_destination.service.environment_type'),

  /// The name of the destination service as configured in AppHub.
  ///
  /// Examples: `my-service`
  ///
  /// Stability: development
  gcpApphubDestinationServiceId('gcp.apphub_destination.service.id'),

  /// Criticality of a destination workload indicates its importance to the
  /// business as specified in
  /// [AppHub type enum](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type)
  ///
  /// Stability: development
  gcpApphubDestinationWorkloadCriticalityType(
      'gcp.apphub_destination.workload.criticality_type'),

  /// Environment of a destination workload is the stage of a software
  /// lifecycle as provided in the
  /// [AppHub environment type](https://cloud.google.com/app-hub/docs/reference/rest/v1/Attributes#type_1)
  ///
  /// Stability: development
  gcpApphubDestinationWorkloadEnvironmentType(
      'gcp.apphub_destination.workload.environment_type'),

  /// The name of the destination workload as configured in AppHub.
  ///
  /// Examples: `my-workload`
  ///
  /// Stability: development
  gcpApphubDestinationWorkloadId('gcp.apphub_destination.workload.id'),

  /// Identifies the Google Cloud service for which the official client
  /// library is intended.
  ///
  /// Examples: `appengine, run, firestore, alloydb, spanner`
  ///
  /// Stability: development
  gcpClientService('gcp.client.service'),

  /// The name of the Cloud Run
  /// [execution](https://cloud.google.com/run/docs/managing/job-executions)
  /// being run for the Job, as set by the
  /// [`CLOUD_RUN_EXECUTION`](https://cloud.google.com/run/docs/container-contract#jobs-env-vars)
  ///  environment variable.
  ///
  /// Examples: `job-name-xxxx, sample-job-mdw84`
  ///
  /// Stability: development
  gcpCloudRunJobExecution('gcp.cloud_run.job.execution'),

  /// The index for a task within an execution as provided by the
  /// [`CLOUD_RUN_TASK_INDEX`](https://cloud.google.com/run/docs/container-contract#jobs-env-vars)
  ///  environment variable.
  ///
  /// Examples: `0, 1`
  ///
  /// Stability: development
  gcpCloudRunJobTaskIndex('gcp.cloud_run.job.task_index'),

  /// The hostname of a GCE instance. This is the full value of the default
  /// or
  /// [custom hostname](https://cloud.google.com/compute/docs/instances/custom-hostname-vm)
  /// .
  ///
  /// Examples:
  /// `my-host1234.example.com, sample-vm.us-west1-b.c.my-project.internal`
  ///
  /// Stability: development
  gcpGceInstanceHostname('gcp.gce.instance.hostname'),

  /// GCE instance labels, `<key>` being the label name and the value being
  /// the label value.
  ///
  /// Examples: `observability`
  ///
  /// Stability: development
  gcpGceInstanceLabels('gcp.gce.instance.labels'),

  /// The instance name of a GCE instance. This is the value provided by
  /// `host.name`, the visible name of the instance in the Cloud Console UI,
  /// and the prefix for the default hostname of the instance as defined by
  /// the
  /// [default internal DNS name](https://cloud.google.com/compute/docs/internal-dns#instance-fully-qualified-domain-names)
  /// .
  ///
  /// Examples: `instance-1, my-vm-name`
  ///
  /// Stability: development
  gcpGceInstanceName('gcp.gce.instance.name'),

  /// The name of the Instance Group Manager (IGM) that manages this VM, if
  /// any.
  ///
  /// Examples: `web-igm, my-managed-group`
  ///
  /// Stability: development
  gcpGceInstanceGroupManagerName('gcp.gce.instance_group_manager.name'),

  /// The region of a **regional** Instance Group Manager (e.g.,
  /// `us-central1`). Set this **only** when the IGM is regional.
  ///
  /// Examples: `us-central1, europe-west1`
  ///
  /// Stability: development
  gcpGceInstanceGroupManagerRegion('gcp.gce.instance_group_manager.region'),

  /// The zone of a **zonal** Instance Group Manager (e.g., `us-central1-a`
  /// ). Set this **only** when the IGM is zonal.
  ///
  /// Examples: `us-central1-a, europe-west1-b`
  ///
  /// Stability: development
  gcpGceInstanceGroupManagerZone('gcp.gce.instance_group_manager.zone');

  @override
  final String key;

  const Gcp(this.key);

  @override
  String toString() => key;
}

/// Values for `gcp.apphub.service.criticality_type`.
///
/// Stability: development
enum GcpApphubServiceCriticalityType implements OTelSemanticValue {
  /// Mission critical service.
  ///
  /// Stability: development
  missionCritical('MISSION_CRITICAL'),

  /// High impact.
  ///
  /// Stability: development
  high('HIGH'),

  /// Medium impact.
  ///
  /// Stability: development
  medium('MEDIUM'),

  /// Low impact.
  ///
  /// Stability: development
  low('LOW');

  @override
  final String value;

  const GcpApphubServiceCriticalityType(this.value);

  @override
  String toString() => value;
}

/// Values for `gcp.apphub.service.environment_type`.
///
/// Stability: development
enum GcpApphubServiceEnvironmentType implements OTelSemanticValue {
  /// Production environment.
  ///
  /// Stability: development
  production('PRODUCTION'),

  /// Staging environment.
  ///
  /// Stability: development
  staging('STAGING'),

  /// Test environment.
  ///
  /// Stability: development
  test('TEST'),

  /// Development environment.
  ///
  /// Stability: development
  development('DEVELOPMENT');

  @override
  final String value;

  const GcpApphubServiceEnvironmentType(this.value);

  @override
  String toString() => value;
}

/// Values for `gcp.apphub.workload.criticality_type`.
///
/// Stability: development
enum GcpApphubWorkloadCriticalityType implements OTelSemanticValue {
  /// Mission critical service.
  ///
  /// Stability: development
  missionCritical('MISSION_CRITICAL'),

  /// High impact.
  ///
  /// Stability: development
  high('HIGH'),

  /// Medium impact.
  ///
  /// Stability: development
  medium('MEDIUM'),

  /// Low impact.
  ///
  /// Stability: development
  low('LOW');

  @override
  final String value;

  const GcpApphubWorkloadCriticalityType(this.value);

  @override
  String toString() => value;
}

/// Values for `gcp.apphub.workload.environment_type`.
///
/// Stability: development
enum GcpApphubWorkloadEnvironmentType implements OTelSemanticValue {
  /// Production environment.
  ///
  /// Stability: development
  production('PRODUCTION'),

  /// Staging environment.
  ///
  /// Stability: development
  staging('STAGING'),

  /// Test environment.
  ///
  /// Stability: development
  test('TEST'),

  /// Development environment.
  ///
  /// Stability: development
  development('DEVELOPMENT');

  @override
  final String value;

  const GcpApphubWorkloadEnvironmentType(this.value);

  @override
  String toString() => value;
}

/// Values for `gcp.apphub_destination.service.criticality_type`.
///
/// Stability: development
enum GcpApphubDestinationServiceCriticalityType implements OTelSemanticValue {
  /// Mission critical service.
  ///
  /// Stability: development
  missionCritical('MISSION_CRITICAL'),

  /// High impact.
  ///
  /// Stability: development
  high('HIGH'),

  /// Medium impact.
  ///
  /// Stability: development
  medium('MEDIUM'),

  /// Low impact.
  ///
  /// Stability: development
  low('LOW');

  @override
  final String value;

  const GcpApphubDestinationServiceCriticalityType(this.value);

  @override
  String toString() => value;
}

/// Values for `gcp.apphub_destination.service.environment_type`.
///
/// Stability: development
enum GcpApphubDestinationServiceEnvironmentType implements OTelSemanticValue {
  /// Production environment.
  ///
  /// Stability: development
  production('PRODUCTION'),

  /// Staging environment.
  ///
  /// Stability: development
  staging('STAGING'),

  /// Test environment.
  ///
  /// Stability: development
  test('TEST'),

  /// Development environment.
  ///
  /// Stability: development
  development('DEVELOPMENT');

  @override
  final String value;

  const GcpApphubDestinationServiceEnvironmentType(this.value);

  @override
  String toString() => value;
}

/// Values for `gcp.apphub_destination.workload.criticality_type`.
///
/// Stability: development
enum GcpApphubDestinationWorkloadCriticalityType implements OTelSemanticValue {
  /// Mission critical service.
  ///
  /// Stability: development
  missionCritical('MISSION_CRITICAL'),

  /// High impact.
  ///
  /// Stability: development
  high('HIGH'),

  /// Medium impact.
  ///
  /// Stability: development
  medium('MEDIUM'),

  /// Low impact.
  ///
  /// Stability: development
  low('LOW');

  @override
  final String value;

  const GcpApphubDestinationWorkloadCriticalityType(this.value);

  @override
  String toString() => value;
}

/// Values for `gcp.apphub_destination.workload.environment_type`.
///
/// Stability: development
enum GcpApphubDestinationWorkloadEnvironmentType implements OTelSemanticValue {
  /// Production environment.
  ///
  /// Stability: development
  production('PRODUCTION'),

  /// Staging environment.
  ///
  /// Stability: development
  staging('STAGING'),

  /// Test environment.
  ///
  /// Stability: development
  test('TEST'),

  /// Development environment.
  ///
  /// Stability: development
  development('DEVELOPMENT');

  @override
  final String value;

  const GcpApphubDestinationWorkloadEnvironmentType(this.value);

  @override
  String toString() => value;
}
