// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `gen_ai`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/gen-ai/)
library;

import '../semantics_base.dart';

/// `gen_ai.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum GenAi implements OTelSemantic {
  /// Free-form description of the GenAI agent provided by the application.
  ///
  /// Examples: `Helps with math problems, Generates fiction stories`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiAgentDescription('gen_ai.agent.description'),

  /// The unique identifier of the GenAI agent.
  ///
  /// Examples: `asst_5j66UpCpwteGg4YSxUnt7lPY`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiAgentId('gen_ai.agent.id'),

  /// Human-readable name of the GenAI agent provided by the application.
  ///
  /// Examples: `Math Tutor, Fiction Writer`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiAgentName('gen_ai.agent.name'),

  /// The version of the GenAI agent.
  ///
  /// Examples: `1.0.0, 2025-05-01`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiAgentVersion('gen_ai.agent.version'),

  /// Deprecated, use Event API to report completions contents.
  ///
  /// Examples:
  /// `[{'role': 'assistant', 'content': 'The capital of France is Paris.'}]`
  ///
  /// Stability: development
  @Deprecated('Removed, no replacement at this time.')
  genAiCompletion('gen_ai.completion'),

  /// The unique identifier for a conversation (session, thread), used to
  /// store and correlate messages within this conversation.
  ///
  /// Examples: `conv_5j66UpCpwteGg4YSxUnt7lPY`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiConversationId('gen_ai.conversation.id'),

  /// The data source identifier.
  ///
  /// Examples: `H7STPQYOND`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiDataSourceId('gen_ai.data_source.id'),

  /// The number of dimensions the resulting output embeddings should have.
  ///
  /// Examples: `512, 1024`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiEmbeddingsDimensionCount('gen_ai.embeddings.dimension.count'),

  /// A free-form explanation for the assigned score provided by the
  /// evaluator.
  ///
  /// Examples:
  /// `The response is factually accurate but lacks sufficient detail to fully address the question.`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiEvaluationExplanation('gen_ai.evaluation.explanation'),

  /// The name of the evaluation metric used for the GenAI response.
  ///
  /// Examples: `Relevance, IntentResolution`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiEvaluationName('gen_ai.evaluation.name'),

  /// Human readable label for evaluation.
  ///
  /// Examples: `relevant, not_relevant, correct, incorrect, pass, fail`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiEvaluationScoreLabel('gen_ai.evaluation.score.label'),

  /// The evaluation score returned by the evaluator.
  ///
  /// Examples: `4.0`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiEvaluationScoreValue('gen_ai.evaluation.score.value'),

  /// The chat history provided to the model as an input.
  ///
  /// Examples:
  /// `[   {     "role": "user",     "parts": [       {         "type": "text",         "content": "Weather in Paris?"       }     ]   },   {     "role": "assistant",     "parts": [       {         "type": "tool_call",         "id": "call_VSPygqKTWdrhaFErNvMV18Yl",         "name": "get_weather",         "arguments": {           "location": "Paris"         }       }     ]   },   {     "role": "tool",     "parts": [       {         "type": "tool_call_response",         "id": " call_VSPygqKTWdrhaFErNvMV18Yl",         "result": "rainy, 57°F"       }     ]   } ] `
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiInputMessages('gen_ai.input.messages'),

  /// Deprecated, use `gen_ai.output.type`.
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `gen_ai.output.type`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOpenaiRequestResponseFormat('gen_ai.openai.request.response_format'),

  /// Deprecated, use `gen_ai.request.seed`.
  ///
  /// Examples: `100`
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `gen_ai.request.seed`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOpenaiRequestSeed('gen_ai.openai.request.seed'),

  /// Deprecated, use `openai.request.service_tier`.
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `openai.request.service_tier`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOpenaiRequestServiceTier('gen_ai.openai.request.service_tier'),

  /// Deprecated, use `openai.response.service_tier`.
  ///
  /// Examples: `scale, default`
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `openai.response.service_tier`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOpenaiResponseServiceTier('gen_ai.openai.response.service_tier'),

  /// Deprecated, use `openai.response.system_fingerprint`.
  ///
  /// Examples: `fp_44709d6fcb`
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `openai.response.system_fingerprint`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOpenaiResponseSystemFingerprint(
      'gen_ai.openai.response.system_fingerprint'),

  /// The name of the operation being performed.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOperationName('gen_ai.operation.name'),

  /// Messages returned by the model where each message represents a specific
  /// model response (choice, candidate).
  ///
  /// Examples:
  /// `[   {     "role": "assistant",     "parts": [       {         "type": "text",         "content": "The weather in Paris is currently rainy with a temperature of 57°F."       }     ],     "finish_reason": "stop"   } ] `
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOutputMessages('gen_ai.output.messages'),

  /// Represents the content type requested by the client.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiOutputType('gen_ai.output.type'),

  /// Deprecated, use Event API to report prompt contents.
  ///
  /// Examples:
  /// `[{'role': 'user', 'content': 'What is the capital of France?'}]`
  ///
  /// Stability: development
  @Deprecated('Removed, no replacement at this time.')
  genAiPrompt('gen_ai.prompt'),

  /// The name of the prompt that uniquely identifies it.
  ///
  /// Examples: `analyze-code`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiPromptName('gen_ai.prompt.name'),

  /// The Generative AI provider as identified by the client or server
  /// instrumentation.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiProviderName('gen_ai.provider.name'),

  /// The target number of candidate completions to return.
  ///
  /// Examples: `3`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestChoiceCount('gen_ai.request.choice.count'),

  /// The encoding formats requested in an embeddings operation, if
  /// specified.
  ///
  /// Examples: `["base64"], ["float", "binary"]`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestEncodingFormats('gen_ai.request.encoding_formats'),

  /// The frequency penalty setting for the GenAI request.
  ///
  /// Examples: `0.1`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestFrequencyPenalty('gen_ai.request.frequency_penalty'),

  /// The maximum number of tokens the model generates for a request.
  ///
  /// Examples: `100`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestMaxTokens('gen_ai.request.max_tokens'),

  /// The name of the GenAI model a request is being made to.
  ///
  /// Examples: `gpt-4`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestModel('gen_ai.request.model'),

  /// The presence penalty setting for the GenAI request.
  ///
  /// Examples: `0.1`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestPresencePenalty('gen_ai.request.presence_penalty'),

  /// Requests with same seed value more likely to return same result.
  ///
  /// Examples: `100`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestSeed('gen_ai.request.seed'),

  /// List of sequences that the model will use to stop generating further
  /// tokens.
  ///
  /// Examples: `["forest", "lived"]`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestStopSequences('gen_ai.request.stop_sequences'),

  /// Indicates whether the GenAI request was made in streaming mode.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestStream('gen_ai.request.stream'),

  /// The temperature setting for the GenAI request.
  ///
  /// Examples: `0.0`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestTemperature('gen_ai.request.temperature'),

  /// The top_k sampling setting for the GenAI request.
  ///
  /// Examples: `1.0`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestTopK('gen_ai.request.top_k'),

  /// The top_p sampling setting for the GenAI request.
  ///
  /// Examples: `1.0`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRequestTopP('gen_ai.request.top_p'),

  /// Array of reasons the model stopped generating tokens, corresponding to
  /// each generation received.
  ///
  /// Examples: `["stop"], ["stop", "length"]`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiResponseFinishReasons('gen_ai.response.finish_reasons'),

  /// The unique identifier for the completion.
  ///
  /// Examples: `chatcmpl-123`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiResponseId('gen_ai.response.id'),

  /// The name of the model that generated the response.
  ///
  /// Examples: `gpt-4-0613`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiResponseModel('gen_ai.response.model'),

  /// Time to first chunk in a streaming response, measured from request
  /// issuance, in seconds. The value is measured from when the client issues
  /// the generation request to when the first chunk is received in the
  /// response stream.
  ///
  /// Examples: `0.5, 1.2`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiResponseTimeToFirstChunk('gen_ai.response.time_to_first_chunk'),

  /// The documents retrieved.
  ///
  /// Examples:
  /// `[   {     "id": "doc_123",     "score": 0.95   },   {     "id": "doc_456",     "score": 0.87   },   {     "id": "doc_789",     "score": 0.82   } ] `
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRetrievalDocuments('gen_ai.retrieval.documents'),

  /// The query text used for retrieval.
  ///
  /// Examples: `What is the capital of France?, weather in Paris`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiRetrievalQueryText('gen_ai.retrieval.query.text'),

  /// Deprecated, use `gen_ai.provider.name` instead.
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `gen_ai.provider.name`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiSystem('gen_ai.system'),

  /// The system message or instructions provided to the GenAI model
  /// separately from the chat history.
  ///
  /// Examples:
  /// `[   {     "type": "text",     "content": "You are an Agent that greet users, always use greetings tool to respond"   } ] , [   {     "type": "text",     "content": "You are a language translator."   },   {     "type": "text",     "content": "Your mission is to translate text in English to French."   } ] `
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiSystemInstructions('gen_ai.system_instructions'),

  /// The type of token being counted.
  ///
  /// Examples: `input, output`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiTokenType('gen_ai.token.type'),

  /// Parameters passed to the tool call.
  ///
  /// Examples:
  /// `{     "location": "San Francisco?",     "date": "2025-10-01" } `
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiToolCallArguments('gen_ai.tool.call.arguments'),

  /// The tool call identifier.
  ///
  /// Examples: `call_mszuSIzqtI65i1wAUOE8w5H4`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiToolCallId('gen_ai.tool.call.id'),

  /// The result returned by the tool call (if any and if execution was
  /// successful).
  ///
  /// Examples:
  /// `{   "temperature_range": {     "high": 75,     "low": 60   },   "conditions": "sunny" } `
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiToolCallResult('gen_ai.tool.call.result'),

  /// The list of tool definitions available to the GenAI agent or model.
  ///
  /// Examples:
  /// `[   {     "type": "function",     "name": "get_current_weather",     "description": "Get the current weather in a given location",     "parameters": {       "type": "object",       "properties": {         "location": {           "type": "string",           "description": "The city and state, e.g. San Francisco, CA"         },         "unit": {           "type": "string",           "enum": [             "celsius",             "fahrenheit"           ]         }       },       "required": [         "location",         "unit"       ]     }   } ] `
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiToolDefinitions('gen_ai.tool.definitions'),

  /// The tool description.
  ///
  /// Examples: `Multiply two numbers`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiToolDescription('gen_ai.tool.description'),

  /// Name of the tool utilized by the agent.
  ///
  /// Examples: `Flights`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiToolName('gen_ai.tool.name'),

  /// Type of the tool utilized by the agent
  ///
  /// Examples: `function, extension, datastore`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiToolType('gen_ai.tool.type'),

  /// The number of input tokens written to a provider-managed cache.
  ///
  /// Examples: `25`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiUsageCacheCreationInputTokens(
      'gen_ai.usage.cache_creation.input_tokens'),

  /// The number of input tokens served from a provider-managed cache.
  ///
  /// Examples: `50`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiUsageCacheReadInputTokens('gen_ai.usage.cache_read.input_tokens'),

  /// Deprecated, use `gen_ai.usage.output_tokens` instead.
  ///
  /// Examples: `42`
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `gen_ai.usage.output_tokens`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiUsageCompletionTokens('gen_ai.usage.completion_tokens'),

  /// The number of tokens used in the GenAI input (prompt).
  ///
  /// Examples: `100`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiUsageInputTokens('gen_ai.usage.input_tokens'),

  /// The number of tokens used in the GenAI response (completion).
  ///
  /// Examples: `180`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiUsageOutputTokens('gen_ai.usage.output_tokens'),

  /// Deprecated, use `gen_ai.usage.input_tokens` instead.
  ///
  /// Examples: `42`
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `gen_ai.usage.input_tokens`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiUsagePromptTokens('gen_ai.usage.prompt_tokens'),

  /// The number of output tokens used for reasoning (e.g. chain-of-thought,
  /// extended thinking).
  ///
  /// Examples: `50`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiUsageReasoningOutputTokens('gen_ai.usage.reasoning.output_tokens'),

  /// Human-readable name of the GenAI workflow provided by the application.
  ///
  /// Examples: `multi_agent_rag, customer_support_pipeline`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiWorkflowName('gen_ai.workflow.name');

  @override
  final String key;

  const GenAi(this.key);

  @override
  String toString() => key;
}

/// Values for `gen_ai.openai.request.response_format`.
///
/// Stability: development
@Deprecated(
    'Replaced by `gen_ai.output.type`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum GenAiOpenaiRequestResponseFormat implements OTelSemanticValue {
  /// Text response format
  ///
  /// Stability: development
  text('text'),

  /// JSON object response format
  ///
  /// Stability: development
  jsonObject('json_object'),

  /// JSON schema response format
  ///
  /// Stability: development
  jsonSchema('json_schema');

  @override
  final String value;

  const GenAiOpenaiRequestResponseFormat(this.value);

  @override
  String toString() => value;
}

/// Values for `gen_ai.openai.request.service_tier`.
///
/// Stability: development
@Deprecated(
    'Replaced by `openai.request.service_tier`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum GenAiOpenaiRequestServiceTier implements OTelSemanticValue {
  /// The system will utilize scale tier credits until they are exhausted.
  ///
  /// Stability: development
  auto('auto'),

  /// The system will utilize the default scale tier.
  ///
  /// Stability: development
  default$('default');

  @override
  final String value;

  const GenAiOpenaiRequestServiceTier(this.value);

  @override
  String toString() => value;
}

/// Values for `gen_ai.operation.name`.
///
/// Stability: development
@Deprecated(
    'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum GenAiOperationName implements OTelSemanticValue {
  /// Chat completion operation such as
  /// [OpenAI Chat API](https://platform.openai.com/docs/api-reference/chat)
  ///
  /// Stability: development
  chat('chat'),

  /// Multimodal content generation operation such as
  /// [Gemini Generate Content](https://ai.google.dev/api/generate-content)
  ///
  /// Stability: development
  generateContent('generate_content'),

  /// Text completions operation such as
  /// [OpenAI Completions API (Legacy)](https://platform.openai.com/docs/api-reference/completions)
  ///
  /// Stability: development
  textCompletion('text_completion'),

  /// Embeddings operation such as
  /// [OpenAI Create embeddings API](https://platform.openai.com/docs/api-reference/embeddings/create)
  ///
  /// Stability: development
  embeddings('embeddings'),

  /// Retrieval operation such as
  /// [OpenAI Search Vector Store API](https://platform.openai.com/docs/api-reference/vector-stores/search)
  ///
  /// Stability: development
  retrieval('retrieval'),

  /// Create GenAI agent
  ///
  /// Stability: development
  createAgent('create_agent'),

  /// Invoke GenAI agent
  ///
  /// Stability: development
  invokeAgent('invoke_agent'),

  /// Execute a tool
  ///
  /// Stability: development
  executeTool('execute_tool'),

  /// Invoke GenAI workflow
  ///
  /// Stability: development
  invokeWorkflow('invoke_workflow');

  @override
  final String value;

  const GenAiOperationName(this.value);

  @override
  String toString() => value;
}

/// Values for `gen_ai.output.type`.
///
/// Stability: development
@Deprecated(
    'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum GenAiOutputType implements OTelSemanticValue {
  /// Plain text
  ///
  /// Stability: development
  text('text'),

  /// JSON object with known or unknown schema
  ///
  /// Stability: development
  json('json'),

  /// Image
  ///
  /// Stability: development
  image('image'),

  /// Speech
  ///
  /// Stability: development
  speech('speech');

  @override
  final String value;

  const GenAiOutputType(this.value);

  @override
  String toString() => value;
}

/// Values for `gen_ai.provider.name`.
///
/// Stability: development
@Deprecated(
    'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum GenAiProviderName implements OTelSemanticValue {
  /// [OpenAI](https://openai.com/)
  ///
  /// Stability: development
  openai('openai'),

  /// Any Google generative AI endpoint
  ///
  /// Stability: development
  gcpGenAi('gcp.gen_ai'),

  /// [Vertex AI](https://cloud.google.com/vertex-ai)
  ///
  /// Stability: development
  gcpVertexAi('gcp.vertex_ai'),

  /// [Gemini](https://cloud.google.com/products/gemini)
  ///
  /// Stability: development
  gcpGemini('gcp.gemini'),

  /// [Anthropic](https://www.anthropic.com/)
  ///
  /// Stability: development
  anthropic('anthropic'),

  /// [Cohere](https://cohere.com/)
  ///
  /// Stability: development
  cohere('cohere'),

  /// Azure AI Inference
  ///
  /// Stability: development
  azureAiInference('azure.ai.inference'),

  ///
  /// [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/overview)
  ///
  /// Stability: development
  azureAiOpenai('azure.ai.openai'),

  /// [IBM Watsonx AI](https://www.ibm.com/products/watsonx-ai)
  ///
  /// Stability: development
  ibmWatsonxAi('ibm.watsonx.ai'),

  /// [AWS Bedrock](https://aws.amazon.com/bedrock)
  ///
  /// Stability: development
  awsBedrock('aws.bedrock'),

  /// [Perplexity](https://www.perplexity.ai/)
  ///
  /// Stability: development
  perplexity('perplexity'),

  /// [xAI](https://x.ai/)
  ///
  /// Stability: development
  xAi('x_ai'),

  /// [DeepSeek](https://www.deepseek.com/)
  ///
  /// Stability: development
  deepseek('deepseek'),

  /// [Groq](https://groq.com/)
  ///
  /// Stability: development
  groq('groq'),

  /// [Mistral AI](https://mistral.ai/)
  ///
  /// Stability: development
  mistralAi('mistral_ai');

  @override
  final String value;

  const GenAiProviderName(this.value);

  @override
  String toString() => value;
}

/// Values for `gen_ai.system`.
///
/// Stability: development
@Deprecated(
    'Replaced by `gen_ai.provider.name`, which has moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum GenAiSystem implements OTelSemanticValue {
  /// OpenAI
  ///
  /// Stability: development
  openai('openai'),

  /// Any Google generative AI endpoint
  ///
  /// Stability: development
  gcpGenAi('gcp.gen_ai'),

  /// Vertex AI
  ///
  /// Stability: development
  gcpVertexAi('gcp.vertex_ai'),

  /// Gemini
  ///
  /// Stability: development
  gcpGemini('gcp.gemini'),

  /// Vertex AI
  ///
  /// Stability: development
  @Deprecated('Replaced by `gcp.vertex_ai`.')
  vertexAi('vertex_ai'),

  /// Gemini
  ///
  /// Stability: development
  @Deprecated('Replaced by `gcp.gemini`.')
  gemini('gemini'),

  /// Anthropic
  ///
  /// Stability: development
  anthropic('anthropic'),

  /// Cohere
  ///
  /// Stability: development
  cohere('cohere'),

  /// Azure AI Inference
  ///
  /// Stability: development
  @Deprecated('Replaced by `azure.ai.inference`.')
  azAiInference('az.ai.inference'),

  /// Azure OpenAI
  ///
  /// Stability: development
  @Deprecated('Replaced by `azure.ai.openai`.')
  azAiOpenai('az.ai.openai'),

  /// Azure AI Inference
  ///
  /// Stability: development
  azureAiInference('azure.ai.inference'),

  /// Azure OpenAI
  ///
  /// Stability: development
  azureAiOpenai('azure.ai.openai'),

  /// IBM Watsonx AI
  ///
  /// Stability: development
  ibmWatsonxAi('ibm.watsonx.ai'),

  /// AWS Bedrock
  ///
  /// Stability: development
  awsBedrock('aws.bedrock'),

  /// Perplexity
  ///
  /// Stability: development
  perplexity('perplexity'),

  /// xAI
  ///
  /// Stability: development
  xai('xai'),

  /// DeepSeek
  ///
  /// Stability: development
  deepseek('deepseek'),

  /// Groq
  ///
  /// Stability: development
  groq('groq'),

  /// Mistral AI
  ///
  /// Stability: development
  mistralAi('mistral_ai');

  @override
  final String value;

  const GenAiSystem(this.value);

  @override
  String toString() => value;
}

/// Values for `gen_ai.token.type`.
///
/// Stability: development
@Deprecated(
    'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum GenAiTokenType implements OTelSemanticValue {
  /// Input tokens (prompt, input, etc.)
  ///
  /// Stability: development
  input('input'),

  /// Output tokens (completion, response, etc.)
  ///
  /// Stability: development
  @Deprecated('Replaced by `output`.')
  completion('output'),

  /// Output tokens (completion, response, etc.)
  ///
  /// Stability: development
  output('output');

  @override
  final String value;

  const GenAiTokenType(this.value);

  @override
  String toString() => value;
}
