// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `geo`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/geo/)
library;

import '../semantics_base.dart';

/// `geo.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Geo implements OTelSemantic {
  /// Two-letter code representing continent’s name.
  ///
  /// Stability: development
  geoContinentCode('geo.continent.code'),

  /// Two-letter ISO Country Code (
  /// [ISO 3166-1 alpha2](https://wikipedia.org/wiki/ISO_3166-1#Codes)).
  ///
  /// Examples: `CA`
  ///
  /// Stability: development
  geoCountryIsoCode('geo.country.iso_code'),

  /// Locality name. Represents the name of a city, town, village, or similar
  /// populated place.
  ///
  /// Examples: `Montreal, Berlin`
  ///
  /// Stability: development
  geoLocalityName('geo.locality.name'),

  /// Latitude of the geo location in
  /// [WGS84](https://wikipedia.org/wiki/World_Geodetic_System#WGS84).
  ///
  /// Examples: `45.505918`
  ///
  /// Stability: development
  geoLocationLat('geo.location.lat'),

  /// Longitude of the geo location in
  /// [WGS84](https://wikipedia.org/wiki/World_Geodetic_System#WGS84).
  ///
  /// Examples: `-73.61483`
  ///
  /// Stability: development
  geoLocationLon('geo.location.lon'),

  /// Postal code associated with the location. Values appropriate for this
  /// field may also be known as a postcode or ZIP code and will vary widely
  /// from country to country.
  ///
  /// Examples: `94040`
  ///
  /// Stability: development
  geoPostalCode('geo.postal_code'),

  /// Region ISO code ([ISO 3166-2](https://wikipedia.org/wiki/ISO_3166-2)).
  ///
  /// Examples: `CA-QC`
  ///
  /// Stability: development
  geoRegionIsoCode('geo.region.iso_code');

  @override
  final String key;

  const Geo(this.key);

  @override
  String toString() => key;
}

/// Values for `geo.continent.code`.
///
/// Stability: development
enum GeoContinentCode implements OTelSemanticValue {
  /// Africa
  ///
  /// Stability: development
  af('AF'),

  /// Antarctica
  ///
  /// Stability: development
  an('AN'),

  /// Asia
  ///
  /// Stability: development
  as('AS'),

  /// Europe
  ///
  /// Stability: development
  eu('EU'),

  /// North America
  ///
  /// Stability: development
  na('NA'),

  /// Oceania
  ///
  /// Stability: development
  oc('OC'),

  /// South America
  ///
  /// Stability: development
  sa('SA');

  @override
  final String value;

  const GeoContinentCode(this.value);

  @override
  String toString() => value;
}
