// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `go`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/go/)
library;

import '../semantics_base.dart';

/// `go.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Go implements OTelSemantic {
  /// The detailed state of the CPU.
  ///
  /// Examples: `gc/pause, gc/mark/assist`
  ///
  /// Stability: development
  goCpuDetailedState('go.cpu.detailed_state'),

  /// The state of the CPU.
  ///
  /// Examples: `user, gc`
  ///
  /// Stability: development
  goCpuState('go.cpu.state'),

  /// The detailed type of memory.
  ///
  /// Examples: `heap/objects, heap/free`
  ///
  /// Stability: development
  goMemoryDetailedType('go.memory.detailed_type'),

  /// The type of memory.
  ///
  /// Examples: `other, stack`
  ///
  /// Stability: development
  goMemoryType('go.memory.type');

  @override
  final String key;

  const Go(this.key);

  @override
  String toString() => key;
}

/// Values for `go.cpu.state`.
///
/// Stability: development
enum GoCpuState implements OTelSemanticValue {
  /// CPU time spent running user Go code.
  ///
  /// Stability: development
  user('user'),

  /// CPU time spent performing garbage collection tasks.
  ///
  /// Stability: development
  gc('gc'),

  /// CPU time spent returning unused memory to the underlying platform.
  ///
  /// Stability: development
  scavenge('scavenge'),

  /// Available CPU time not spent executing any Go or Go runtime code.
  ///
  /// Stability: development
  idle('idle');

  @override
  final String value;

  const GoCpuState(this.value);

  @override
  String toString() => value;
}

/// Values for `go.memory.type`.
///
/// Stability: development
enum GoMemoryType implements OTelSemanticValue {
  /// Memory allocated from the heap that is reserved for stack space,
  /// whether or not it is currently in-use.
  ///
  /// Stability: development
  stack('stack'),

  /// Memory used by the Go runtime, excluding other categories of memory
  /// usage described in this enumeration.
  ///
  /// Stability: development
  other('other');

  @override
  final String value;

  const GoMemoryType(this.value);

  @override
  String toString() => value;
}
