// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `host`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/host/)
library;

import '../semantics_base.dart';

/// `host.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Host implements OTelSemantic {
  /// The CPU architecture the host system is running on.
  ///
  /// Stability: development
  hostArch('host.arch'),

  /// The amount of level 2 memory cache available to the processor (in
  /// Bytes).
  ///
  /// Examples: `12288000`
  ///
  /// Stability: development
  hostCpuCacheL2Size('host.cpu.cache.l2.size'),

  /// Family or generation of the CPU.
  ///
  /// Examples: `6, PA-RISC 1.1e`
  ///
  /// Stability: development
  hostCpuFamily('host.cpu.family'),

  /// Model identifier. It provides more granular information about the CPU,
  /// distinguishing it from other CPUs within the same family.
  ///
  /// Examples: `6, 9000/778/B180L`
  ///
  /// Stability: development
  hostCpuModelId('host.cpu.model.id'),

  /// Model designation of the processor.
  ///
  /// Examples: `11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz`
  ///
  /// Stability: development
  hostCpuModelName('host.cpu.model.name'),

  /// Stepping or core revisions.
  ///
  /// Examples: `1, r1p1`
  ///
  /// Stability: development
  hostCpuStepping('host.cpu.stepping'),

  /// Processor manufacturer identifier. A maximum 12-character string.
  ///
  /// Examples: `GenuineIntel`
  ///
  /// Stability: development
  hostCpuVendorId('host.cpu.vendor.id'),

  /// Unique host ID. For Cloud, this must be the instance_id assigned by the
  /// cloud provider. For non-containerized systems, this should be the
  /// `machine-id`. See the table below for the sources to use to determine
  /// the `machine-id` based on operating system.
  ///
  /// Examples: `fdbf79e8af94cb7f9e8df36789187052`
  ///
  /// Stability: development
  hostId('host.id'),

  /// VM image ID or host OS image ID. For Cloud, this value is from the
  /// provider.
  ///
  /// Examples: `ami-07b06b442921831e5`
  ///
  /// Stability: development
  hostImageId('host.image.id'),

  /// Name of the VM image or OS install the host was instantiated from.
  ///
  /// Examples: `infra-ami-eks-worker-node-7d4ec78312, CentOS-8-x86_64-1905`
  ///
  /// Stability: development
  hostImageName('host.image.name'),

  /// The version string of the VM image or host OS as defined in
  /// [Version Attributes](/docs/resource/README.md#version-attributes).
  ///
  /// Examples: `0.1`
  ///
  /// Stability: development
  hostImageVersion('host.image.version'),

  /// Available IP addresses of the host, excluding loopback interfaces.
  ///
  /// Examples: `["192.168.1.140", "fe80::abc2:4a28:737a:609e"]`
  ///
  /// Stability: development
  hostIp('host.ip'),

  /// Available MAC addresses of the host, excluding loopback interfaces.
  ///
  /// Examples: `["AC-DE-48-23-45-67", "AC-DE-48-23-45-67-01-9F"]`
  ///
  /// Stability: development
  hostMac('host.mac'),

  /// Name of the host. On Unix systems, it may contain what the hostname
  /// command returns, or the fully qualified hostname, or another name
  /// specified by the user.
  ///
  /// Examples: `opentelemetry-test`
  ///
  /// Stability: development
  hostName('host.name'),

  /// Type of host. For Cloud, this must be the machine type.
  ///
  /// Examples: `n1-standard-1`
  ///
  /// Stability: development
  hostType('host.type');

  @override
  final String key;

  const Host(this.key);

  @override
  String toString() => key;
}

/// Values for `host.arch`.
///
/// Stability: development
enum HostArch implements OTelSemanticValue {
  /// AMD64
  ///
  /// Stability: development
  amd64('amd64'),

  /// ARM32
  ///
  /// Stability: development
  arm32('arm32'),

  /// ARM64
  ///
  /// Stability: development
  arm64('arm64'),

  /// Itanium
  ///
  /// Stability: development
  ia64('ia64'),

  /// 32-bit PowerPC
  ///
  /// Stability: development
  ppc32('ppc32'),

  /// 64-bit PowerPC
  ///
  /// Stability: development
  ppc64('ppc64'),

  /// IBM z/Architecture
  ///
  /// Stability: development
  s390x('s390x'),

  /// 32-bit x86
  ///
  /// Stability: development
  x86('x86');

  @override
  final String value;

  const HostArch(this.value);

  @override
  String toString() => value;
}
