// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `hw`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/hw/)
library;

import '../semantics_base.dart';

/// `hw.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Hw implements OTelSemantic {
  /// Design capacity in Watts-hours or Ampere-hours
  ///
  /// Examples: `9.3Ah, 50Wh`
  ///
  /// Stability: development
  hwBatteryCapacity('hw.battery.capacity'),

  /// Battery
  /// [chemistry](https://schemas.dmtf.org/wbem/cim-html/2.31.0/CIM_Battery.html)
  /// , e.g. Lithium-Ion, Nickel-Cadmium, etc.
  ///
  /// Examples: `Li-ion, NiMH`
  ///
  /// Stability: development
  hwBatteryChemistry('hw.battery.chemistry'),

  /// The current state of the battery
  ///
  /// Stability: development
  hwBatteryState('hw.battery.state'),

  /// BIOS version of the hardware component
  ///
  /// Examples: `1.2.3`
  ///
  /// Stability: development
  hwBiosVersion('hw.bios_version'),

  /// Driver version for the hardware component
  ///
  /// Examples: `10.2.1-3`
  ///
  /// Stability: development
  hwDriverVersion('hw.driver_version'),

  /// Type of the enclosure (useful for modular systems)
  ///
  /// Examples: `Computer, Storage, Switch`
  ///
  /// Stability: development
  hwEnclosureType('hw.enclosure.type'),

  /// Firmware version of the hardware component
  ///
  /// Examples: `2.0.1`
  ///
  /// Stability: development
  hwFirmwareVersion('hw.firmware_version'),

  /// Type of task the GPU is performing
  ///
  /// Stability: development
  hwGpuTask('hw.gpu.task'),

  /// An identifier for the hardware component, unique within the monitored
  /// host
  ///
  /// Examples: `win32battery_battery_testsysa33_1`
  ///
  /// Stability: development
  hwId('hw.id'),

  /// Type of limit for hardware components
  ///
  /// Stability: development
  hwLimitType('hw.limit_type'),

  /// RAID Level of the logical disk
  ///
  /// Examples: `RAID0+1, RAID5, RAID10`
  ///
  /// Stability: development
  hwLogicalDiskRaidLevel('hw.logical_disk.raid_level'),

  /// State of the logical disk space usage
  ///
  /// Stability: development
  hwLogicalDiskState('hw.logical_disk.state'),

  /// Type of the memory module
  ///
  /// Examples: `DDR4, DDR5, LPDDR5`
  ///
  /// Stability: development
  hwMemoryType('hw.memory.type'),

  /// Descriptive model name of the hardware component
  ///
  /// Examples:
  /// `PERC H740P, Intel(R) Core(TM) i7-10700K, Dell XPS 15 Battery`
  ///
  /// Stability: development
  hwModel('hw.model'),

  /// An easily-recognizable name for the hardware component
  ///
  /// Examples: `eth0`
  ///
  /// Stability: development
  hwName('hw.name'),

  /// Logical addresses of the adapter (e.g. IP address, or WWPN)
  ///
  /// Examples: `["172.16.8.21", "57.11.193.42"]`
  ///
  /// Stability: development
  hwNetworkLogicalAddresses('hw.network.logical_addresses'),

  /// Physical address of the adapter (e.g. MAC address, or WWNN)
  ///
  /// Examples: `00-90-F5-E9-7B-36`
  ///
  /// Stability: development
  hwNetworkPhysicalAddress('hw.network.physical_address'),

  /// Unique identifier of the parent component (typically the `hw.id`
  /// attribute of the enclosure, or disk controller)
  ///
  /// Examples: `dellStorage_perc_0`
  ///
  /// Stability: development
  hwParent('hw.parent'),

  /// [S.M.A.R.T.](https://wikipedia.org/wiki/S.M.A.R.T.) (Self-Monitoring,
  /// Analysis, and Reporting Technology) attribute of the physical disk
  ///
  /// Examples: `Spin Retry Count, Seek Error Rate, Raw Read Error Rate`
  ///
  /// Stability: development
  hwPhysicalDiskSmartAttribute('hw.physical_disk.smart_attribute'),

  /// State of the physical disk endurance utilization
  ///
  /// Stability: development
  hwPhysicalDiskState('hw.physical_disk.state'),

  /// Type of the physical disk
  ///
  /// Examples: `HDD, SSD, 10K`
  ///
  /// Stability: development
  hwPhysicalDiskType('hw.physical_disk.type'),

  /// Location of the sensor
  ///
  /// Examples:
  /// `cpu0, ps1, INLET, CPU0_DIE, AMBIENT, MOTHERBOARD, PS0 V3_3, MAIN_12V, CPU_VCORE`
  ///
  /// Stability: development
  hwSensorLocation('hw.sensor_location'),

  /// Serial number of the hardware component
  ///
  /// Examples: `CNFCP0123456789`
  ///
  /// Stability: development
  hwSerialNumber('hw.serial_number'),

  /// The current state of the component
  ///
  /// Stability: development
  hwState('hw.state'),

  /// Type of tape drive operation
  ///
  /// Stability: development
  hwTapeDriveOperationType('hw.tape_drive.operation_type'),

  /// Type of the component
  ///
  /// Stability: development
  hwType('hw.type'),

  /// Vendor name of the hardware component
  ///
  /// Examples: `Dell, HP, Intel, AMD, LSI, Lenovo`
  ///
  /// Stability: development
  hwVendor('hw.vendor');

  @override
  final String key;

  const Hw(this.key);

  @override
  String toString() => key;
}

/// Values for `hw.battery.state`.
///
/// Stability: development
enum HwBatteryState implements OTelSemanticValue {
  /// Charging
  ///
  /// Stability: development
  charging('charging'),

  /// Discharging
  ///
  /// Stability: development
  discharging('discharging');

  @override
  final String value;

  const HwBatteryState(this.value);

  @override
  String toString() => value;
}

/// Values for `hw.gpu.task`.
///
/// Stability: development
enum HwGpuTask implements OTelSemanticValue {
  /// Decoder
  ///
  /// Stability: development
  decoder('decoder'),

  /// Encoder
  ///
  /// Stability: development
  encoder('encoder'),

  /// General
  ///
  /// Stability: development
  general('general');

  @override
  final String value;

  const HwGpuTask(this.value);

  @override
  String toString() => value;
}

/// Values for `hw.limit_type`.
///
/// Stability: development
enum HwLimitType implements OTelSemanticValue {
  /// Critical
  ///
  /// Stability: development
  critical('critical'),

  /// Degraded
  ///
  /// Stability: development
  degraded('degraded'),

  /// High Critical
  ///
  /// Stability: development
  highCritical('high.critical'),

  /// High Degraded
  ///
  /// Stability: development
  highDegraded('high.degraded'),

  /// Low Critical
  ///
  /// Stability: development
  lowCritical('low.critical'),

  /// Low Degraded
  ///
  /// Stability: development
  lowDegraded('low.degraded'),

  /// Maximum
  ///
  /// Stability: development
  max('max'),

  /// Throttled
  ///
  /// Stability: development
  throttled('throttled'),

  /// Turbo
  ///
  /// Stability: development
  turbo('turbo');

  @override
  final String value;

  const HwLimitType(this.value);

  @override
  String toString() => value;
}

/// Values for `hw.logical_disk.state`.
///
/// Stability: development
enum HwLogicalDiskState implements OTelSemanticValue {
  /// Used
  ///
  /// Stability: development
  used('used'),

  /// Free
  ///
  /// Stability: development
  free('free');

  @override
  final String value;

  const HwLogicalDiskState(this.value);

  @override
  String toString() => value;
}

/// Values for `hw.physical_disk.state`.
///
/// Stability: development
enum HwPhysicalDiskState implements OTelSemanticValue {
  /// Remaining
  ///
  /// Stability: development
  remaining('remaining');

  @override
  final String value;

  const HwPhysicalDiskState(this.value);

  @override
  String toString() => value;
}

/// Values for `hw.state`.
///
/// Stability: development
enum HwState implements OTelSemanticValue {
  /// Degraded
  ///
  /// Stability: development
  degraded('degraded'),

  /// Failed
  ///
  /// Stability: development
  failed('failed'),

  /// Needs Cleaning
  ///
  /// Stability: development
  needsCleaning('needs_cleaning'),

  /// OK
  ///
  /// Stability: development
  ok('ok'),

  /// Predicted Failure
  ///
  /// Stability: development
  predictedFailure('predicted_failure');

  @override
  final String value;

  const HwState(this.value);

  @override
  String toString() => value;
}

/// Values for `hw.tape_drive.operation_type`.
///
/// Stability: development
enum HwTapeDriveOperationType implements OTelSemanticValue {
  /// Mount
  ///
  /// Stability: development
  mount('mount'),

  /// Unmount
  ///
  /// Stability: development
  unmount('unmount'),

  /// Clean
  ///
  /// Stability: development
  clean('clean');

  @override
  final String value;

  const HwTapeDriveOperationType(this.value);

  @override
  String toString() => value;
}

/// Values for `hw.type`.
///
/// Stability: development
enum HwType implements OTelSemanticValue {
  /// Battery
  ///
  /// Stability: development
  battery('battery'),

  /// CPU
  ///
  /// Stability: development
  cpu('cpu'),

  /// Disk controller
  ///
  /// Stability: development
  diskController('disk_controller'),

  /// Enclosure
  ///
  /// Stability: development
  enclosure('enclosure'),

  /// Fan
  ///
  /// Stability: development
  fan('fan'),

  /// GPU
  ///
  /// Stability: development
  gpu('gpu'),

  /// Logical disk
  ///
  /// Stability: development
  logicalDisk('logical_disk'),

  /// Memory
  ///
  /// Stability: development
  memory('memory'),

  /// Network
  ///
  /// Stability: development
  network('network'),

  /// Physical disk
  ///
  /// Stability: development
  physicalDisk('physical_disk'),

  /// Power supply
  ///
  /// Stability: development
  powerSupply('power_supply'),

  /// Tape drive
  ///
  /// Stability: development
  tapeDrive('tape_drive'),

  /// Temperature
  ///
  /// Stability: development
  temperature('temperature'),

  /// Voltage
  ///
  /// Stability: development
  voltage('voltage');

  @override
  final String value;

  const HwType(this.value);

  @override
  String toString() => value;
}
