// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `ios`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/ios/)
library;

import '../semantics_base.dart';

/// `ios.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Ios implements OTelSemantic {
  /// This attribute represents the state of the application.
  ///
  /// Stability: development
  iosAppState('ios.app.state'),

  /// Deprecated. Use the `ios.app.state` attribute.
  ///
  /// Stability: development
  @Deprecated('Replaced by `ios.app.state`.')
  iosState('ios.state');

  @override
  final String key;

  const Ios(this.key);

  @override
  String toString() => key;
}

/// Values for `ios.app.state`.
///
/// Stability: development
enum IosAppState implements OTelSemanticValue {
  /// The app has become `active`. Associated with UIKit notification
  /// `applicationDidBecomeActive`.
  ///
  /// Stability: development
  active('active'),

  /// The app is now `inactive`. Associated with UIKit notification
  /// `applicationWillResignActive`.
  ///
  /// Stability: development
  inactive('inactive'),

  /// The app is now in the background. This value is associated with UIKit
  /// notification `applicationDidEnterBackground`.
  ///
  /// Stability: development
  background('background'),

  /// The app is now in the foreground. This value is associated with UIKit
  /// notification `applicationWillEnterForeground`.
  ///
  /// Stability: development
  foreground('foreground'),

  /// The app is about to terminate. Associated with UIKit notification
  /// `applicationWillTerminate`.
  ///
  /// Stability: development
  terminate('terminate');

  @override
  final String value;

  const IosAppState(this.value);

  @override
  String toString() => value;
}

/// Values for `ios.state`.
///
/// Stability: development
@Deprecated('Replaced by `ios.app.state`.')
enum IosState implements OTelSemanticValue {
  /// The app has become `active`. Associated with UIKit notification
  /// `applicationDidBecomeActive`.
  ///
  /// Stability: development
  active('active'),

  /// The app is now `inactive`. Associated with UIKit notification
  /// `applicationWillResignActive`.
  ///
  /// Stability: development
  inactive('inactive'),

  /// The app is now in the background. This value is associated with UIKit
  /// notification `applicationDidEnterBackground`.
  ///
  /// Stability: development
  background('background'),

  /// The app is now in the foreground. This value is associated with UIKit
  /// notification `applicationWillEnterForeground`.
  ///
  /// Stability: development
  foreground('foreground'),

  /// The app is about to terminate. Associated with UIKit notification
  /// `applicationWillTerminate`.
  ///
  /// Stability: development
  terminate('terminate');

  @override
  final String value;

  const IosState(this.value);

  @override
  String toString() => value;
}
