// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `jsonrpc`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/jsonrpc/)
library;

import '../semantics_base.dart';

/// `jsonrpc.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Jsonrpc implements OTelSemantic {
  /// Protocol version, as specified in the `jsonrpc` property of the request
  /// and its corresponding response.
  ///
  /// Examples: `2.0, 1.0`
  ///
  /// Stability: development
  jsonrpcProtocolVersion('jsonrpc.protocol.version'),

  /// A string representation of the `id` property of the request and its
  /// corresponding response.
  ///
  /// Examples: `10, request-7`
  ///
  /// Stability: development
  jsonrpcRequestId('jsonrpc.request.id');

  @override
  final String key;

  const Jsonrpc(this.key);

  @override
  String toString() => key;
}
