// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `jvm`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/jvm/)
library;

import '../semantics_base.dart';

/// `jvm.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Jvm implements OTelSemantic {
  /// Name of the buffer pool.
  ///
  /// Examples: `mapped, direct`
  ///
  /// Stability: development
  jvmBufferPoolName('jvm.buffer.pool.name'),

  /// Name of the garbage collector action.
  ///
  /// Examples: `end of minor GC, end of major GC`
  jvmGcAction('jvm.gc.action'),

  /// Name of the garbage collector cause.
  ///
  /// Examples: `System.gc(), Allocation Failure`
  ///
  /// Stability: development
  jvmGcCause('jvm.gc.cause'),

  /// Name of the garbage collector.
  ///
  /// Examples: `G1 Young Generation, G1 Old Generation`
  jvmGcName('jvm.gc.name'),

  /// Name of the memory pool.
  ///
  /// Examples: `G1 Old Gen, G1 Eden space, G1 Survivor Space`
  jvmMemoryPoolName('jvm.memory.pool.name'),

  /// The type of memory.
  ///
  /// Examples: `heap, non_heap`
  jvmMemoryType('jvm.memory.type'),

  /// Whether the thread is daemon or not.
  jvmThreadDaemon('jvm.thread.daemon'),

  /// State of the thread.
  ///
  /// Examples: `runnable, blocked`
  jvmThreadState('jvm.thread.state');

  @override
  final String key;

  const Jvm(this.key);

  @override
  String toString() => key;
}

/// Values for `jvm.memory.type`.
enum JvmMemoryType implements OTelSemanticValue {
  /// Heap memory.
  heap('heap'),

  /// Non-heap memory
  nonHeap('non_heap');

  @override
  final String value;

  const JvmMemoryType(this.value);

  @override
  String toString() => value;
}

/// Values for `jvm.thread.state`.
enum JvmThreadState implements OTelSemanticValue {
  /// A thread that has not yet started is in this state.
  new$('new'),

  /// A thread executing in the Java virtual machine is in this state.
  runnable('runnable'),

  /// A thread that is blocked waiting for a monitor lock is in this state.
  blocked('blocked'),

  /// A thread that is waiting indefinitely for another thread to perform a
  /// particular action is in this state.
  waiting('waiting'),

  /// A thread that is waiting for another thread to perform an action for up
  /// to a specified waiting time is in this state.
  timedWaiting('timed_waiting'),

  /// A thread that has exited is in this state.
  terminated('terminated');

  @override
  final String value;

  const JvmThreadState(this.value);

  @override
  String toString() => value;
}
