// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `k8s`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/k8s/)
library;

import '../semantics_base.dart';

/// `k8s.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum K8s implements OTelSemantic {
  /// The name of the cluster.
  ///
  /// Examples: `opentelemetry-cluster`
  k8sClusterName('k8s.cluster.name'),

  /// A pseudo-ID for the cluster, set to the UID of the `kube-system`
  /// namespace.
  ///
  /// Examples: `218fc5a9-a5f1-4b54-aa05-46717d0ab26d`
  k8sClusterUid('k8s.cluster.uid'),

  /// The type of file system component for ephemeral storage.
  ///
  /// Examples: `rootfs, logs`
  ///
  /// Stability: development
  k8sContainerEphemeralStorageFsType('k8s.container.ephemeral_storage.fs_type'),

  /// The name of the Container from Pod specification, must be unique within
  /// a Pod. Container runtime usually uses different globally unique name (
  /// `container.name`).
  ///
  /// Examples: `redis`
  k8sContainerName('k8s.container.name'),

  /// Number of times the container was restarted. This attribute can be used
  /// to identify a particular container (running or stopped) within a
  /// container spec.
  k8sContainerRestartCount('k8s.container.restart_count'),

  /// Last terminated reason of the Container.
  ///
  /// Examples: `Evicted, Error`
  ///
  /// Stability: development
  k8sContainerStatusLastTerminatedReason(
      'k8s.container.status.last_terminated_reason'),

  /// The reason for the container state. Corresponds to the `reason` field
  /// of the:
  /// [K8s ContainerStateWaiting](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#containerstatewaiting-v1-core)
  ///  or
  /// [K8s ContainerStateTerminated](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#containerstateterminated-v1-core)
  ///
  /// Examples:
  /// `ContainerCreating, CrashLoopBackOff, CreateContainerConfigError, ErrImagePull, ImagePullBackOff, OOMKilled, Completed, Error, ContainerCannotRun`
  ///
  /// Stability: development
  k8sContainerStatusReason('k8s.container.status.reason'),

  /// The state of the container.
  /// [K8s ContainerState](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#containerstate-v1-core)
  ///
  /// Examples: `terminated, running, waiting`
  ///
  /// Stability: development
  k8sContainerStatusState('k8s.container.status.state'),

  /// The cronjob annotation placed on the CronJob, the `<key>` being the
  /// annotation name, the value being the annotation value.
  ///
  /// Examples: `4, `
  k8sCronjobAnnotation('k8s.cronjob.annotation'),

  /// The label placed on the CronJob, the `<key>` being the label name, the
  /// value being the label value.
  ///
  /// Examples: `weekly, `
  k8sCronjobLabel('k8s.cronjob.label'),

  /// The name of the CronJob.
  ///
  /// Examples: `opentelemetry`
  k8sCronjobName('k8s.cronjob.name'),

  /// The UID of the CronJob.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  k8sCronjobUid('k8s.cronjob.uid'),

  /// The annotation placed on the DaemonSet, the `<key>` being the
  /// annotation name, the value being the annotation value, even if the
  /// value is empty.
  ///
  /// Examples: `1, `
  k8sDaemonsetAnnotation('k8s.daemonset.annotation'),

  /// The label placed on the DaemonSet, the `<key>` being the label name,
  /// the value being the label value, even if the value is empty.
  ///
  /// Examples: `guestbook, `
  k8sDaemonsetLabel('k8s.daemonset.label'),

  /// The name of the DaemonSet.
  ///
  /// Examples: `opentelemetry`
  k8sDaemonsetName('k8s.daemonset.name'),

  /// The UID of the DaemonSet.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  k8sDaemonsetUid('k8s.daemonset.uid'),

  /// The annotation placed on the Deployment, the `<key>` being the
  /// annotation name, the value being the annotation value, even if the
  /// value is empty.
  ///
  /// Examples: `1, `
  k8sDeploymentAnnotation('k8s.deployment.annotation'),

  /// The label placed on the Deployment, the `<key>` being the label name,
  /// the value being the label value, even if the value is empty.
  ///
  /// Examples: `guestbook, `
  k8sDeploymentLabel('k8s.deployment.label'),

  /// The name of the Deployment.
  ///
  /// Examples: `opentelemetry`
  k8sDeploymentName('k8s.deployment.name'),

  /// The UID of the Deployment.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  k8sDeploymentUid('k8s.deployment.uid'),

  /// The type of metric source for the horizontal pod autoscaler.
  ///
  /// Examples: `Resource, ContainerResource`
  ///
  /// Stability: development
  k8sHpaMetricType('k8s.hpa.metric.type'),

  /// The name of the horizontal pod autoscaler.
  ///
  /// Examples: `opentelemetry`
  ///
  /// Stability: development
  k8sHpaName('k8s.hpa.name'),

  /// The API version of the target resource to scale for the
  /// HorizontalPodAutoscaler.
  ///
  /// Examples: `apps/v1, autoscaling/v2`
  ///
  /// Stability: development
  k8sHpaScaletargetrefApiVersion('k8s.hpa.scaletargetref.api_version'),

  /// The kind of the target resource to scale for the
  /// HorizontalPodAutoscaler.
  ///
  /// Examples: `Deployment, StatefulSet`
  ///
  /// Stability: development
  k8sHpaScaletargetrefKind('k8s.hpa.scaletargetref.kind'),

  /// The name of the target resource to scale for the
  /// HorizontalPodAutoscaler.
  ///
  /// Examples: `my-deployment, my-statefulset`
  ///
  /// Stability: development
  k8sHpaScaletargetrefName('k8s.hpa.scaletargetref.name'),

  /// The UID of the horizontal pod autoscaler.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  ///
  /// Stability: development
  k8sHpaUid('k8s.hpa.uid'),

  /// The size (identifier) of the K8s huge page.
  ///
  /// Examples: `2Mi`
  ///
  /// Stability: development
  k8sHugepageSize('k8s.hugepage.size'),

  /// The annotation placed on the Job, the `<key>` being the annotation
  /// name, the value being the annotation value, even if the value is empty.
  ///
  /// Examples: `1, `
  k8sJobAnnotation('k8s.job.annotation'),

  /// The label placed on the Job, the `<key>` being the label name, the
  /// value being the label value, even if the value is empty.
  ///
  /// Examples: `ci, `
  k8sJobLabel('k8s.job.label'),

  /// The name of the Job.
  ///
  /// Examples: `opentelemetry`
  k8sJobName('k8s.job.name'),

  /// The UID of the Job.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  k8sJobUid('k8s.job.uid'),

  /// The annotation placed on the Namespace, the `<key>` being the
  /// annotation name, the value being the annotation value, even if the
  /// value is empty.
  ///
  /// Examples: `0, `
  k8sNamespaceAnnotation('k8s.namespace.annotation'),

  /// The label placed on the Namespace, the `<key>` being the label name,
  /// the value being the label value, even if the value is empty.
  ///
  /// Examples: `default, `
  k8sNamespaceLabel('k8s.namespace.label'),

  /// The name of the namespace that the pod is running in.
  ///
  /// Examples: `default`
  k8sNamespaceName('k8s.namespace.name'),

  /// The phase of the K8s namespace.
  ///
  /// Examples: `active, terminating`
  ///
  /// Stability: development
  k8sNamespacePhase('k8s.namespace.phase'),

  /// The annotation placed on the Node, the `<key>` being the annotation
  /// name, the value being the annotation value, even if the value is empty.
  ///
  /// Examples: `0, `
  k8sNodeAnnotation('k8s.node.annotation'),

  /// The status of the condition, one of True, False, Unknown.
  ///
  /// Examples: `true, false, unknown`
  ///
  /// Stability: development
  k8sNodeConditionStatus('k8s.node.condition.status'),

  /// The condition type of a K8s Node.
  ///
  /// Examples: `Ready, DiskPressure`
  ///
  /// Stability: development
  k8sNodeConditionType('k8s.node.condition.type'),

  /// The label placed on the Node, the `<key>` being the label name, the
  /// value being the label value, even if the value is empty.
  ///
  /// Examples: `arm64, `
  k8sNodeLabel('k8s.node.label'),

  /// The name of the Node.
  ///
  /// Examples: `node-1`
  k8sNodeName('k8s.node.name'),

  /// The name of the system container running on the K8s Node.
  ///
  /// Examples: `kubelet, runtime, pods, misc`
  ///
  /// Stability: development
  k8sNodeSystemContainerName('k8s.node.system_container.name'),

  /// The UID of the Node.
  ///
  /// Examples: `1eb3a0c6-0477-4080-a9cb-0cb7db65c6a2`
  k8sNodeUid('k8s.node.uid'),

  /// The annotation placed on the PersistentVolume, the `<key>` being the
  /// annotation name, the value being the annotation value, even if the
  /// value is empty.
  ///
  /// Examples: `kubernetes.io/aws-ebs, `
  ///
  /// Stability: development
  k8sPersistentvolumeAnnotation('k8s.persistentvolume.annotation'),

  /// The label placed on the PersistentVolume, the `<key>` being the label
  /// name, the value being the label value, even if the value is empty.
  ///
  /// Examples: `ssd, `
  ///
  /// Stability: development
  k8sPersistentvolumeLabel('k8s.persistentvolume.label'),

  /// The name of the PersistentVolume.
  ///
  /// Examples: `pv-data-01`
  ///
  /// Stability: development
  k8sPersistentvolumeName('k8s.persistentvolume.name'),

  /// The reclaim policy of the PersistentVolume.
  ///
  /// Examples: `Delete, Retain, Recycle`
  ///
  /// Stability: development
  k8sPersistentvolumeReclaimPolicy('k8s.persistentvolume.reclaim_policy'),

  /// The phase of the PersistentVolume.
  ///
  /// Examples: `Pending, Available, Bound, Released, Failed`
  ///
  /// Stability: development
  k8sPersistentvolumeStatusPhase('k8s.persistentvolume.status.phase'),

  /// The UID of the PersistentVolume.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  ///
  /// Stability: development
  k8sPersistentvolumeUid('k8s.persistentvolume.uid'),

  /// The annotation placed on the PersistentVolumeClaim, the `<key>` being
  /// the annotation name, the value being the annotation value, even if the
  /// value is empty.
  ///
  /// Examples: `kubernetes.io/aws-ebs, `
  ///
  /// Stability: development
  k8sPersistentvolumeclaimAnnotation('k8s.persistentvolumeclaim.annotation'),

  /// The label placed on the PersistentVolumeClaim, the `<key>` being the
  /// label name, the value being the label value, even if the value is
  /// empty.
  ///
  /// Examples: `my-app, `
  ///
  /// Stability: development
  k8sPersistentvolumeclaimLabel('k8s.persistentvolumeclaim.label'),

  /// The name of the PersistentVolumeClaim.
  ///
  /// Examples: `pvc-data-01`
  ///
  /// Stability: development
  k8sPersistentvolumeclaimName('k8s.persistentvolumeclaim.name'),

  /// The phase of the PersistentVolumeClaim.
  ///
  /// Examples: `Pending, Bound, Lost`
  ///
  /// Stability: development
  k8sPersistentvolumeclaimStatusPhase('k8s.persistentvolumeclaim.status.phase'),

  /// The UID of the PersistentVolumeClaim.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  ///
  /// Stability: development
  k8sPersistentvolumeclaimUid('k8s.persistentvolumeclaim.uid'),

  /// The annotation placed on the Pod, the `<key>` being the annotation
  /// name, the value being the annotation value.
  ///
  /// Examples: `true, x64, `
  k8sPodAnnotation('k8s.pod.annotation'),

  /// Specifies the hostname of the Pod.
  ///
  /// Examples: `collector-gateway`
  k8sPodHostname('k8s.pod.hostname'),

  /// IP address allocated to the Pod.
  ///
  /// Examples: `172.18.0.2`
  k8sPodIp('k8s.pod.ip'),

  /// The label placed on the Pod, the `<key>` being the label name, the
  /// value being the label value.
  ///
  /// Examples: `my-app, x64, `
  k8sPodLabel('k8s.pod.label'),

  /// Deprecated, use `k8s.pod.label` instead.
  ///
  /// Examples: `my-app`
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.pod.label`.')
  k8sPodLabels('k8s.pod.labels'),

  /// The name of the Pod.
  ///
  /// Examples: `opentelemetry-pod-autoconf`
  k8sPodName('k8s.pod.name'),

  /// The start timestamp of the Pod.
  ///
  /// Examples: `2025-12-04T08:41:03Z`
  k8sPodStartTime('k8s.pod.start_time'),

  /// The phase for the pod. Corresponds to the `phase` field of the:
  /// [K8s PodStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#podstatus-v1-core)
  ///
  /// Examples: `Pending, Running`
  ///
  /// Stability: development
  k8sPodStatusPhase('k8s.pod.status.phase'),

  /// The reason for the pod state. Corresponds to the `reason` field of the:
  /// [K8s PodStatus](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.33/#podstatus-v1-core)
  ///
  /// Examples: `Evicted, NodeAffinity`
  ///
  /// Stability: development
  k8sPodStatusReason('k8s.pod.status.reason'),

  /// The UID of the Pod.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  k8sPodUid('k8s.pod.uid'),

  /// The annotation placed on the ReplicaSet, the `<key>` being the
  /// annotation name, the value being the annotation value, even if the
  /// value is empty.
  ///
  /// Examples: `0, `
  k8sReplicasetAnnotation('k8s.replicaset.annotation'),

  /// The label placed on the ReplicaSet, the `<key>` being the label name,
  /// the value being the label value, even if the value is empty.
  ///
  /// Examples: `guestbook, `
  k8sReplicasetLabel('k8s.replicaset.label'),

  /// The name of the ReplicaSet.
  ///
  /// Examples: `opentelemetry`
  k8sReplicasetName('k8s.replicaset.name'),

  /// The UID of the ReplicaSet.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  k8sReplicasetUid('k8s.replicaset.uid'),

  /// The name of the replication controller.
  ///
  /// Examples: `opentelemetry`
  ///
  /// Stability: development
  k8sReplicationcontrollerName('k8s.replicationcontroller.name'),

  /// The UID of the replication controller.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  ///
  /// Stability: development
  k8sReplicationcontrollerUid('k8s.replicationcontroller.uid'),

  /// The name of the resource quota.
  ///
  /// Examples: `opentelemetry`
  ///
  /// Stability: development
  k8sResourcequotaName('k8s.resourcequota.name'),

  /// The name of the K8s resource a resource quota defines.
  ///
  /// Examples: `count/replicationcontrollers`
  ///
  /// Stability: development
  k8sResourcequotaResourceName('k8s.resourcequota.resource_name'),

  /// The UID of the resource quota.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  ///
  /// Stability: development
  k8sResourcequotaUid('k8s.resourcequota.uid'),

  /// The annotation placed on the Service, the `<key>` being the annotation
  /// name, the value being the annotation value, even if the value is empty.
  ///
  /// Examples: `true, `
  ///
  /// Stability: development
  k8sServiceAnnotation('k8s.service.annotation'),

  /// The address type of the service endpoint.
  ///
  /// Examples: `IPv4, IPv6`
  ///
  /// Stability: development
  k8sServiceEndpointAddressType('k8s.service.endpoint.address_type'),

  /// The condition of the service endpoint.
  ///
  /// Examples: `ready, serving, terminating`
  ///
  /// Stability: development
  k8sServiceEndpointCondition('k8s.service.endpoint.condition'),

  /// The zone of the service endpoint.
  ///
  /// Examples: `us-east-1a, us-west-2b, zone-a, `
  ///
  /// Stability: development
  k8sServiceEndpointZone('k8s.service.endpoint.zone'),

  /// The label placed on the Service, the `<key>` being the label name, the
  /// value being the label value, even if the value is empty.
  ///
  /// Examples: `my-service, `
  ///
  /// Stability: development
  k8sServiceLabel('k8s.service.label'),

  /// The name of the Service.
  ///
  /// Examples: `my-service`
  ///
  /// Stability: development
  k8sServiceName('k8s.service.name'),

  /// Whether the Service publishes not-ready endpoints.
  ///
  /// Examples: `true, false`
  ///
  /// Stability: development
  k8sServicePublishNotReadyAddresses('k8s.service.publish_not_ready_addresses'),

  /// The selector key-value pair placed on the Service, the `<key>` being
  /// the selector key, the value being the selector value.
  ///
  /// Examples: `my-app, v1`
  ///
  /// Stability: development
  k8sServiceSelector('k8s.service.selector'),

  /// The traffic distribution policy for the Service.
  ///
  /// Examples: `PreferSameZone, PreferSameNode`
  ///
  /// Stability: development
  k8sServiceTrafficDistribution('k8s.service.traffic_distribution'),

  /// The type of the Kubernetes Service.
  ///
  /// Examples: `ClusterIP, NodePort, LoadBalancer`
  ///
  /// Stability: development
  k8sServiceType('k8s.service.type'),

  /// The UID of the Service.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  ///
  /// Stability: development
  k8sServiceUid('k8s.service.uid'),

  /// The annotation placed on the StatefulSet, the `<key>` being the
  /// annotation name, the value being the annotation value, even if the
  /// value is empty.
  ///
  /// Examples: `1, `
  k8sStatefulsetAnnotation('k8s.statefulset.annotation'),

  /// The label placed on the StatefulSet, the `<key>` being the label name,
  /// the value being the label value, even if the value is empty.
  ///
  /// Examples: `guestbook, `
  k8sStatefulsetLabel('k8s.statefulset.label'),

  /// The name of the StatefulSet.
  ///
  /// Examples: `opentelemetry`
  k8sStatefulsetName('k8s.statefulset.name'),

  /// The UID of the StatefulSet.
  ///
  /// Examples: `275ecb36-5aa8-4c2a-9c47-d8bb681b9aff`
  k8sStatefulsetUid('k8s.statefulset.uid'),

  /// The name of K8s
  /// [StorageClass](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.34/#storageclass-v1-storage-k8s-io)
  ///  object.
  ///
  /// Examples: `gold.storageclass.storage.k8s.io`
  ///
  /// Stability: development
  k8sStorageclassName('k8s.storageclass.name'),

  /// The name of the K8s volume.
  ///
  /// Examples: `volume0`
  ///
  /// Stability: development
  k8sVolumeName('k8s.volume.name'),

  /// The type of the K8s volume.
  ///
  /// Examples: `emptyDir, persistentVolumeClaim`
  ///
  /// Stability: development
  k8sVolumeType('k8s.volume.type');

  @override
  final String key;

  const K8s(this.key);

  @override
  String toString() => key;
}

/// Values for `k8s.container.ephemeral_storage.fs_type`.
///
/// Stability: development
enum K8sContainerEphemeralStorageFsType implements OTelSemanticValue {
  /// For the container's writable layer usage.
  ///
  /// Stability: development
  rootfs('rootfs'),

  /// For the container's log files usage (stdout/stderr).
  ///
  /// Stability: development
  logs('logs');

  @override
  final String value;

  const K8sContainerEphemeralStorageFsType(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.container.status.reason`.
///
/// Stability: development
enum K8sContainerStatusReason implements OTelSemanticValue {
  /// The container is being created.
  ///
  /// Stability: development
  containerCreating('ContainerCreating'),

  /// The container is in a crash loop back off state.
  ///
  /// Stability: development
  crashLoopBackOff('CrashLoopBackOff'),

  /// There was an error creating the container configuration.
  ///
  /// Stability: development
  createContainerConfigError('CreateContainerConfigError'),

  /// There was an error pulling the container image.
  ///
  /// Stability: development
  errImagePull('ErrImagePull'),

  /// The container image pull is in back off state.
  ///
  /// Stability: development
  imagePullBackOff('ImagePullBackOff'),

  /// The container was killed due to out of memory.
  ///
  /// Stability: development
  oomKilled('OOMKilled'),

  /// The container has completed execution.
  ///
  /// Stability: development
  completed('Completed'),

  /// There was an error with the container.
  ///
  /// Stability: development
  error('Error'),

  /// The container cannot run.
  ///
  /// Stability: development
  containerCannotRun('ContainerCannotRun');

  @override
  final String value;

  const K8sContainerStatusReason(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.container.status.state`.
///
/// Stability: development
enum K8sContainerStatusState implements OTelSemanticValue {
  /// The container has terminated.
  ///
  /// Stability: development
  terminated('terminated'),

  /// The container is running.
  ///
  /// Stability: development
  running('running'),

  /// The container is waiting.
  ///
  /// Stability: development
  waiting('waiting');

  @override
  final String value;

  const K8sContainerStatusState(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.namespace.phase`.
///
/// Stability: development
enum K8sNamespacePhase implements OTelSemanticValue {
  /// Active namespace phase as described by
  /// [K8s API](https://pkg.go.dev/k8s.io/api@v0.31.3/core/v1#NamespacePhase)
  ///
  /// Stability: development
  active('active'),

  /// Terminating namespace phase as described by
  /// [K8s API](https://pkg.go.dev/k8s.io/api@v0.31.3/core/v1#NamespacePhase)
  ///
  /// Stability: development
  terminating('terminating');

  @override
  final String value;

  const K8sNamespacePhase(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.node.condition.status`.
///
/// Stability: development
enum K8sNodeConditionStatus implements OTelSemanticValue {
  /// Stability: development
  conditionTrue('true'),

  /// Stability: development
  conditionFalse('false'),

  /// Stability: development
  conditionUnknown('unknown');

  @override
  final String value;

  const K8sNodeConditionStatus(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.node.condition.type`.
///
/// Stability: development
enum K8sNodeConditionType implements OTelSemanticValue {
  /// The node is healthy and ready to accept pods
  ///
  /// Stability: development
  ready('Ready'),

  /// Pressure exists on the disk size—that is, if the disk capacity is low
  ///
  /// Stability: development
  diskPressure('DiskPressure'),

  /// Pressure exists on the node memory—that is, if the node memory is low
  ///
  /// Stability: development
  memoryPressure('MemoryPressure'),

  /// Pressure exists on the processes—that is, if there are too many
  /// processes on the node
  ///
  /// Stability: development
  pidPressure('PIDPressure'),

  /// The network for the node is not correctly configured
  ///
  /// Stability: development
  networkUnavailable('NetworkUnavailable');

  @override
  final String value;

  const K8sNodeConditionType(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.persistentvolume.reclaim_policy`.
///
/// Stability: development
enum K8sPersistentvolumeReclaimPolicy implements OTelSemanticValue {
  /// The volume will be deleted when released from its claim.
  ///
  /// Stability: development
  delete('Delete'),

  /// The volume will be recycled (basic scrub) when released from its claim.
  ///
  /// Stability: development
  recycle('Recycle'),

  /// The volume will be retained when released from its claim.
  ///
  /// Stability: development
  retain('Retain');

  @override
  final String value;

  const K8sPersistentvolumeReclaimPolicy(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.persistentvolume.status.phase`.
///
/// Stability: development
enum K8sPersistentvolumeStatusPhase implements OTelSemanticValue {
  /// The volume is available and not yet bound to a claim.
  ///
  /// Stability: development
  available('Available'),

  /// The volume is bound to a claim.
  ///
  /// Stability: development
  bound('Bound'),

  /// The volume has failed its automatic reclamation.
  ///
  /// Stability: development
  failed('Failed'),

  /// The volume is being provisioned.
  ///
  /// Stability: development
  pending('Pending'),

  /// The claim has been deleted but the volume is not yet available.
  ///
  /// Stability: development
  released('Released');

  @override
  final String value;

  const K8sPersistentvolumeStatusPhase(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.persistentvolumeclaim.status.phase`.
///
/// Stability: development
enum K8sPersistentvolumeclaimStatusPhase implements OTelSemanticValue {
  /// The claim is bound to a volume.
  ///
  /// Stability: development
  bound('Bound'),

  /// The claim has lost its underlying volume (the volume does not exist
  /// anymore).
  ///
  /// Stability: development
  lost('Lost'),

  /// The claim has not yet been bound to a volume.
  ///
  /// Stability: development
  pending('Pending');

  @override
  final String value;

  const K8sPersistentvolumeclaimStatusPhase(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.pod.status.phase`.
///
/// Stability: development
enum K8sPodStatusPhase implements OTelSemanticValue {
  /// The pod has been accepted by the system, but one or more of the
  /// containers has not been started. This includes time before being bound
  /// to a node, as well as time spent pulling images onto the host.
  ///
  /// Stability: development
  pending('Pending'),

  /// The pod has been bound to a node and all of the containers have been
  /// started. At least one container is still running or is in the process
  /// of being restarted.
  ///
  /// Stability: development
  running('Running'),

  /// All containers in the pod have voluntarily terminated with a container
  /// exit code of 0, and the system is not going to restart any of these
  /// containers.
  ///
  /// Stability: development
  succeeded('Succeeded'),

  /// All containers in the pod have terminated, and at least one container
  /// has terminated in a failure (exited with a non-zero exit code or was
  /// stopped by the system).
  ///
  /// Stability: development
  failed('Failed'),

  /// For some reason the state of the pod could not be obtained, typically
  /// due to an error in communicating with the host of the pod.
  ///
  /// Stability: development
  unknown('Unknown');

  @override
  final String value;

  const K8sPodStatusPhase(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.pod.status.reason`.
///
/// Stability: development
enum K8sPodStatusReason implements OTelSemanticValue {
  /// The pod is evicted.
  ///
  /// Stability: development
  evicted('Evicted'),

  /// The pod is in a status because of its node affinity
  ///
  /// Stability: development
  nodeAffinity('NodeAffinity'),

  /// The reason on a pod when its state cannot be confirmed as kubelet is
  /// unresponsive on the node it is (was) running.
  ///
  /// Stability: development
  nodeLost('NodeLost'),

  /// The node is shutdown
  ///
  /// Stability: development
  shutdown('Shutdown'),

  /// The pod was rejected admission to the node because of an error during
  /// admission that could not be categorized.
  ///
  /// Stability: development
  unexpectedAdmissionError('UnexpectedAdmissionError');

  @override
  final String value;

  const K8sPodStatusReason(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.service.endpoint.address_type`.
///
/// Stability: development
enum K8sServiceEndpointAddressType implements OTelSemanticValue {
  /// IPv4 address type
  ///
  /// Stability: development
  ipv4('IPv4'),

  /// IPv6 address type
  ///
  /// Stability: development
  ipv6('IPv6'),

  /// FQDN address type
  ///
  /// Stability: development
  fqdn('FQDN');

  @override
  final String value;

  const K8sServiceEndpointAddressType(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.service.endpoint.condition`.
///
/// Stability: development
enum K8sServiceEndpointCondition implements OTelSemanticValue {
  /// The endpoint is ready to receive new connections.
  ///
  /// Stability: development
  ready('ready'),

  /// The endpoint is currently handling traffic.
  ///
  /// Stability: development
  serving('serving'),

  /// The endpoint is in the process of shutting down.
  ///
  /// Stability: development
  terminating('terminating');

  @override
  final String value;

  const K8sServiceEndpointCondition(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.service.type`.
///
/// Stability: development
enum K8sServiceType implements OTelSemanticValue {
  /// ClusterIP service type
  ///
  /// Stability: development
  clusterIp('ClusterIP'),

  /// NodePort service type
  ///
  /// Stability: development
  nodePort('NodePort'),

  /// LoadBalancer service type
  ///
  /// Stability: development
  loadBalancer('LoadBalancer'),

  /// ExternalName service type
  ///
  /// Stability: development
  externalName('ExternalName');

  @override
  final String value;

  const K8sServiceType(this.value);

  @override
  String toString() => value;
}

/// Values for `k8s.volume.type`.
///
/// Stability: development
enum K8sVolumeType implements OTelSemanticValue {
  /// A
  /// [persistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/volumes/#persistentvolumeclaim)
  ///  volume
  ///
  /// Stability: development
  persistentVolumeClaim('persistentVolumeClaim'),

  /// A
  /// [configMap](https://kubernetes.io/docs/concepts/storage/volumes/#configmap)
  ///  volume
  ///
  /// Stability: development
  configMap('configMap'),

  /// A
  /// [downwardAPI](https://kubernetes.io/docs/concepts/storage/volumes/#downwardapi)
  ///  volume
  ///
  /// Stability: development
  downwardApi('downwardAPI'),

  /// An
  /// [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)
  ///  volume
  ///
  /// Stability: development
  emptyDir('emptyDir'),

  /// A [secret](https://kubernetes.io/docs/concepts/storage/volumes/#secret)
  ///  volume
  ///
  /// Stability: development
  secret('secret'),

  /// A [local](https://kubernetes.io/docs/concepts/storage/volumes/#local)
  /// volume
  ///
  /// Stability: development
  local('local');

  @override
  final String value;

  const K8sVolumeType(this.value);

  @override
  String toString() => value;
}
