// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `linux`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/linux/)
library;

import '../semantics_base.dart';

/// `linux.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Linux implements OTelSemantic {
  /// The Linux Slab memory state
  ///
  /// Examples: `reclaimable, unreclaimable`
  ///
  /// Stability: development
  @Deprecated('Replaced by `system.memory.linux.slab.state`.')
  linuxMemorySlabState('linux.memory.slab.state');

  @override
  final String key;

  const Linux(this.key);

  @override
  String toString() => key;
}

/// Values for `linux.memory.slab.state`.
///
/// Stability: development
@Deprecated('Replaced by `system.memory.linux.slab.state`.')
enum LinuxMemorySlabState implements OTelSemanticValue {
  /// Stability: development
  reclaimable('reclaimable'),

  /// Stability: development
  unreclaimable('unreclaimable');

  @override
  final String value;

  const LinuxMemorySlabState(this.value);

  @override
  String toString() => value;
}
