// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `log`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/log/)
library;

import '../semantics_base.dart';

/// `log.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Log implements OTelSemantic {
  /// The basename of the file.
  ///
  /// Examples: `audit.log`
  ///
  /// Stability: development
  logFileName('log.file.name'),

  /// The basename of the file, with symlinks resolved.
  ///
  /// Examples: `uuid.log`
  ///
  /// Stability: development
  logFileNameResolved('log.file.name_resolved'),

  /// The full path to the file.
  ///
  /// Examples: `/var/log/mysql/audit.log`
  ///
  /// Stability: development
  logFilePath('log.file.path'),

  /// The full path to the file, with symlinks resolved.
  ///
  /// Examples: `/var/lib/docker/uuid.log`
  ///
  /// Stability: development
  logFilePathResolved('log.file.path_resolved'),

  /// The stream associated with the log. See below for a list of well-known
  /// values.
  ///
  /// Stability: development
  logIostream('log.iostream'),

  /// The complete original Log Record.
  ///
  /// Examples:
  /// `77 <86>1 2015-08-06T21:58:59.694Z 192.168.2.133 inactive - - - Something happened, [INFO] 8/3/24 12:34:56 Something happened`
  ///
  /// Stability: development
  logRecordOriginal('log.record.original'),

  /// A unique identifier for the Log Record.
  ///
  /// Examples: `01ARZ3NDEKTSV4RRFFQ69G5FAV`
  ///
  /// Stability: development
  logRecordUid('log.record.uid');

  @override
  final String key;

  const Log(this.key);

  @override
  String toString() => key;
}

/// Values for `log.iostream`.
///
/// Stability: development
enum LogIostream implements OTelSemanticValue {
  /// Logs from stdout stream
  ///
  /// Stability: development
  stdout('stdout'),

  /// Events from stderr stream
  ///
  /// Stability: development
  stderr('stderr');

  @override
  final String value;

  const LogIostream(this.value);

  @override
  String toString() => value;
}
