// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `mcp`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/mcp/)
library;

import '../semantics_base.dart';

/// `mcp.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Mcp implements OTelSemantic {
  /// The name of the request or notification method.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  mcpMethodName('mcp.method.name'),

  /// The [version](https://modelcontextprotocol.io/specification/versioning)
  ///  of the Model Context Protocol used.
  ///
  /// Examples: `2025-06-18`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  mcpProtocolVersion('mcp.protocol.version'),

  /// The value of the resource uri.
  ///
  /// Examples:
  /// `postgres://database/customers/schema, file:///home/user/documents/report.pdf`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  mcpResourceUri('mcp.resource.uri'),

  /// Identifies
  /// [MCP session](https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#session-management)
  /// .
  ///
  /// Examples: `191c4850af6c49e08843a3f6c80e5046`
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  mcpSessionId('mcp.session.id');

  @override
  final String key;

  const Mcp(this.key);

  @override
  String toString() => key;
}

/// Values for `mcp.method.name`.
///
/// Stability: development
@Deprecated(
    'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
enum McpMethodName implements OTelSemanticValue {
  /// Notification cancelling a previously-issued request.
  ///
  /// Stability: development
  notificationsCancelled('notifications/cancelled'),

  /// Request to initialize the MCP client.
  ///
  /// Stability: development
  initialize('initialize'),

  /// Notification indicating that the MCP client has been initialized.
  ///
  /// Stability: development
  notificationsInitialized('notifications/initialized'),

  /// Notification indicating the progress for a long-running operation.
  ///
  /// Stability: development
  notificationsProgress('notifications/progress'),

  /// Request to check that the other party is still alive.
  ///
  /// Stability: development
  ping('ping'),

  /// Request to list resources available on server.
  ///
  /// Stability: development
  resourcesList('resources/list'),

  /// Request to list resource templates available on server.
  ///
  /// Stability: development
  resourcesTemplatesList('resources/templates/list'),

  /// Request to read a resource.
  ///
  /// Stability: development
  resourcesRead('resources/read'),

  /// Notification indicating that the list of resources has changed.
  ///
  /// Stability: development
  notificationsResourcesListChanged('notifications/resources/list_changed'),

  /// Request to subscribe to a resource.
  ///
  /// Stability: development
  resourcesSubscribe('resources/subscribe'),

  /// Request to unsubscribe from resource updates.
  ///
  /// Stability: development
  resourcesUnsubscribe('resources/unsubscribe'),

  /// Notification indicating that a resource has been updated.
  ///
  /// Stability: development
  notificationsResourcesUpdated('notifications/resources/updated'),

  /// Request to list prompts available on server.
  ///
  /// Stability: development
  promptsList('prompts/list'),

  /// Request to get a prompt.
  ///
  /// Stability: development
  promptsGet('prompts/get'),

  /// Notification indicating that the list of prompts has changed.
  ///
  /// Stability: development
  notificationsPromptsListChanged('notifications/prompts/list_changed'),

  /// Request to list tools available on server.
  ///
  /// Stability: development
  toolsList('tools/list'),

  /// Request to call a tool.
  ///
  /// Stability: development
  toolsCall('tools/call'),

  /// Notification indicating that the list of tools has changed.
  ///
  /// Stability: development
  notificationsToolsListChanged('notifications/tools/list_changed'),

  /// Request to set the logging level.
  ///
  /// Stability: development
  loggingSetLevel('logging/setLevel'),

  /// Notification indicating that a message has been received.
  ///
  /// Stability: development
  notificationsMessage('notifications/message'),

  /// Request to create a sampling message.
  ///
  /// Stability: development
  samplingCreateMessage('sampling/createMessage'),

  /// Request to complete a prompt.
  ///
  /// Stability: development
  completionComplete('completion/complete'),

  /// Request to list roots available on server.
  ///
  /// Stability: development
  rootsList('roots/list'),

  /// Notification indicating that the list of roots has changed.
  ///
  /// Stability: development
  notificationsRootsListChanged('notifications/roots/list_changed'),

  /// Request from the server to elicit additional information from the user
  /// via the client
  ///
  /// Stability: development
  elicitationCreate('elicitation/create');

  @override
  final String value;

  const McpMethodName(this.value);

  @override
  String toString() => value;
}
