// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `message`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/message/)
library;

import '../semantics_base.dart';

/// `message.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Message implements OTelSemantic {
  /// Deprecated, no replacement at this time.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  messageCompressedSize('message.compressed_size'),

  /// Deprecated, no replacement at this time.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  messageId('message.id'),

  /// Deprecated, no replacement at this time.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  messageType('message.type'),

  /// Deprecated, no replacement at this time.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  messageUncompressedSize('message.uncompressed_size');

  @override
  final String key;

  const Message(this.key);

  @override
  String toString() => key;
}

/// Values for `message.type`.
///
/// Stability: development
@Deprecated('Deprecated, no replacement at this time.')
enum MessageType implements OTelSemanticValue {
  /// Stability: development
  sent('SENT'),

  /// Stability: development
  received('RECEIVED');

  @override
  final String value;

  const MessageType(this.value);

  @override
  String toString() => value;
}
