// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `messaging`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/messaging/)
library;

import '../semantics_base.dart';

/// `messaging.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Messaging implements OTelSemantic {
  /// The number of messages sent, received, or processed in the scope of the
  /// batching operation.
  ///
  /// Examples: `0, 1, 2`
  ///
  /// Stability: development
  messagingBatchMessageCount('messaging.batch.message_count'),

  /// A unique identifier for the client that consumes or produces a message.
  ///
  /// Examples: `client-5, myhost@8742@s8083jm`
  ///
  /// Stability: development
  messagingClientId('messaging.client.id'),

  /// The name of the consumer group with which a consumer is associated.
  ///
  /// Examples: `my-group, indexer`
  ///
  /// Stability: development
  messagingConsumerGroupName('messaging.consumer.group.name'),

  /// A boolean that is true if the message destination is anonymous (could
  /// be unnamed or have auto-generated name).
  ///
  /// Stability: development
  messagingDestinationAnonymous('messaging.destination.anonymous'),

  /// The message destination name
  ///
  /// Examples: `MyQueue, MyTopic`
  ///
  /// Stability: development
  messagingDestinationName('messaging.destination.name'),

  /// The identifier of the partition messages are sent to or received from,
  /// unique within the `messaging.destination.name`.
  ///
  /// Examples: `1`
  ///
  /// Stability: development
  messagingDestinationPartitionId('messaging.destination.partition.id'),

  /// The name of the destination subscription from which a message is
  /// consumed.
  ///
  /// Examples: `subscription-a`
  ///
  /// Stability: development
  messagingDestinationSubscriptionName(
      'messaging.destination.subscription.name'),

  /// Low cardinality representation of the messaging destination name
  ///
  /// Examples: `/customers/{customerId}`
  ///
  /// Stability: development
  messagingDestinationTemplate('messaging.destination.template'),

  /// A boolean that is true if the message destination is temporary and
  /// might not exist anymore after messages are processed.
  ///
  /// Stability: development
  messagingDestinationTemporary('messaging.destination.temporary'),

  /// Deprecated, no replacement at this time.
  ///
  /// Stability: development
  @Deprecated('Removed. No replacement at this time.')
  messagingDestinationPublishAnonymous(
      'messaging.destination_publish.anonymous'),

  /// Deprecated, no replacement at this time.
  ///
  /// Examples: `MyQueue, MyTopic`
  ///
  /// Stability: development
  @Deprecated('Removed. No replacement at this time.')
  messagingDestinationPublishName('messaging.destination_publish.name'),

  /// Deprecated, use `messaging.consumer.group.name` instead.
  ///
  /// Examples: `$Default`
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.consumer.group.name`.')
  messagingEventhubsConsumerGroup('messaging.eventhubs.consumer.group'),

  /// The UTC epoch seconds at which the message has been accepted and stored
  /// in the entity.
  ///
  /// Examples: `1701393730`
  ///
  /// Stability: development
  messagingEventhubsMessageEnqueuedTime(
      'messaging.eventhubs.message.enqueued_time'),

  /// The ack deadline in seconds set for the modify ack deadline request.
  ///
  /// Examples: `10`
  ///
  /// Stability: development
  messagingGcpPubsubMessageAckDeadline(
      'messaging.gcp_pubsub.message.ack_deadline'),

  /// The ack id for a given message.
  ///
  /// Examples: `ack_id`
  ///
  /// Stability: development
  messagingGcpPubsubMessageAckId('messaging.gcp_pubsub.message.ack_id'),

  /// The delivery attempt for a given message.
  ///
  /// Examples: `2`
  ///
  /// Stability: development
  messagingGcpPubsubMessageDeliveryAttempt(
      'messaging.gcp_pubsub.message.delivery_attempt'),

  /// The ordering key for a given message. If the attribute is not present,
  /// the message does not have an ordering key.
  ///
  /// Examples: `ordering_key`
  ///
  /// Stability: development
  messagingGcpPubsubMessageOrderingKey(
      'messaging.gcp_pubsub.message.ordering_key'),

  /// The Kafka cluster id, obtained from the broker metadata exposed through
  /// the Kafka client (or AdminClient) API.
  ///
  /// Examples: `MkU3OEVBNTcwNTJENDM2Qk`
  ///
  /// Stability: development
  messagingKafkaClusterId('messaging.kafka.cluster.id'),

  /// Deprecated, use `messaging.consumer.group.name` instead.
  ///
  /// Examples: `my-group`
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.consumer.group.name`.')
  messagingKafkaConsumerGroup('messaging.kafka.consumer.group'),

  /// Deprecated, use `messaging.destination.partition.id` instead.
  ///
  /// Examples: `2`
  ///
  /// Stability: development
  @Deprecated(
      'Record string representation of the partition id in `messaging.destination.partition.id` attribute.')
  messagingKafkaDestinationPartition('messaging.kafka.destination.partition'),

  /// Message keys in Kafka are used for grouping alike messages to ensure
  /// they're processed on the same partition. They differ from
  /// `messaging.message.id` in that they're not unique. If the key is `null`
  /// , the attribute MUST NOT be set.
  ///
  /// Examples: `myKey`
  ///
  /// Stability: development
  messagingKafkaMessageKey('messaging.kafka.message.key'),

  /// Deprecated, use `messaging.kafka.offset` instead.
  ///
  /// Examples: `42`
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.kafka.offset`.')
  messagingKafkaMessageOffset('messaging.kafka.message.offset'),

  /// A boolean that is true if the message is a tombstone.
  ///
  /// Stability: development
  messagingKafkaMessageTombstone('messaging.kafka.message.tombstone'),

  /// The offset of a record in the corresponding Kafka partition.
  ///
  /// Examples: `42`
  ///
  /// Stability: development
  messagingKafkaOffset('messaging.kafka.offset'),

  /// The size of the message body in bytes.
  ///
  /// Examples: `1439`
  ///
  /// Stability: development
  messagingMessageBodySize('messaging.message.body.size'),

  /// The conversation ID identifying the conversation to which the message
  /// belongs, represented as a string. Sometimes called "Correlation ID".
  ///
  /// Examples: `MyConversationId`
  ///
  /// Stability: development
  messagingMessageConversationId('messaging.message.conversation_id'),

  /// The size of the message body and metadata in bytes.
  ///
  /// Examples: `2738`
  ///
  /// Stability: development
  messagingMessageEnvelopeSize('messaging.message.envelope.size'),

  /// A value used by the messaging system as an identifier for the message,
  /// represented as a string.
  ///
  /// Examples: `452a7c7c7c7048c2f887f61572b18fc2`
  ///
  /// Stability: development
  messagingMessageId('messaging.message.id'),

  /// Deprecated, use `messaging.operation.type` instead.
  ///
  /// Examples: `publish, create, process`
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.operation.type`.')
  messagingOperation('messaging.operation'),

  /// The system-specific name of the messaging operation.
  ///
  /// Examples: `ack, nack, send`
  ///
  /// Stability: development
  messagingOperationName('messaging.operation.name'),

  /// A string identifying the type of the messaging operation.
  ///
  /// Stability: development
  messagingOperationType('messaging.operation.type'),

  /// RabbitMQ message routing key.
  ///
  /// Examples: `myKey`
  ///
  /// Stability: development
  messagingRabbitmqDestinationRoutingKey(
      'messaging.rabbitmq.destination.routing_key'),

  /// RabbitMQ message delivery tag
  ///
  /// Examples: `123`
  ///
  /// Stability: development
  messagingRabbitmqMessageDeliveryTag(
      'messaging.rabbitmq.message.delivery_tag'),

  /// Deprecated, use `messaging.consumer.group.name` instead.
  ///
  /// Examples: `myConsumerGroup`
  ///
  /// Stability: development
  @Deprecated(
      'Replaced by `messaging.consumer.group.name` on the consumer spans. No replacement for producer spans.')
  messagingRocketmqClientGroup('messaging.rocketmq.client_group'),

  /// Model of message consumption. This only applies to consumer spans.
  ///
  /// Stability: development
  messagingRocketmqConsumptionModel('messaging.rocketmq.consumption_model'),

  /// The delay time level for delay message, which determines the message
  /// delay time.
  ///
  /// Examples: `3`
  ///
  /// Stability: development
  messagingRocketmqMessageDelayTimeLevel(
      'messaging.rocketmq.message.delay_time_level'),

  /// The timestamp in milliseconds that the delay message is expected to be
  /// delivered to consumer.
  ///
  /// Examples: `1665987217045`
  ///
  /// Stability: development
  messagingRocketmqMessageDeliveryTimestamp(
      'messaging.rocketmq.message.delivery_timestamp'),

  /// It is essential for FIFO message. Messages that belong to the same
  /// message group are always processed one by one within the same consumer
  /// group.
  ///
  /// Examples: `myMessageGroup`
  ///
  /// Stability: development
  messagingRocketmqMessageGroup('messaging.rocketmq.message.group'),

  /// Key(s) of message, another way to mark message besides message id.
  ///
  /// Examples: `["keyA", "keyB"]`
  ///
  /// Stability: development
  messagingRocketmqMessageKeys('messaging.rocketmq.message.keys'),

  /// The secondary classifier of message besides topic.
  ///
  /// Examples: `tagA`
  ///
  /// Stability: development
  messagingRocketmqMessageTag('messaging.rocketmq.message.tag'),

  /// Type of message.
  ///
  /// Stability: development
  messagingRocketmqMessageType('messaging.rocketmq.message.type'),

  /// Namespace of RocketMQ resources, resources in different namespaces are
  /// individual.
  ///
  /// Examples: `myNamespace`
  ///
  /// Stability: development
  messagingRocketmqNamespace('messaging.rocketmq.namespace'),

  /// Deprecated, use `messaging.destination.subscription.name` instead.
  ///
  /// Examples: `subscription-a`
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.destination.subscription.name`.')
  messagingServicebusDestinationSubscriptionName(
      'messaging.servicebus.destination.subscription_name'),

  /// Describes the
  /// [settlement type](https://learn.microsoft.com/azure/service-bus-messaging/message-transfers-locks-settlement#peeklock)
  /// .
  ///
  /// Stability: development
  messagingServicebusDispositionStatus(
      'messaging.servicebus.disposition_status'),

  /// Number of deliveries that have been attempted for this message.
  ///
  /// Examples: `2`
  ///
  /// Stability: development
  messagingServicebusMessageDeliveryCount(
      'messaging.servicebus.message.delivery_count'),

  /// The UTC epoch seconds at which the message has been accepted and stored
  /// in the entity.
  ///
  /// Examples: `1701393730`
  ///
  /// Stability: development
  messagingServicebusMessageEnqueuedTime(
      'messaging.servicebus.message.enqueued_time'),

  /// The messaging system as identified by the client instrumentation.
  ///
  /// Stability: development
  messagingSystem('messaging.system');

  @override
  final String key;

  const Messaging(this.key);

  @override
  String toString() => key;
}

/// Values for `messaging.operation.type`.
///
/// Stability: development
enum MessagingOperationType implements OTelSemanticValue {
  /// A message is created. "Create" spans always refer to a single message
  /// and are used to provide a unique creation context for messages in batch
  /// sending scenarios.
  ///
  /// Stability: development
  create('create'),

  /// One or more messages are provided for sending to an intermediary. If a
  /// single message is sent, the context of the "Send" span can be used as
  /// the creation context and no "Create" span needs to be created.
  ///
  /// Stability: development
  send('send'),

  /// One or more messages are requested by a consumer. This operation refers
  /// to pull-based scenarios, where consumers explicitly call methods of
  /// messaging SDKs to receive messages.
  ///
  /// Stability: development
  receive('receive'),

  /// One or more messages are processed by a consumer.
  ///
  /// Stability: development
  process('process'),

  /// One or more messages are settled.
  ///
  /// Stability: development
  settle('settle'),

  /// Deprecated. Use `process` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `process`.')
  deliver('deliver'),

  /// Deprecated. Use `send` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `send`.')
  publish('publish');

  @override
  final String value;

  const MessagingOperationType(this.value);

  @override
  String toString() => value;
}

/// Values for `messaging.rocketmq.consumption_model`.
///
/// Stability: development
enum MessagingRocketmqConsumptionModel implements OTelSemanticValue {
  /// Clustering consumption model
  ///
  /// Stability: development
  clustering('clustering'),

  /// Broadcasting consumption model
  ///
  /// Stability: development
  broadcasting('broadcasting');

  @override
  final String value;

  const MessagingRocketmqConsumptionModel(this.value);

  @override
  String toString() => value;
}

/// Values for `messaging.rocketmq.message.type`.
///
/// Stability: development
enum MessagingRocketmqMessageType implements OTelSemanticValue {
  /// Normal message
  ///
  /// Stability: development
  normal('normal'),

  /// FIFO message
  ///
  /// Stability: development
  fifo('fifo'),

  /// Delay message
  ///
  /// Stability: development
  delay('delay'),

  /// Transaction message
  ///
  /// Stability: development
  transaction('transaction');

  @override
  final String value;

  const MessagingRocketmqMessageType(this.value);

  @override
  String toString() => value;
}

/// Values for `messaging.servicebus.disposition_status`.
///
/// Stability: development
enum MessagingServicebusDispositionStatus implements OTelSemanticValue {
  /// Message is completed
  ///
  /// Stability: development
  complete('complete'),

  /// Message is abandoned
  ///
  /// Stability: development
  abandon('abandon'),

  /// Message is sent to dead letter queue
  ///
  /// Stability: development
  deadLetter('dead_letter'),

  /// Message is deferred
  ///
  /// Stability: development
  defer('defer');

  @override
  final String value;

  const MessagingServicebusDispositionStatus(this.value);

  @override
  String toString() => value;
}

/// Values for `messaging.system`.
///
/// Stability: development
enum MessagingSystem implements OTelSemanticValue {
  /// Apache ActiveMQ
  ///
  /// Stability: development
  activemq('activemq'),

  /// Amazon Simple Notification Service (SNS)
  ///
  /// Stability: development
  awsSns('aws.sns'),

  /// Amazon Simple Queue Service (SQS)
  ///
  /// Stability: development
  awsSqs('aws_sqs'),

  /// Azure Event Grid
  ///
  /// Stability: development
  eventgrid('eventgrid'),

  /// Azure Event Hubs
  ///
  /// Stability: development
  eventhubs('eventhubs'),

  /// Azure Service Bus
  ///
  /// Stability: development
  servicebus('servicebus'),

  /// Google Cloud Pub/Sub
  ///
  /// Stability: development
  gcpPubsub('gcp_pubsub'),

  /// Java Message Service
  ///
  /// Stability: development
  jms('jms'),

  /// Apache Kafka
  ///
  /// Stability: development
  kafka('kafka'),

  /// RabbitMQ
  ///
  /// Stability: development
  rabbitmq('rabbitmq'),

  /// Apache RocketMQ
  ///
  /// Stability: development
  rocketmq('rocketmq'),

  /// Apache Pulsar
  ///
  /// Stability: development
  pulsar('pulsar');

  @override
  final String value;

  const MessagingSystem(this.value);

  @override
  String toString() => value;
}
