// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `nfs`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/nfs/)
library;

import '../semantics_base.dart';

/// `nfs.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Nfs implements OTelSemantic {
  /// NFSv4+ operation name.
  ///
  /// Examples: `OPEN, READ, GETATTR`
  ///
  /// Stability: development
  nfsOperationName('nfs.operation.name'),

  /// Linux: one of "hit" (NFSD_STATS_RC_HITS), "miss"
  /// (NFSD_STATS_RC_MISSES), or "nocache" (NFSD_STATS_RC_NOCACHE --
  /// uncacheable)
  ///
  /// Examples: `hit`
  ///
  /// Stability: development
  nfsServerRepcacheStatus('nfs.server.repcache.status');

  @override
  final String key;

  const Nfs(this.key);

  @override
  String toString() => key;
}
