// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `oci`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/oci/)
library;

import '../semantics_base.dart';

/// `oci.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Oci implements OTelSemantic {
  /// The digest of the OCI image manifest. For container images specifically
  /// is the digest by which the container image is known.
  ///
  /// Examples:
  /// `sha256:e4ca62c0d62f3e886e684806dfe9d4e0cda60d54986898173c1083856cfda0f4`
  ///
  /// Stability: development
  ociManifestDigest('oci.manifest.digest');

  @override
  final String key;

  const Oci(this.key);

  @override
  String toString() => key;
}
