// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `onc_rpc`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/onc-rpc/)
library;

import '../semantics_base.dart';

/// `onc_rpc.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum OncRpc implements OTelSemantic {
  /// ONC/Sun RPC procedure name.
  ///
  /// Examples: `OPEN, READ, GETATTR`
  ///
  /// Stability: development
  oncRpcProcedureName('onc_rpc.procedure.name'),

  /// ONC/Sun RPC procedure number.
  ///
  /// Stability: development
  oncRpcProcedureNumber('onc_rpc.procedure.number'),

  /// ONC/Sun RPC program name.
  ///
  /// Examples: `portmapper, nfs`
  ///
  /// Stability: development
  oncRpcProgramName('onc_rpc.program.name'),

  /// ONC/Sun RPC program version.
  ///
  /// Stability: development
  oncRpcVersion('onc_rpc.version');

  @override
  final String key;

  const OncRpc(this.key);

  @override
  String toString() => key;
}
