// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `opentracing`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/opentracing/)
library;

import '../semantics_base.dart';

/// `opentracing.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Opentracing implements OTelSemantic {
  /// Parent-child Reference type
  ///
  /// Stability: development
  opentracingRefType('opentracing.ref_type');

  @override
  final String key;

  const Opentracing(this.key);

  @override
  String toString() => key;
}

/// Values for `opentracing.ref_type`.
///
/// Stability: development
enum OpentracingRefType implements OTelSemanticValue {
  /// The parent Span depends on the child Span in some capacity
  ///
  /// Stability: development
  childOf('child_of'),

  /// The parent Span doesn't depend in any way on the result of the child
  /// Span
  ///
  /// Stability: development
  followsFrom('follows_from');

  @override
  final String value;

  const OpentracingRefType(this.value);

  @override
  String toString() => value;
}
