// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `oracle`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/oracle/)
library;

import '../semantics_base.dart';

/// `oracle.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Oracle implements OTelSemantic {
  /// The database domain associated with the connection.
  ///
  /// Examples: `example.com, corp.internal, prod.db.local`
  ///
  /// Stability: release_candidate
  oracleDbDomain('oracle.db.domain'),

  /// The instance name associated with the connection in an Oracle Real
  /// Application Clusters environment.
  ///
  /// Examples: `ORCL1, ORCL2, ORCL3`
  ///
  /// Stability: release_candidate
  oracleDbInstanceName('oracle.db.instance.name'),

  /// The database name associated with the connection.
  ///
  /// Examples: `ORCL1, FREE`
  ///
  /// Stability: release_candidate
  oracleDbName('oracle.db.name'),

  /// The pluggable database (PDB) name associated with the connection.
  ///
  /// Examples: `PDB1, FREEPDB`
  ///
  /// Stability: release_candidate
  oracleDbPdb('oracle.db.pdb'),

  /// The service name currently associated with the database connection.
  ///
  /// Examples:
  /// `order-processing-service, db_low.adb.oraclecloud.com, db_high.adb.oraclecloud.com`
  ///
  /// Stability: release_candidate
  oracleDbService('oracle.db.service');

  @override
  final String key;

  const Oracle(this.key);

  @override
  String toString() => key;
}
