// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `otel`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/otel/)
library;

import '../semantics_base.dart';

/// `otel.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Otel implements OTelSemantic {
  /// A name uniquely identifying the instance of the OpenTelemetry component
  /// within its containing SDK instance.
  ///
  /// Examples: `otlp_grpc_span_exporter/0, custom-name`
  ///
  /// Stability: development
  otelComponentName('otel.component.name'),

  /// A name identifying the type of the OpenTelemetry component.
  ///
  /// Examples: `batching_span_processor, com.example.MySpanExporter`
  ///
  /// Stability: development
  otelComponentType('otel.component.type'),

  /// Identifies the class / type of event.
  ///
  /// Examples: `browser.mouse.click, device.app.lifecycle`
  otelEventName('otel.event.name'),

  /// Deprecated. Use the `otel.scope.name` attribute
  ///
  /// Examples: `io.opentelemetry.contrib.mongodb`
  ///
  /// Stability: development
  @Deprecated('Replaced by `otel.scope.name`.')
  otelLibraryName('otel.library.name'),

  /// Deprecated. Use the `otel.scope.version` attribute.
  ///
  /// Examples: `1.0.0`
  ///
  /// Stability: development
  @Deprecated('Replaced by `otel.scope.version`.')
  otelLibraryVersion('otel.library.version'),

  /// The name of the instrumentation scope - (`InstrumentationScope.Name` in
  /// OTLP).
  ///
  /// Examples: `io.opentelemetry.contrib.mongodb`
  otelScopeName('otel.scope.name'),

  /// The schema URL of the instrumentation scope.
  ///
  /// Examples: `https://opentelemetry.io/schemas/1.31.0`
  ///
  /// Stability: development
  otelScopeSchemaUrl('otel.scope.schema_url'),

  /// The version of the instrumentation scope - (
  /// `InstrumentationScope.Version` in OTLP).
  ///
  /// Examples: `1.0.0`
  otelScopeVersion('otel.scope.version'),

  /// Determines whether the span has a parent span, and if so,
  /// [whether it is a remote parent](https://opentelemetry.io/docs/specs/otel/trace/api/#isremote)
  ///
  /// Stability: development
  otelSpanParentOrigin('otel.span.parent.origin'),

  /// The result value of the sampler for this span
  ///
  /// Stability: development
  otelSpanSamplingResult('otel.span.sampling_result'),

  /// Name of the code, either "OK" or "ERROR". MUST NOT be set if the status
  /// code is UNSET.
  otelStatusCode('otel.status_code'),

  /// Description of the Status if it has a value, otherwise not set.
  ///
  /// Examples: `resource not found`
  otelStatusDescription('otel.status_description');

  @override
  final String key;

  const Otel(this.key);

  @override
  String toString() => key;
}

/// Values for `otel.component.type`.
///
/// Stability: development
enum OtelComponentType implements OTelSemanticValue {
  /// The builtin SDK batching span processor
  ///
  /// Stability: development
  batchingSpanProcessor('batching_span_processor'),

  /// The builtin SDK simple span processor
  ///
  /// Stability: development
  simpleSpanProcessor('simple_span_processor'),

  /// The builtin SDK batching log record processor
  ///
  /// Stability: development
  batchingLogProcessor('batching_log_processor'),

  /// The builtin SDK simple log record processor
  ///
  /// Stability: development
  simpleLogProcessor('simple_log_processor'),

  /// OTLP span exporter over gRPC with protobuf serialization
  ///
  /// Stability: development
  otlpGrpcSpanExporter('otlp_grpc_span_exporter'),

  /// OTLP span exporter over HTTP with protobuf serialization
  ///
  /// Stability: development
  otlpHttpSpanExporter('otlp_http_span_exporter'),

  /// OTLP span exporter over HTTP with JSON serialization
  ///
  /// Stability: development
  otlpHttpJsonSpanExporter('otlp_http_json_span_exporter'),

  /// Zipkin span exporter over HTTP
  ///
  /// Stability: development
  zipkinHttpSpanExporter('zipkin_http_span_exporter'),

  /// OTLP log record exporter over gRPC with protobuf serialization
  ///
  /// Stability: development
  otlpGrpcLogExporter('otlp_grpc_log_exporter'),

  /// OTLP log record exporter over HTTP with protobuf serialization
  ///
  /// Stability: development
  otlpHttpLogExporter('otlp_http_log_exporter'),

  /// OTLP log record exporter over HTTP with JSON serialization
  ///
  /// Stability: development
  otlpHttpJsonLogExporter('otlp_http_json_log_exporter'),

  /// The builtin SDK periodically exporting metric reader
  ///
  /// Stability: development
  periodicMetricReader('periodic_metric_reader'),

  /// OTLP metric exporter over gRPC with protobuf serialization
  ///
  /// Stability: development
  otlpGrpcMetricExporter('otlp_grpc_metric_exporter'),

  /// OTLP metric exporter over HTTP with protobuf serialization
  ///
  /// Stability: development
  otlpHttpMetricExporter('otlp_http_metric_exporter'),

  /// OTLP metric exporter over HTTP with JSON serialization
  ///
  /// Stability: development
  otlpHttpJsonMetricExporter('otlp_http_json_metric_exporter'),

  /// Prometheus metric exporter over HTTP with the default text-based format
  ///
  /// Stability: development
  prometheusHttpTextMetricExporter('prometheus_http_text_metric_exporter');

  @override
  final String value;

  const OtelComponentType(this.value);

  @override
  String toString() => value;
}

/// Values for `otel.span.parent.origin`.
///
/// Stability: development
enum OtelSpanParentOrigin implements OTelSemanticValue {
  /// The span does not have a parent, it is a root span
  ///
  /// Stability: development
  none('none'),

  /// The span has a parent and the parent's span context
  /// [isRemote()](https://opentelemetry.io/docs/specs/otel/trace/api/#isremote)
  ///  is false
  ///
  /// Stability: development
  local('local'),

  /// The span has a parent and the parent's span context
  /// [isRemote()](https://opentelemetry.io/docs/specs/otel/trace/api/#isremote)
  ///  is true
  ///
  /// Stability: development
  remote('remote');

  @override
  final String value;

  const OtelSpanParentOrigin(this.value);

  @override
  String toString() => value;
}

/// Values for `otel.span.sampling_result`.
///
/// Stability: development
enum OtelSpanSamplingResult implements OTelSemanticValue {
  /// The span is not sampled and not recording
  ///
  /// Stability: development
  drop('DROP'),

  /// The span is not sampled, but recording
  ///
  /// Stability: development
  recordOnly('RECORD_ONLY'),

  /// The span is sampled and recording
  ///
  /// Stability: development
  recordAndSample('RECORD_AND_SAMPLE');

  @override
  final String value;

  const OtelSpanSamplingResult(this.value);

  @override
  String toString() => value;
}

/// Values for `otel.status_code`.
enum OtelStatusCode implements OTelSemanticValue {
  /// The operation has been validated by an Application developer or
  /// Operator to have completed successfully.
  ok('OK'),

  /// The operation contains an error.
  error('ERROR');

  @override
  final String value;

  const OtelStatusCode(this.value);

  @override
  String toString() => value;
}
