// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `peer`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/peer/)
library;

import '../semantics_base.dart';

/// `peer.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Peer implements OTelSemantic {
  /// The [`service.name`](/docs/resource/README.md#service) of the remote
  /// service. SHOULD be equal to the actual `service.name` resource
  /// attribute of the remote service if any.
  ///
  /// Examples: `AuthTokenCache`
  ///
  /// Stability: development
  @Deprecated('Replaced by `service.peer.name`.')
  peerService('peer.service');

  @override
  final String key;

  const Peer(this.key);

  @override
  String toString() => key;
}
