// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `pool`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/pool/)
library;

import '../semantics_base.dart';

/// `pool.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Pool implements OTelSemantic {
  /// Deprecated, use `db.client.connection.pool.name` instead.
  ///
  /// Examples: `myDataSource`
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.pool.name`.')
  poolName('pool.name');

  @override
  final String key;

  const Pool(this.key);

  @override
  String toString() => key;
}
