// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `pprof`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/pprof/)
library;

import '../semantics_base.dart';

/// `pprof.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Pprof implements OTelSemantic {
  /// Provides an indication that multiple symbols map to this location's
  /// address, for example due to identical code folding by the linker. In
  /// that case the line information represents one of the multiple symbols.
  /// This field must be recomputed when the symbolization state of the
  /// profile changes.
  ///
  /// Stability: development
  pprofLocationIsFolded('pprof.location.is_folded'),

  /// Indicates that there are filenames related to this mapping.
  ///
  /// Stability: development
  pprofMappingHasFilenames('pprof.mapping.has_filenames'),

  /// Indicates that there are functions related to this mapping.
  ///
  /// Stability: development
  pprofMappingHasFunctions('pprof.mapping.has_functions'),

  /// Indicates that there are inline frames related to this mapping.
  ///
  /// Stability: development
  pprofMappingHasInlineFrames('pprof.mapping.has_inline_frames'),

  /// Indicates that there are line numbers related to this mapping.
  ///
  /// Stability: development
  pprofMappingHasLineNumbers('pprof.mapping.has_line_numbers'),

  /// Free-form text associated with the profile. This field should not be
  /// used to store any machine-readable information, it is only for
  /// human-friendly content.
  ///
  /// Examples: `["hello world", "bazinga"]`
  ///
  /// Stability: development
  pprofProfileComment('pprof.profile.comment'),

  /// Documentation link for this profile type.
  ///
  /// Examples: `http://pprof.example.com/cpu-profile.html`
  ///
  /// Stability: development
  pprofProfileDocUrl('pprof.profile.doc_url'),

  /// Frames with Function.function_name fully matching the regexp will be
  /// dropped from the samples, along with their successors.
  ///
  /// Examples: `/foobar/`
  ///
  /// Stability: development
  pprofProfileDropFrames('pprof.profile.drop_frames'),

  /// Frames with Function.function_name fully matching the regexp will be
  /// kept, even if it matches drop_frames.
  ///
  /// Examples: `/bazinga/`
  ///
  /// Stability: development
  pprofProfileKeepFrames('pprof.profile.keep_frames'),

  /// Records the pprof's default_sample_type in the original profile. Not
  /// set if the default sample type was missing.
  ///
  /// Examples: `cpu`
  ///
  /// Stability: development
  pprofScopeDefaultSampleType('pprof.scope.default_sample_type'),

  /// Records the indexes of the sample types in the original profile.
  ///
  /// Examples: `[3, 0, 1, 2]`
  ///
  /// Stability: development
  pprofScopeSampleTypeOrder('pprof.scope.sample_type_order');

  @override
  final String key;

  const Pprof(this.key);

  @override
  String toString() => key;
}
