// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `process`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/process/)
library;

import '../semantics_base.dart';

/// `process.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum ProcessAttributes implements OTelSemantic {
  /// Length of the process.command_args array
  ///
  /// Examples: `4`
  ///
  /// Stability: release_candidate
  processArgsCount('process.args_count'),

  /// The command used to launch the process (i.e. the command name). On
  /// Linux based systems, can be set to the zeroth string in
  /// `proc/[pid]/cmdline`. On Windows, can be set to the first parameter
  /// extracted from `GetCommandLineW`.
  ///
  /// Examples: `cmd/otelcol`
  ///
  /// Stability: release_candidate
  processCommand('process.command'),

  /// All the command arguments (including the command/executable itself) as
  /// received by the process. On Linux-based systems (and some other Unixoid
  /// systems supporting procfs), can be set according to the list of
  /// null-delimited strings extracted from `proc/[pid]/cmdline`. For
  /// libc-based executables, this would be the full argv vector passed to
  /// `main`. SHOULD NOT be collected by default unless there is sanitization
  /// that excludes sensitive data.
  ///
  /// Examples: `["cmd/otecol", "--config=config.yaml"]`
  ///
  /// Stability: release_candidate
  processCommandArgs('process.command_args'),

  /// The full command used to launch the process as a single string
  /// representing the full command. On Windows, can be set to the result of
  /// `GetCommandLineW`. Do not set this if you have to assemble it just for
  /// monitoring; use `process.command_args` instead. SHOULD NOT be collected
  /// by default unless there is sanitization that excludes sensitive data.
  ///
  /// Examples: `C:\cmd\otecol --config="my directory\config.yaml"`
  ///
  /// Stability: release_candidate
  processCommandLine('process.command_line'),

  /// Specifies whether the context switches for this data point were
  /// voluntary or involuntary.
  ///
  /// Stability: release_candidate
  processContextSwitchType('process.context_switch.type'),

  /// Deprecated, use `cpu.mode` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `cpu.mode`.')
  processCpuState('process.cpu.state'),

  /// The date and time the process was created, in ISO 8601 format.
  ///
  /// Examples: `2023-11-21T09:25:34.853Z`
  ///
  /// Stability: release_candidate
  processCreationTime('process.creation.time'),

  /// Process environment variables, `<key>` being the environment variable
  /// name, the value being the environment variable value.
  ///
  /// Examples: `ubuntu, /usr/local/bin:/usr/bin`
  ///
  /// Stability: release_candidate
  processEnvironmentVariable('process.environment_variable'),

  /// The GNU build ID as found in the `.note.gnu.build-id` ELF section (hex
  /// string).
  ///
  /// Examples: `c89b11207f6479603b0d49bf291c092c2b719293`
  ///
  /// Stability: release_candidate
  processExecutableBuildIdGnu('process.executable.build_id.gnu'),

  /// The Go build ID as retrieved by `go tool buildid <go executable>`.
  ///
  /// Examples:
  /// `foh3mEXu7BLZjsN9pOwG/kATcXlYVCDEFouRMQed_/WwRFB1hPo9LBkekthSPG/x8hMC8emW2cCjXD0_1aY`
  ///
  /// Stability: release_candidate
  processExecutableBuildIdGo('process.executable.build_id.go'),

  /// Deterministic build ID for executables.
  ///
  /// Examples: `600DCAFE4A110000F2BF38C493F5FB92`
  ///
  /// Stability: release_candidate
  processExecutableBuildIdHtlhash('process.executable.build_id.htlhash'),

  /// "Deprecated, use `process.executable.build_id.htlhash` instead."
  ///
  /// Examples: `600DCAFE4A110000F2BF38C493F5FB92`
  ///
  /// Stability: development
  @Deprecated('Replaced by `process.executable.build_id.htlhash`.')
  processExecutableBuildIdProfiling('process.executable.build_id.profiling'),

  /// The name of the process executable. On Linux based systems, this SHOULD
  /// be set to the base name of the target of `/proc/[pid]/exe`. On Windows,
  /// this SHOULD be set to the base name of `GetProcessImageFileNameW`.
  ///
  /// Examples: `otelcol`
  ///
  /// Stability: release_candidate
  processExecutableName('process.executable.name'),

  /// The full path to the process executable. On Linux based systems, can be
  /// set to the target of `proc/[pid]/exe`. On Windows, can be set to the
  /// result of `GetProcessImageFileNameW`.
  ///
  /// Examples: `/usr/bin/cmd/otelcol`
  ///
  /// Stability: release_candidate
  processExecutablePath('process.executable.path'),

  /// The exit code of the process.
  ///
  /// Examples: `127`
  ///
  /// Stability: release_candidate
  processExitCode('process.exit.code'),

  /// The date and time the process exited, in ISO 8601 format.
  ///
  /// Examples: `2023-11-21T09:26:12.315Z`
  ///
  /// Stability: release_candidate
  processExitTime('process.exit.time'),

  /// The PID of the process's group leader. This is also the process group
  /// ID (PGID) of the process.
  ///
  /// Examples: `23`
  ///
  /// Stability: release_candidate
  processGroupLeaderPid('process.group_leader.pid'),

  /// Whether the process is connected to an interactive shell.
  ///
  /// Stability: release_candidate
  processInteractive('process.interactive'),

  /// The control group associated with the process.
  ///
  /// Examples:
  /// `1:name=systemd:/user.slice/user-1000.slice/session-3.scope, 0::/user.slice/user-1000.slice/user@1000.service/tmux-spawn-0267755b-4639-4a27-90ed-f19f88e53748.scope`
  ///
  /// Stability: release_candidate
  processLinuxCgroup('process.linux.cgroup'),

  /// The username of the user that owns the process.
  ///
  /// Examples: `root`
  ///
  /// Stability: release_candidate
  processOwner('process.owner'),

  /// Deprecated, use `system.paging.fault.type` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `system.paging.fault.type`.')
  processPagingFaultType('process.paging.fault_type'),

  /// Parent Process identifier (PPID).
  ///
  /// Examples: `111`
  ///
  /// Stability: release_candidate
  processParentPid('process.parent_pid'),

  /// Process identifier (PID).
  ///
  /// Examples: `1234`
  ///
  /// Stability: release_candidate
  processPid('process.pid'),

  /// The real user ID (RUID) of the process.
  ///
  /// Examples: `1000`
  ///
  /// Stability: release_candidate
  processRealUserId('process.real_user.id'),

  /// The username of the real user of the process.
  ///
  /// Examples: `operator`
  ///
  /// Stability: release_candidate
  processRealUserName('process.real_user.name'),

  /// An additional description about the runtime of the process, for example
  /// a specific vendor customization of the runtime environment.
  ///
  /// Examples: `Eclipse OpenJ9 Eclipse OpenJ9 VM openj9-0.21.0`
  ///
  /// Stability: release_candidate
  processRuntimeDescription('process.runtime.description'),

  /// The name of the runtime of this process.
  ///
  /// Examples: `OpenJDK Runtime Environment`
  ///
  /// Stability: release_candidate
  processRuntimeName('process.runtime.name'),

  /// The version of the runtime of this process, as returned by the runtime
  /// without modification.
  ///
  /// Examples: `14.0.2`
  ///
  /// Stability: release_candidate
  processRuntimeVersion('process.runtime.version'),

  /// The saved user ID (SUID) of the process.
  ///
  /// Examples: `1002`
  ///
  /// Stability: release_candidate
  processSavedUserId('process.saved_user.id'),

  /// The username of the saved user.
  ///
  /// Examples: `operator`
  ///
  /// Stability: release_candidate
  processSavedUserName('process.saved_user.name'),

  /// The PID of the process's session leader. This is also the session ID
  /// (SID) of the process.
  ///
  /// Examples: `14`
  ///
  /// Stability: release_candidate
  processSessionLeaderPid('process.session_leader.pid'),

  /// The process state, e.g.,
  /// [Linux Process State Codes](https://man7.org/linux/man-pages/man1/ps.1.html#PROCESS_STATE_CODES)
  ///
  /// Examples: `running`
  ///
  /// Stability: release_candidate
  processState('process.state'),

  /// Process title (proctitle)
  ///
  /// Examples: `cat /etc/hostname, xfce4-session, bash`
  ///
  /// Stability: release_candidate
  processTitle('process.title'),

  /// The effective user ID (EUID) of the process.
  ///
  /// Examples: `1001`
  ///
  /// Stability: release_candidate
  processUserId('process.user.id'),

  /// The username of the effective user of the process.
  ///
  /// Examples: `root`
  ///
  /// Stability: release_candidate
  processUserName('process.user.name'),

  /// Virtual process identifier.
  ///
  /// Examples: `12`
  ///
  /// Stability: release_candidate
  processVpid('process.vpid'),

  /// The working directory of the process.
  ///
  /// Examples: `/root`
  ///
  /// Stability: release_candidate
  processWorkingDirectory('process.working_directory');

  @override
  final String key;

  const ProcessAttributes(this.key);

  @override
  String toString() => key;
}

/// Values for `process.context_switch.type`.
///
/// Stability: release_candidate
enum ProcessContextSwitchType implements OTelSemanticValue {
  /// Stability: release_candidate
  voluntary('voluntary'),

  /// Stability: release_candidate
  involuntary('involuntary');

  @override
  final String value;

  const ProcessContextSwitchType(this.value);

  @override
  String toString() => value;
}

/// Values for `process.cpu.state`.
///
/// Stability: development
@Deprecated('Replaced by `cpu.mode`.')
enum ProcessCpuState implements OTelSemanticValue {
  /// Stability: development
  system('system'),

  /// Stability: development
  user('user'),

  /// Stability: development
  wait('wait');

  @override
  final String value;

  const ProcessCpuState(this.value);

  @override
  String toString() => value;
}

/// Values for `process.paging.fault_type`.
///
/// Stability: development
@Deprecated('Replaced by `system.paging.fault.type`.')
enum ProcessPagingFaultType implements OTelSemanticValue {
  /// Stability: development
  major('major'),

  /// Stability: development
  minor('minor');

  @override
  final String value;

  const ProcessPagingFaultType(this.value);

  @override
  String toString() => value;
}

/// Values for `process.state`.
///
/// Stability: release_candidate
enum ProcessState implements OTelSemanticValue {
  /// Stability: release_candidate
  running('running'),

  /// Stability: release_candidate
  sleeping('sleeping'),

  /// Stability: release_candidate
  stopped('stopped'),

  /// Stability: release_candidate
  defunct('defunct');

  @override
  final String value;

  const ProcessState(this.value);

  @override
  String toString() => value;
}
