// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `profile`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/profile/)
library;

import '../semantics_base.dart';

/// `profile.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Profile implements OTelSemantic {
  /// Describes the interpreter or compiler of a single frame.
  ///
  /// Examples: `cpython`
  ///
  /// Stability: development
  profileFrameType('profile.frame.type');

  @override
  final String key;

  const Profile(this.key);

  @override
  String toString() => key;
}

/// Values for `profile.frame.type`.
///
/// Stability: development
enum ProfileFrameType implements OTelSemanticValue {
  /// [.NET](https://wikipedia.org/wiki/.NET)
  ///
  /// Stability: development
  dotnet('dotnet'),

  /// [JVM](https://wikipedia.org/wiki/Java_virtual_machine)
  ///
  /// Stability: development
  jvm('jvm'),

  /// [Kernel](https://wikipedia.org/wiki/Kernel_(operating_system))
  ///
  /// Stability: development
  kernel('kernel'),

  /// Can be one of but not limited to
  /// [C](https://wikipedia.org/wiki/C_(programming_language)),
  /// [C++](https://wikipedia.org/wiki/C%2B%2B),
  /// [Go](https://wikipedia.org/wiki/Go_(programming_language)) or
  /// [Rust](https://wikipedia.org/wiki/Rust_(programming_language)). If
  /// possible, a more precise value MUST be used.
  ///
  /// Stability: development
  native('native'),

  /// [Perl](https://wikipedia.org/wiki/Perl)
  ///
  /// Stability: development
  perl('perl'),

  /// [PHP](https://wikipedia.org/wiki/PHP)
  ///
  /// Stability: development
  php('php'),

  /// [Python](https://wikipedia.org/wiki/Python_(programming_language))
  ///
  /// Stability: development
  cpython('cpython'),

  /// [Ruby](https://wikipedia.org/wiki/Ruby_(programming_language))
  ///
  /// Stability: development
  ruby('ruby'),

  /// [V8JS](https://wikipedia.org/wiki/V8_(JavaScript_engine))
  ///
  /// Stability: development
  v8js('v8js'),

  /// [Erlang](https://en.wikipedia.org/wiki/BEAM_(Erlang_virtual_machine))
  ///
  /// Stability: development
  beam('beam'),

  /// [Go](https://wikipedia.org/wiki/Go_(programming_language)),
  ///
  /// Stability: development
  go('go'),

  /// [Rust](https://wikipedia.org/wiki/Rust_(programming_language))
  ///
  /// Stability: development
  rust('rust'),

  /// [LuaJIT](https://en.wikipedia.org/wiki/LuaJIT)
  ///
  /// Stability: development
  luajit('luajit');

  @override
  final String value;

  const ProfileFrameType(this.value);

  @override
  String toString() => value;
}
