// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `rpc`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/rpc/)
library;

import '../semantics_base.dart';

/// `rpc.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Rpc implements OTelSemantic {
  /// Deprecated, use `rpc.response.status_code` attribute instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `rpc.response.status_code`.')
  rpcConnectRpcErrorCode('rpc.connect_rpc.error_code'),

  /// Deprecated, use `rpc.request.metadata` instead.
  ///
  /// Examples: `["1.2.3.4", "1.2.3.5"]`
  ///
  /// Stability: development
  @Deprecated('Replaced by `rpc.request.metadata`.')
  rpcConnectRpcRequestMetadata('rpc.connect_rpc.request.metadata'),

  /// Deprecated, use `rpc.response.metadata` instead.
  ///
  /// Examples: `["attribute_value"]`
  ///
  /// Stability: development
  @Deprecated('Replaced by `rpc.response.metadata`.')
  rpcConnectRpcResponseMetadata('rpc.connect_rpc.response.metadata'),

  /// Deprecated, use `rpc.request.metadata` instead.
  ///
  /// Examples: `["1.2.3.4", "1.2.3.5"]`
  ///
  /// Stability: development
  @Deprecated('Replaced by `rpc.request.metadata`.')
  rpcGrpcRequestMetadata('rpc.grpc.request.metadata'),

  /// Deprecated, use `rpc.response.metadata` instead.
  ///
  /// Examples: `["attribute_value"]`
  ///
  /// Stability: development
  @Deprecated('Replaced by `rpc.response.metadata`.')
  rpcGrpcResponseMetadata('rpc.grpc.response.metadata'),

  /// Deprecated, use string representation on the `rpc.response.status_code`
  ///  attribute instead.
  ///
  /// Stability: development
  @Deprecated(
      'Use string representation of the gRPC status code on the `rpc.response.status_code` attribute.')
  rpcGrpcStatusCode('rpc.grpc.status_code'),

  /// Deprecated, use string representation on the `rpc.response.status_code`
  ///  attribute instead.
  ///
  /// Examples: `-32700, 100`
  ///
  /// Stability: development
  @Deprecated(
      'Use string representation of the error code on the `rpc.response.status_code` attribute.')
  rpcJsonrpcErrorCode('rpc.jsonrpc.error_code'),

  /// Deprecated, use the span status description when reporting JSON-RPC
  /// spans.
  ///
  /// Examples: `Parse error, User already exists`
  ///
  /// Stability: development
  @Deprecated('Use the span status description when reporting JSON-RPC spans.')
  rpcJsonrpcErrorMessage('rpc.jsonrpc.error_message'),

  /// Deprecated, use `jsonrpc.request.id` instead.
  ///
  /// Examples: `10, request-7, `
  ///
  /// Stability: development
  @Deprecated('Replaced by `jsonrpc.request.id`.')
  rpcJsonrpcRequestId('rpc.jsonrpc.request_id'),

  /// Deprecated, use `jsonrpc.protocol.version` instead.
  ///
  /// Examples: `2.0, 1.0`
  ///
  /// Stability: development
  @Deprecated('Replaced by `jsonrpc.protocol.version`.')
  rpcJsonrpcVersion('rpc.jsonrpc.version'),

  /// Compressed size of the message in bytes.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  rpcMessageCompressedSize('rpc.message.compressed_size'),

  /// MUST be calculated as two different counters starting from `1` one for
  /// sent messages and one for received message.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  rpcMessageId('rpc.message.id'),

  /// Whether this is a received or sent message.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  rpcMessageType('rpc.message.type'),

  /// Uncompressed size of the message in bytes.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  rpcMessageUncompressedSize('rpc.message.uncompressed_size'),

  /// The fully-qualified logical name of the method from the RPC interface
  /// perspective.
  ///
  /// Examples:
  /// `com.example.ExampleService/exampleMethod, EchoService/Echo, _OTHER`
  ///
  /// Stability: release_candidate
  rpcMethod('rpc.method'),

  /// The original name of the method used by the client.
  ///
  /// Examples:
  /// `com.myservice.EchoService/catchAll, com.myservice.EchoService/unknownMethod, InvalidMethod`
  ///
  /// Stability: release_candidate
  rpcMethodOriginal('rpc.method_original'),

  /// RPC request metadata, `<key>` being the normalized RPC metadata key
  /// (lowercase), the value being the metadata values.
  ///
  /// Examples: `["1.2.3.4", "1.2.3.5"]`
  ///
  /// Stability: development
  rpcRequestMetadata('rpc.request.metadata'),

  /// RPC response metadata, `<key>` being the normalized RPC metadata key
  /// (lowercase), the value being the metadata values.
  ///
  /// Examples: `["attribute_value"]`
  ///
  /// Stability: development
  rpcResponseMetadata('rpc.response.metadata'),

  /// Status code of the RPC returned by the RPC server or generated by the
  /// client
  ///
  /// Examples: `OK, DEADLINE_EXCEEDED, -32602`
  ///
  /// Stability: release_candidate
  rpcResponseStatusCode('rpc.response.status_code'),

  /// Deprecated, use fully-qualified `rpc.method` instead.
  ///
  /// Examples: `myservice.EchoService`
  ///
  /// Stability: development
  @Deprecated(
      'Value should be included in `rpc.method` which is expected to be a fully-qualified name.')
  rpcService('rpc.service'),

  /// Deprecated, use `rpc.system.name` attribute instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `rpc.system.name`.')
  rpcSystem('rpc.system'),

  /// The Remote Procedure Call (RPC) system.
  ///
  /// Stability: release_candidate
  rpcSystemName('rpc.system.name');

  @override
  final String key;

  const Rpc(this.key);

  @override
  String toString() => key;
}

/// Values for `rpc.connect_rpc.error_code`.
///
/// Stability: development
@Deprecated('Replaced by `rpc.response.status_code`.')
enum RpcConnectRpcErrorCode implements OTelSemanticValue {
  /// Stability: development
  cancelled('cancelled'),

  /// Stability: development
  unknown('unknown'),

  /// Stability: development
  invalidArgument('invalid_argument'),

  /// Stability: development
  deadlineExceeded('deadline_exceeded'),

  /// Stability: development
  notFound('not_found'),

  /// Stability: development
  alreadyExists('already_exists'),

  /// Stability: development
  permissionDenied('permission_denied'),

  /// Stability: development
  resourceExhausted('resource_exhausted'),

  /// Stability: development
  failedPrecondition('failed_precondition'),

  /// Stability: development
  aborted('aborted'),

  /// Stability: development
  outOfRange('out_of_range'),

  /// Stability: development
  unimplemented('unimplemented'),

  /// Stability: development
  internal('internal'),

  /// Stability: development
  unavailable('unavailable'),

  /// Stability: development
  dataLoss('data_loss'),

  /// Stability: development
  unauthenticated('unauthenticated');

  @override
  final String value;

  const RpcConnectRpcErrorCode(this.value);

  @override
  String toString() => value;
}

/// Values for `rpc.grpc.status_code`.
///
/// Stability: development
@Deprecated(
    'Use string representation of the gRPC status code on the `rpc.response.status_code` attribute.')
enum RpcGrpcStatusCode implements OTelSemanticIntValue {
  /// OK
  ///
  /// Stability: development
  ok(0),

  /// CANCELLED
  ///
  /// Stability: development
  cancelled(1),

  /// UNKNOWN
  ///
  /// Stability: development
  unknown(2),

  /// INVALID_ARGUMENT
  ///
  /// Stability: development
  invalidArgument(3),

  /// DEADLINE_EXCEEDED
  ///
  /// Stability: development
  deadlineExceeded(4),

  /// NOT_FOUND
  ///
  /// Stability: development
  notFound(5),

  /// ALREADY_EXISTS
  ///
  /// Stability: development
  alreadyExists(6),

  /// PERMISSION_DENIED
  ///
  /// Stability: development
  permissionDenied(7),

  /// RESOURCE_EXHAUSTED
  ///
  /// Stability: development
  resourceExhausted(8),

  /// FAILED_PRECONDITION
  ///
  /// Stability: development
  failedPrecondition(9),

  /// ABORTED
  ///
  /// Stability: development
  aborted(10),

  /// OUT_OF_RANGE
  ///
  /// Stability: development
  outOfRange(11),

  /// UNIMPLEMENTED
  ///
  /// Stability: development
  unimplemented(12),

  /// INTERNAL
  ///
  /// Stability: development
  internal(13),

  /// UNAVAILABLE
  ///
  /// Stability: development
  unavailable(14),

  /// DATA_LOSS
  ///
  /// Stability: development
  dataLoss(15),

  /// UNAUTHENTICATED
  ///
  /// Stability: development
  unauthenticated(16);

  @override
  final int value;

  const RpcGrpcStatusCode(this.value);

  @override
  String toString() => value.toString();
}

/// Values for `rpc.message.type`.
///
/// Stability: development
@Deprecated('Deprecated, no replacement at this time.')
enum RpcMessageType implements OTelSemanticValue {
  /// Stability: development
  sent('SENT'),

  /// Stability: development
  received('RECEIVED');

  @override
  final String value;

  const RpcMessageType(this.value);

  @override
  String toString() => value;
}

/// Values for `rpc.system`.
///
/// Stability: development
@Deprecated('Replaced by `rpc.system.name`.')
enum RpcSystem implements OTelSemanticValue {
  /// gRPC
  ///
  /// Stability: development
  grpc('grpc'),

  /// Java RMI
  ///
  /// Stability: development
  javaRmi('java_rmi'),

  /// .NET WCF
  ///
  /// Stability: development
  dotnetWcf('dotnet_wcf'),

  /// Apache Dubbo
  ///
  /// Stability: development
  apacheDubbo('apache_dubbo'),

  /// Connect RPC
  ///
  /// Stability: development
  connectRpc('connect_rpc'),

  /// [ONC RPC (Sun RPC)](https://datatracker.ietf.org/doc/html/rfc5531)
  ///
  /// Stability: development
  oncRpc('onc_rpc'),

  /// JSON-RPC
  ///
  /// Stability: development
  jsonrpc('jsonrpc');

  @override
  final String value;

  const RpcSystem(this.value);

  @override
  String toString() => value;
}

/// Values for `rpc.system.name`.
///
/// Stability: release_candidate
enum RpcSystemName implements OTelSemanticValue {
  /// [gRPC](https://grpc.io/)
  ///
  /// Stability: release_candidate
  grpc('grpc'),

  /// [Apache Dubbo](https://dubbo.apache.org/)
  ///
  /// Stability: release_candidate
  dubbo('dubbo'),

  /// [Connect RPC](https://connectrpc.com/)
  ///
  /// Stability: development
  connectrpc('connectrpc'),

  /// [JSON-RPC](https://www.jsonrpc.org/)
  ///
  /// Stability: development
  jsonrpc('jsonrpc');

  @override
  final String value;

  const RpcSystemName(this.value);

  @override
  String toString() => value;
}
