// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `security_rule`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/security-rule/)
library;

import '../semantics_base.dart';

/// `security_rule.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum SecurityRule implements OTelSemantic {
  /// A categorization value keyword used by the entity using the rule for
  /// detection of this event
  ///
  /// Examples: `Attempted Information Leak`
  ///
  /// Stability: development
  securityRuleCategory('security_rule.category'),

  /// The description of the rule generating the event.
  ///
  /// Examples: `Block requests to public DNS over HTTPS / TLS protocols`
  ///
  /// Stability: development
  securityRuleDescription('security_rule.description'),

  /// Name of the license under which the rule used to generate this event is
  /// made available.
  ///
  /// Examples: `Apache 2.0`
  ///
  /// Stability: development
  securityRuleLicense('security_rule.license'),

  /// The name of the rule or signature generating the event.
  ///
  /// Examples: `BLOCK_DNS_over_TLS`
  ///
  /// Stability: development
  securityRuleName('security_rule.name'),

  /// Reference URL to additional information about the rule used to generate
  /// this event.
  ///
  /// Examples: `https://en.wikipedia.org/wiki/DNS_over_TLS`
  ///
  /// Stability: development
  securityRuleReference('security_rule.reference'),

  /// Name of the ruleset, policy, group, or parent category in which the
  /// rule used to generate this event is a member.
  ///
  /// Examples: `Standard_Protocol_Filters`
  ///
  /// Stability: development
  securityRuleRulesetName('security_rule.ruleset.name'),

  /// A rule ID that is unique within the scope of a set or group of agents,
  /// observers, or other entities using the rule for detection of this
  /// event.
  ///
  /// Examples: `550e8400-e29b-41d4-a716-446655440000, 1100110011`
  ///
  /// Stability: development
  securityRuleUuid('security_rule.uuid'),

  /// The version / revision of the rule being used for analysis.
  ///
  /// Examples: `1.0.0`
  ///
  /// Stability: development
  securityRuleVersion('security_rule.version');

  @override
  final String key;

  const SecurityRule(this.key);

  @override
  String toString() => key;
}
