// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0
// (registry v1.44.0 @ e10a9308).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `server`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/server/)
library;

import '../semantics_base.dart';

/// `server.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Server implements OTelSemantic {
  /// Server domain name if available without reverse DNS lookup; otherwise,
  /// IP address or UNIX domain socket name.
  ///
  /// Examples: `example.com, 10.1.2.80, /tmp/my.sock`
  serverAddress('server.address'),

  /// Server port number.
  ///
  /// Examples: `80, 8080, 443`
  serverPort('server.port');

  @override
  final String key;

  const Server(this.key);

  @override
  String toString() => key;
}
