// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `service`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/service/)
library;

import '../semantics_base.dart';

/// `service.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Service implements OTelSemantic {
  /// The operational criticality of the service.
  ///
  /// Examples: `critical, high, medium, low`
  ///
  /// Stability: alpha
  serviceCriticality('service.criticality'),

  /// The string ID of the service instance.
  ///
  /// Examples: `627cc493-f310-47de-96bd-71410b7dec09`
  serviceInstanceId('service.instance.id'),

  /// Logical name of the service.
  ///
  /// Examples: `shoppingcart`
  serviceName('service.name'),

  /// A namespace for `service.name`.
  ///
  /// Examples: `Shop`
  serviceNamespace('service.namespace'),

  /// Logical name of the service on the other side of the connection. SHOULD
  /// be equal to the actual
  /// [`service.name`](/docs/resource/README.md#service) resource attribute
  /// of the remote service if any.
  ///
  /// Examples: `shoppingcart`
  ///
  /// Stability: development
  servicePeerName('service.peer.name'),

  /// Logical namespace of the service on the other side of the connection.
  /// SHOULD be equal to the actual
  /// [`service.namespace`](/docs/resource/README.md#service) resource
  /// attribute of the remote service if any.
  ///
  /// Examples: `Shop`
  ///
  /// Stability: development
  servicePeerNamespace('service.peer.namespace'),

  /// The version string of the service component. The format is not defined
  /// by these conventions.
  ///
  /// Examples: `2.0.0, a01dbef8a`
  serviceVersion('service.version');

  @override
  final String key;

  const Service(this.key);

  @override
  String toString() => key;
}

/// Values for `service.criticality`.
///
/// Stability: alpha
enum ServiceCriticality implements OTelSemanticValue {
  /// Service is business-critical; downtime directly impacts revenue, user
  /// experience, or core functionality.
  ///
  /// Stability: alpha
  critical('critical'),

  /// Service is important but has degradation tolerance or fallback
  /// mechanisms.
  ///
  /// Stability: alpha
  high('high'),

  /// Service provides supplementary functionality; degradation has limited
  /// user impact.
  ///
  /// Stability: alpha
  medium('medium'),

  /// Service is non-essential to core operations; used for background tasks
  /// or internal tools.
  ///
  /// Stability: alpha
  low('low');

  @override
  final String value;

  const ServiceCriticality(this.value);

  @override
  String toString() => value;
}
