// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `session`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/session/)
library;

import '../semantics_base.dart';

/// `session.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Session implements OTelSemantic {
  /// A unique id to identify a session.
  ///
  /// Examples: `00112233-4455-6677-8899-aabbccddeeff`
  ///
  /// Stability: development
  sessionId('session.id'),

  /// The previous `session.id` for this user, when known.
  ///
  /// Examples: `00112233-4455-6677-8899-aabbccddeeff`
  ///
  /// Stability: development
  sessionPreviousId('session.previous_id');

  @override
  final String key;

  const Session(this.key);

  @override
  String toString() => key;
}
