// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `telemetry`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/telemetry/)
library;

import '../semantics_base.dart';

/// `telemetry.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Telemetry implements OTelSemantic {
  /// The name of the auto instrumentation agent or distribution, if used.
  ///
  /// Examples: `parts-unlimited-java`
  telemetryDistroName('telemetry.distro.name'),

  /// The version string of the auto instrumentation agent or distribution,
  /// if used.
  ///
  /// Examples: `1.2.3`
  telemetryDistroVersion('telemetry.distro.version'),

  /// The language of the telemetry SDK.
  telemetrySdkLanguage('telemetry.sdk.language'),

  /// The name of the telemetry SDK as defined above.
  ///
  /// Examples: `opentelemetry`
  telemetrySdkName('telemetry.sdk.name'),

  /// The version string of the telemetry SDK.
  ///
  /// Examples: `1.2.3`
  telemetrySdkVersion('telemetry.sdk.version');

  @override
  final String key;

  const Telemetry(this.key);

  @override
  String toString() => key;
}

/// Values for `telemetry.sdk.language`.
enum TelemetrySdkLanguage implements OTelSemanticValue {
  cpp('cpp'),
  dotnet('dotnet'),
  erlang('erlang'),
  go('go'),
  java('java'),
  kotlin('kotlin'),
  nodejs('nodejs'),
  php('php'),
  python('python'),
  ruby('ruby'),
  rust('rust'),
  swift('swift'),
  webjs('webjs');

  @override
  final String value;

  const TelemetrySdkLanguage(this.value);

  @override
  String toString() => value;
}
