// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `thread`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/thread/)
library;

import '../semantics_base.dart';

/// `thread.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Thread implements OTelSemantic {
  /// Current "managed" thread ID (as opposed to OS thread ID).
  ///
  /// Examples: `42`
  ///
  /// Stability: development
  threadId('thread.id'),

  /// Current thread name.
  ///
  /// Examples: `main`
  ///
  /// Stability: development
  threadName('thread.name');

  @override
  final String key;

  const Thread(this.key);

  @override
  String toString() => key;
}
