// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `url`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/url/)
library;

import '../semantics_base.dart';

/// `url.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Url implements OTelSemantic {
  /// Domain extracted from the `url.full`, such as "opentelemetry.io".
  ///
  /// Examples:
  /// `www.foo.bar, opentelemetry.io, 3.12.167.2, [1080:0:0:0:8:800:200C:417A]`
  ///
  /// Stability: development
  urlDomain('url.domain'),

  /// The file extension extracted from the `url.full`, excluding the leading
  /// dot.
  ///
  /// Examples: `png, gz`
  ///
  /// Stability: development
  urlExtension('url.extension'),

  /// The [URI fragment](https://www.rfc-editor.org/rfc/rfc3986#section-3.5)
  /// component
  ///
  /// Examples: `SemConv`
  urlFragment('url.fragment'),

  /// Absolute URL describing a network resource according to
  /// [RFC3986](https://www.rfc-editor.org/rfc/rfc3986)
  ///
  /// Examples:
  /// `https://www.foo.bar/search?q=OpenTelemetry#SemConv, //localhost`
  urlFull('url.full'),

  /// Unmodified original URL as seen in the event source.
  ///
  /// Examples:
  /// `https://www.foo.bar/search?q=OpenTelemetry#SemConv, search?q=OpenTelemetry`
  ///
  /// Stability: development
  urlOriginal('url.original'),

  /// The [URI path](https://www.rfc-editor.org/rfc/rfc3986#section-3.3)
  /// component
  ///
  /// Examples: `/search`
  urlPath('url.path'),

  /// Port extracted from the `url.full`
  ///
  /// Examples: `443`
  ///
  /// Stability: development
  urlPort('url.port'),

  /// The [URI query](https://www.rfc-editor.org/rfc/rfc3986#section-3.4)
  /// component
  ///
  /// Examples: `q=OpenTelemetry`
  urlQuery('url.query'),

  /// The highest registered url domain, stripped of the subdomain.
  ///
  /// Examples: `example.com, foo.co.uk`
  ///
  /// Stability: development
  urlRegisteredDomain('url.registered_domain'),

  /// The [URI scheme](https://www.rfc-editor.org/rfc/rfc3986#section-3.1)
  /// component identifying the used protocol.
  ///
  /// Examples: `https, ftp, telnet`
  urlScheme('url.scheme'),

  /// The subdomain portion of a fully qualified domain name includes all of
  /// the names except the host name under the registered_domain. In a
  /// partially qualified domain, or if the qualification level of the full
  /// name cannot be determined, subdomain contains all of the names below
  /// the registered domain.
  ///
  /// Examples: `east, sub2.sub1`
  ///
  /// Stability: development
  urlSubdomain('url.subdomain'),

  /// The low-cardinality template of an
  /// [absolute path reference](https://www.rfc-editor.org/rfc/rfc3986#section-4.2)
  /// .
  ///
  /// Examples: `/users/{id}, /users/:id, /users?id={id}`
  ///
  /// Stability: development
  urlTemplate('url.template'),

  /// The effective top level domain (eTLD), also known as the domain suffix,
  /// is the last part of the domain name. For example, the top level domain
  /// for example.com is `com`.
  ///
  /// Examples: `com, co.uk`
  ///
  /// Stability: development
  urlTopLevelDomain('url.top_level_domain');

  @override
  final String key;

  const Url(this.key);

  @override
  String toString() => key;
}
