// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `user`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/user/)
library;

import '../semantics_base.dart';

/// `user.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum User implements OTelSemantic {
  /// User email address.
  ///
  /// Examples: `a.einstein@example.com`
  ///
  /// Stability: development
  userEmail('user.email'),

  /// User's full name
  ///
  /// Examples: `Albert Einstein`
  ///
  /// Stability: development
  userFullName('user.full_name'),

  /// Unique user hash to correlate information for a user in anonymized
  /// form.
  ///
  /// Examples: `364fc68eaf4c8acec74a4e52d7d1feaa`
  ///
  /// Stability: development
  userHash('user.hash'),

  /// Unique identifier of the user.
  ///
  /// Examples: `S-1-5-21-202424912787-2692429404-2351956786-1000`
  ///
  /// Stability: development
  userId('user.id'),

  /// Short name or login/username of the user.
  ///
  /// Examples: `a.einstein`
  ///
  /// Stability: development
  userName('user.name'),

  /// Array of user roles at the time of the event.
  ///
  /// Examples: `["admin", "reporting_user"]`
  ///
  /// Stability: development
  userRoles('user.roles');

  @override
  final String key;

  const User(this.key);

  @override
  String toString() => key;
}
