// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `user_agent`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/user-agent/)
library;

import '../semantics_base.dart';

/// `user_agent.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum UserAgent implements OTelSemantic {
  /// Name of the user-agent extracted from original. Usually refers to the
  /// browser's name.
  ///
  /// Examples: `Safari, YourApp`
  ///
  /// Stability: development
  userAgentName('user_agent.name'),

  /// Value of the
  /// [HTTP User-Agent](https://www.rfc-editor.org/rfc/rfc9110.html#field.user-agent)
  ///  header sent by the client.
  ///
  /// Examples:
  /// `CERN-LineMode/2.15 libwww/2.17b3, Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1, YourApp/1.0.0 grpc-java-okhttp/1.27.2`
  userAgentOriginal('user_agent.original'),

  /// Human readable operating system name.
  ///
  /// Examples: `iOS, Android, Ubuntu`
  ///
  /// Stability: development
  userAgentOsName('user_agent.os.name'),

  /// The version string of the operating system as defined in
  /// [Version Attributes](/docs/resource/README.md#version-attributes).
  ///
  /// Examples: `14.2.1, 18.04.1`
  ///
  /// Stability: development
  userAgentOsVersion('user_agent.os.version'),

  /// Specifies the category of synthetic traffic, such as tests or bots.
  ///
  /// Stability: development
  userAgentSyntheticType('user_agent.synthetic.type'),

  /// Version of the user-agent extracted from original. Usually refers to
  /// the browser's version
  ///
  /// Examples: `14.1.2, 1.0.0`
  ///
  /// Stability: development
  userAgentVersion('user_agent.version');

  @override
  final String key;

  const UserAgent(this.key);

  @override
  String toString() => key;
}

/// Values for `user_agent.synthetic.type`.
///
/// Stability: development
enum UserAgentSyntheticType implements OTelSemanticValue {
  /// Bot source.
  ///
  /// Stability: development
  bot('bot'),

  /// Synthetic test source.
  ///
  /// Stability: development
  test('test');

  @override
  final String value;

  const UserAgentSyntheticType(this.value);

  @override
  String toString() => value;
}
