// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `vcs`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/vcs/)
library;

import '../semantics_base.dart';

/// `vcs.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Vcs implements OTelSemantic {
  /// The ID of the change (pull request/merge request/changelist) if
  /// applicable. This is usually a unique (within repository) identifier
  /// generated by the VCS system.
  ///
  /// Examples: `123`
  ///
  /// Stability: release_candidate
  vcsChangeId('vcs.change.id'),

  /// The state of the change (pull request/merge request/changelist).
  ///
  /// Examples: `open, closed, merged`
  ///
  /// Stability: release_candidate
  vcsChangeState('vcs.change.state'),

  /// The human readable title of the change (pull request/merge
  /// request/changelist). This title is often a brief summary of the change
  /// and may get merged in to a ref as the commit summary.
  ///
  /// Examples:
  /// `Fixes broken thing, feat: add my new feature, [chore] update dependency`
  ///
  /// Stability: release_candidate
  vcsChangeTitle('vcs.change.title'),

  /// The type of line change being measured on a branch or change.
  ///
  /// Examples: `added, removed`
  ///
  /// Stability: release_candidate
  vcsLineChangeType('vcs.line_change.type'),

  /// The group owner within the version control system.
  ///
  /// Examples: `my-org, myteam, business-unit`
  ///
  /// Stability: release_candidate
  vcsOwnerName('vcs.owner.name'),

  /// The name of the version control system provider.
  ///
  /// Examples: `github, gitlab, gitea, bitbucket`
  ///
  /// Stability: release_candidate
  vcsProviderName('vcs.provider.name'),

  /// The name of the
  /// [reference](https://git-scm.com/docs/gitglossary#def_ref) such as
  /// **branch** or **tag** in the repository.
  ///
  /// Examples: `my-feature-branch, tag-1-test`
  ///
  /// Stability: release_candidate
  vcsRefBaseName('vcs.ref.base.name'),

  /// The revision, literally
  /// [revised version](https://www.merriam-webster.com/dictionary/revision)
  /// , The revision most often refers to a commit object in Git, or a
  /// revision number in SVN.
  ///
  /// Examples:
  /// `9d59409acf479dfa0df1aa568182e43e43df8bbe28d60fcf2bc52e30068802cc, main, 123, HEAD`
  ///
  /// Stability: release_candidate
  vcsRefBaseRevision('vcs.ref.base.revision'),

  /// The type of the
  /// [reference](https://git-scm.com/docs/gitglossary#def_ref) in the
  /// repository.
  ///
  /// Examples: `branch, tag`
  ///
  /// Stability: release_candidate
  vcsRefBaseType('vcs.ref.base.type'),

  /// The name of the
  /// [reference](https://git-scm.com/docs/gitglossary#def_ref) such as
  /// **branch** or **tag** in the repository.
  ///
  /// Examples: `my-feature-branch, tag-1-test`
  ///
  /// Stability: release_candidate
  vcsRefHeadName('vcs.ref.head.name'),

  /// The revision, literally
  /// [revised version](https://www.merriam-webster.com/dictionary/revision)
  /// , The revision most often refers to a commit object in Git, or a
  /// revision number in SVN.
  ///
  /// Examples:
  /// `9d59409acf479dfa0df1aa568182e43e43df8bbe28d60fcf2bc52e30068802cc, main, 123, HEAD`
  ///
  /// Stability: release_candidate
  vcsRefHeadRevision('vcs.ref.head.revision'),

  /// The type of the
  /// [reference](https://git-scm.com/docs/gitglossary#def_ref) in the
  /// repository.
  ///
  /// Examples: `branch, tag`
  ///
  /// Stability: release_candidate
  vcsRefHeadType('vcs.ref.head.type'),

  /// The type of the
  /// [reference](https://git-scm.com/docs/gitglossary#def_ref) in the
  /// repository.
  ///
  /// Examples: `branch, tag`
  ///
  /// Stability: release_candidate
  vcsRefType('vcs.ref.type'),

  /// Deprecated, use `vcs.change.id` instead.
  ///
  /// Examples: `123`
  ///
  /// Stability: development
  @Deprecated('Replaced by `vcs.change.id`.')
  vcsRepositoryChangeId('vcs.repository.change.id'),

  /// Deprecated, use `vcs.change.title` instead.
  ///
  /// Examples:
  /// `Fixes broken thing, feat: add my new feature, [chore] update dependency`
  ///
  /// Stability: development
  @Deprecated('Replaced by `vcs.change.title`.')
  vcsRepositoryChangeTitle('vcs.repository.change.title'),

  /// The human readable name of the repository. It SHOULD NOT include any
  /// additional identifier like Group/SubGroup in GitLab or organization in
  /// GitHub.
  ///
  /// Examples: `semantic-conventions, my-cool-repo`
  ///
  /// Stability: release_candidate
  vcsRepositoryName('vcs.repository.name'),

  /// Deprecated, use `vcs.ref.head.name` instead.
  ///
  /// Examples: `my-feature-branch, tag-1-test`
  ///
  /// Stability: development
  @Deprecated('Replaced by `vcs.ref.head.name`.')
  vcsRepositoryRefName('vcs.repository.ref.name'),

  /// Deprecated, use `vcs.ref.head.revision` instead.
  ///
  /// Examples:
  /// `9d59409acf479dfa0df1aa568182e43e43df8bbe28d60fcf2bc52e30068802cc, main, 123, HEAD`
  ///
  /// Stability: development
  @Deprecated('Replaced by `vcs.ref.head.revision`.')
  vcsRepositoryRefRevision('vcs.repository.ref.revision'),

  /// Deprecated, use `vcs.ref.head.type` instead.
  ///
  /// Examples: `branch, tag`
  ///
  /// Stability: development
  @Deprecated('Replaced by `vcs.ref.head.type`.')
  vcsRepositoryRefType('vcs.repository.ref.type'),

  /// The
  /// [canonical URL](https://support.google.com/webmasters/answer/10347851)
  /// of the repository providing the complete HTTP(S) address in order to
  /// locate and identify the repository through a browser.
  ///
  /// Examples:
  /// `https://github.com/opentelemetry/open-telemetry-collector-contrib, https://gitlab.com/my-org/my-project/my-projects-project/repo`
  ///
  /// Stability: release_candidate
  vcsRepositoryUrlFull('vcs.repository.url.full'),

  /// The type of revision comparison.
  ///
  /// Examples: `ahead, behind`
  ///
  /// Stability: release_candidate
  vcsRevisionDeltaDirection('vcs.revision_delta.direction');

  @override
  final String key;

  const Vcs(this.key);

  @override
  String toString() => key;
}

/// Values for `vcs.change.state`.
///
/// Stability: release_candidate
enum VcsChangeState implements OTelSemanticValue {
  /// Open means the change is currently active and under review. It hasn't
  /// been merged into the target branch yet, and it's still possible to make
  /// changes or add comments.
  ///
  /// Stability: release_candidate
  open('open'),

  /// WIP (work-in-progress, draft) means the change is still in progress and
  /// not yet ready for a full review. It might still undergo significant
  /// changes.
  ///
  /// Stability: release_candidate
  wip('wip'),

  /// Closed means the merge request has been closed without merging. This
  /// can happen for various reasons, such as the changes being deemed
  /// unnecessary, the issue being resolved in another way, or the author
  /// deciding to withdraw the request.
  ///
  /// Stability: release_candidate
  closed('closed'),

  /// Merged indicates that the change has been successfully integrated into
  /// the target codebase.
  ///
  /// Stability: release_candidate
  merged('merged');

  @override
  final String value;

  const VcsChangeState(this.value);

  @override
  String toString() => value;
}

/// Values for `vcs.line_change.type`.
///
/// Stability: release_candidate
enum VcsLineChangeType implements OTelSemanticValue {
  /// How many lines were added.
  ///
  /// Stability: release_candidate
  added('added'),

  /// How many lines were removed.
  ///
  /// Stability: release_candidate
  removed('removed');

  @override
  final String value;

  const VcsLineChangeType(this.value);

  @override
  String toString() => value;
}

/// Values for `vcs.provider.name`.
///
/// Stability: release_candidate
enum VcsProviderName implements OTelSemanticValue {
  /// [GitHub](https://github.com)
  ///
  /// Stability: release_candidate
  github('github'),

  /// [GitLab](https://gitlab.com)
  ///
  /// Stability: release_candidate
  gitlab('gitlab'),

  /// Deprecated, use `gitea` instead.
  ///
  /// Stability: release_candidate
  @Deprecated('Replaced by `gitea`.')
  gittea('gittea'),

  /// [Gitea](https://gitea.io)
  ///
  /// Stability: release_candidate
  gitea('gitea'),

  /// [Bitbucket](https://bitbucket.org)
  ///
  /// Stability: release_candidate
  bitbucket('bitbucket');

  @override
  final String value;

  const VcsProviderName(this.value);

  @override
  String toString() => value;
}

/// Values for `vcs.ref.base.type`.
///
/// Stability: release_candidate
enum VcsRefBaseType implements OTelSemanticValue {
  ///
  /// [branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)
  ///
  /// Stability: release_candidate
  branch('branch'),

  ///
  /// [tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)
  ///
  /// Stability: release_candidate
  tag('tag');

  @override
  final String value;

  const VcsRefBaseType(this.value);

  @override
  String toString() => value;
}

/// Values for `vcs.ref.head.type`.
///
/// Stability: release_candidate
enum VcsRefHeadType implements OTelSemanticValue {
  ///
  /// [branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)
  ///
  /// Stability: release_candidate
  branch('branch'),

  ///
  /// [tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)
  ///
  /// Stability: release_candidate
  tag('tag');

  @override
  final String value;

  const VcsRefHeadType(this.value);

  @override
  String toString() => value;
}

/// Values for `vcs.ref.type`.
///
/// Stability: release_candidate
enum VcsRefType implements OTelSemanticValue {
  ///
  /// [branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)
  ///
  /// Stability: release_candidate
  branch('branch'),

  ///
  /// [tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)
  ///
  /// Stability: release_candidate
  tag('tag');

  @override
  final String value;

  const VcsRefType(this.value);

  @override
  String toString() => value;
}

/// Values for `vcs.repository.ref.type`.
///
/// Stability: development
@Deprecated('Replaced by `vcs.ref.head.type`.')
enum VcsRepositoryRefType implements OTelSemanticValue {
  ///
  /// [branch](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch)
  ///
  /// Stability: development
  branch('branch'),

  ///
  /// [tag](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag)
  ///
  /// Stability: development
  tag('tag');

  @override
  final String value;

  const VcsRepositoryRefType(this.value);

  @override
  String toString() => value;
}

/// Values for `vcs.revision_delta.direction`.
///
/// Stability: release_candidate
enum VcsRevisionDeltaDirection implements OTelSemanticValue {
  /// How many revisions the change is behind the target ref.
  ///
  /// Stability: release_candidate
  behind('behind'),

  /// How many revisions the change is ahead of the target ref.
  ///
  /// Stability: release_candidate
  ahead('ahead');

  @override
  final String value;

  const VcsRevisionDeltaDirection(this.value);

  @override
  String toString() => value;
}
