// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `webengine`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/webengine/)
library;

import '../semantics_base.dart';

/// `webengine.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Webengine implements OTelSemantic {
  /// Additional description of the web engine (e.g. detailed version and
  /// edition information).
  ///
  /// Examples:
  /// `WildFly Full 21.0.0.Final (WildFly Core 13.0.1.Final) - 2.2.2.Final`
  ///
  /// Stability: development
  webengineDescription('webengine.description'),

  /// The name of the web engine.
  ///
  /// Examples: `WildFly`
  ///
  /// Stability: development
  webengineName('webengine.name'),

  /// The version of the web engine.
  ///
  /// Examples: `21.0.0`
  ///
  /// Stability: development
  webengineVersion('webengine.version');

  @override
  final String key;

  const Webengine(this.key);

  @override
  String toString() => key;
}
