// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention attributes for the `zos`
/// registry namespace.
///
/// [Spec](https://opentelemetry.io/docs/specs/semconv/registry/attributes/zos/)
library;

import '../semantics_base.dart';

/// `zos.*` attribute keys from the OpenTelemetry
/// semantic-conventions attribute registry.
enum Zos implements OTelSemantic {
  /// The System Management Facility (SMF) Identifier uniquely identified a
  /// z/OS system within a SYSPLEX or mainframe environment and is used for
  /// system and performance analysis.
  ///
  /// Examples: `SYS1`
  ///
  /// Stability: development
  zosSmfId('zos.smf.id'),

  /// The name of the SYSPLEX to which the z/OS system belongs too.
  ///
  /// Examples: `SYSPLEX1`
  ///
  /// Stability: development
  zosSysplexName('zos.sysplex.name');

  @override
  final String key;

  const Zos(this.key);

  @override
  String toString() => key;
}
