// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `aspnetcore`
/// namespace.
library;

import '../../semantics_base.dart';

/// `aspnetcore.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum AspnetcoreMetric implements OTelMetric {
  /// The authentication duration for a request.
  ///
  /// Stability: development
  aspnetcoreAuthenticationAuthenticateDuration(
      'aspnetcore.authentication.authenticate.duration',
      SemanticInstrument.histogram,
      's'),

  /// The total number of times a scheme is challenged.
  ///
  /// Stability: development
  aspnetcoreAuthenticationChallenges('aspnetcore.authentication.challenges',
      SemanticInstrument.counter, '{challenge}'),

  /// The total number of times an authenticated user attempts to access a
  /// resource they are not permitted to access.
  ///
  /// Stability: development
  aspnetcoreAuthenticationForbids('aspnetcore.authentication.forbids',
      SemanticInstrument.counter, '{forbid}'),

  /// The total number of times a principal is signed in with a scheme.
  ///
  /// Stability: development
  aspnetcoreAuthenticationSignIns('aspnetcore.authentication.sign_ins',
      SemanticInstrument.counter, '{sign_in}'),

  /// The total number of times a principal is signed out with a scheme.
  ///
  /// Stability: development
  aspnetcoreAuthenticationSignOuts('aspnetcore.authentication.sign_outs',
      SemanticInstrument.counter, '{sign_out}'),

  /// The total number of authorization attempts.
  ///
  /// Stability: development
  aspnetcoreAuthorizationAttempts('aspnetcore.authorization.attempts',
      SemanticInstrument.counter, '{attempt}'),

  /// Number of exceptions caught by exception handling middleware.
  aspnetcoreDiagnosticsExceptions('aspnetcore.diagnostics.exceptions',
      SemanticInstrument.counter, '{exception}'),

  /// The duration of authenticate attempts. The authenticate metrics is
  /// recorded by sign in methods such as PasswordSignInAsync and
  /// TwoFactorSignInAsync.
  ///
  /// Stability: development
  aspnetcoreIdentitySignInAuthenticateDuration(
      'aspnetcore.identity.sign_in.authenticate.duration',
      SemanticInstrument.histogram,
      's'),

  /// The total number of check password attempts. Checks that the account is
  /// in a state that can log in and that the password is valid using the
  /// UserManager.CheckPasswordAsync method.
  ///
  /// Stability: development
  aspnetcoreIdentitySignInCheckPasswordAttempts(
      'aspnetcore.identity.sign_in.check_password_attempts',
      SemanticInstrument.counter,
      '{attempt}'),

  /// The total number of calls to sign in user principals.
  ///
  /// Stability: development
  aspnetcoreIdentitySignInSignIns('aspnetcore.identity.sign_in.sign_ins',
      SemanticInstrument.counter, '{sign_in}'),

  /// The total number of calls to sign out user principals.
  ///
  /// Stability: development
  aspnetcoreIdentitySignInSignOuts('aspnetcore.identity.sign_in.sign_outs',
      SemanticInstrument.counter, '{sign_out}'),

  /// The total number of two factor clients forgotten.
  ///
  /// Stability: development
  aspnetcoreIdentitySignInTwoFactorClientsForgotten(
      'aspnetcore.identity.sign_in.two_factor_clients_forgotten',
      SemanticInstrument.counter,
      '{client}'),

  /// The total number of two factor clients remembered.
  ///
  /// Stability: development
  aspnetcoreIdentitySignInTwoFactorClientsRemembered(
      'aspnetcore.identity.sign_in.two_factor_clients_remembered',
      SemanticInstrument.counter,
      '{client}'),

  /// The number of check password attempts. Only checks whether the password
  /// is valid and not whether the user account is in a state that can log
  /// in.
  ///
  /// Stability: development
  aspnetcoreIdentityUserCheckPasswordAttempts(
      'aspnetcore.identity.user.check_password_attempts',
      SemanticInstrument.counter,
      '{attempt}'),

  /// The duration of user creation operations.
  ///
  /// Stability: development
  aspnetcoreIdentityUserCreateDuration(
      'aspnetcore.identity.user.create.duration',
      SemanticInstrument.histogram,
      's'),

  /// The duration of user deletion operations.
  ///
  /// Stability: development
  aspnetcoreIdentityUserDeleteDuration(
      'aspnetcore.identity.user.delete.duration',
      SemanticInstrument.histogram,
      's'),

  /// The total number of token generations.
  ///
  /// Stability: development
  aspnetcoreIdentityUserGeneratedTokens(
      'aspnetcore.identity.user.generated_tokens',
      SemanticInstrument.counter,
      '{count}'),

  /// The duration of user update operations.
  ///
  /// Stability: development
  aspnetcoreIdentityUserUpdateDuration(
      'aspnetcore.identity.user.update.duration',
      SemanticInstrument.histogram,
      's'),

  /// The total number of token verification attempts.
  ///
  /// Stability: development
  aspnetcoreIdentityUserVerifyTokenAttempts(
      'aspnetcore.identity.user.verify_token_attempts',
      SemanticInstrument.counter,
      '{attempt}'),

  /// Total number of bytes allocated by the memory pool. Allocation occurs
  /// when a memory rental request exceeds the available pooled memory.
  ///
  /// Stability: development
  aspnetcoreMemoryPoolAllocated(
      'aspnetcore.memory_pool.allocated', SemanticInstrument.counter, 'By'),

  /// Total number of bytes evicted from the memory pool. Eviction occurs
  /// when idle pooled memory is reclaimed.
  ///
  /// Stability: development
  aspnetcoreMemoryPoolEvicted(
      'aspnetcore.memory_pool.evicted', SemanticInstrument.counter, 'By'),

  /// Number of bytes currently pooled and available for reuse.
  ///
  /// Stability: development
  aspnetcoreMemoryPoolPooled(
      'aspnetcore.memory_pool.pooled', SemanticInstrument.upDownCounter, 'By'),

  /// Total number of bytes rented from the memory pool.
  ///
  /// Stability: development
  aspnetcoreMemoryPoolRented(
      'aspnetcore.memory_pool.rented', SemanticInstrument.counter, 'By'),

  /// Number of requests that are currently active on the server that hold a
  /// rate limiting lease.
  aspnetcoreRateLimitingActiveRequestLeases(
      'aspnetcore.rate_limiting.active_request_leases',
      SemanticInstrument.upDownCounter,
      '{request}'),

  /// Number of requests that are currently queued, waiting to acquire a rate
  /// limiting lease.
  aspnetcoreRateLimitingQueuedRequests(
      'aspnetcore.rate_limiting.queued_requests',
      SemanticInstrument.upDownCounter,
      '{request}'),

  /// The time the request spent in a queue waiting to acquire a rate
  /// limiting lease.
  aspnetcoreRateLimitingRequestTimeInQueue(
      'aspnetcore.rate_limiting.request.time_in_queue',
      SemanticInstrument.histogram,
      's'),

  /// The duration of rate limiting lease held by requests on the server.
  aspnetcoreRateLimitingRequestLeaseDuration(
      'aspnetcore.rate_limiting.request_lease.duration',
      SemanticInstrument.histogram,
      's'),

  /// Number of requests that tried to acquire a rate limiting lease.
  aspnetcoreRateLimitingRequests('aspnetcore.rate_limiting.requests',
      SemanticInstrument.counter, '{request}'),

  /// Number of requests that were attempted to be matched to an endpoint.
  aspnetcoreRoutingMatchAttempts('aspnetcore.routing.match_attempts',
      SemanticInstrument.counter, '{match_attempt}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const AspnetcoreMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
