// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `azure`
/// namespace.
library;

import '../../semantics_base.dart';

/// `azure.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum AzureMetric implements OTelMetric {
  /// Number of active client instances.
  ///
  /// Stability: development
  azureCosmosdbClientActiveInstanceCount(
      'azure.cosmosdb.client.active_instance.count',
      SemanticInstrument.upDownCounter,
      '{instance}'),

  ///
  /// [Request units](https://learn.microsoft.com/azure/cosmos-db/request-units)
  ///  consumed by the operation.
  ///
  /// Stability: development
  azureCosmosdbClientOperationRequestCharge(
      'azure.cosmosdb.client.operation.request_charge',
      SemanticInstrument.histogram,
      '{request_unit}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const AzureMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
