// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `cicd`
/// namespace.
library;

import '../../semantics_base.dart';

/// `cicd.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum CicdMetric implements OTelMetric {
  /// The number of pipeline runs currently active in the system by state.
  ///
  /// Stability: release_candidate
  cicdPipelineRunActive(
      'cicd.pipeline.run.active', SemanticInstrument.upDownCounter, '{run}'),

  /// Duration of a pipeline run grouped by pipeline, state and result.
  ///
  /// Stability: release_candidate
  cicdPipelineRunDuration(
      'cicd.pipeline.run.duration', SemanticInstrument.histogram, 's'),

  /// The number of errors encountered in pipeline runs (eg. compile, test
  /// failures).
  ///
  /// Stability: release_candidate
  cicdPipelineRunErrors(
      'cicd.pipeline.run.errors', SemanticInstrument.counter, '{error}'),

  /// The number of errors in a component of the CI/CD system (eg.
  /// controller, scheduler, agent).
  ///
  /// Stability: release_candidate
  cicdSystemErrors('cicd.system.errors', SemanticInstrument.counter, '{error}'),

  /// The number of workers on the CI/CD system by state.
  ///
  /// Stability: release_candidate
  cicdWorkerCount(
      'cicd.worker.count', SemanticInstrument.upDownCounter, '{worker}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const CicdMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
