// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `cpython`
/// namespace.
library;

import '../../semantics_base.dart';

/// `cpython.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum CpythonMetric implements OTelMetric {
  /// The total number of objects collected inside a generation since
  /// interpreter start.
  ///
  /// Stability: development
  cpythonGcCollectedObjects(
      'cpython.gc.collected_objects', SemanticInstrument.counter, '{object}'),

  /// The number of times a generation was collected since interpreter start.
  ///
  /// Stability: development
  cpythonGcCollections(
      'cpython.gc.collections', SemanticInstrument.counter, '{collection}'),

  /// The total number of objects which were found to be uncollectable inside
  /// a generation since interpreter start.
  ///
  /// Stability: development
  cpythonGcUncollectableObjects('cpython.gc.uncollectable_objects',
      SemanticInstrument.counter, '{object}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const CpythonMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
