// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `db`
/// namespace.
library;

import '../../semantics_base.dart';

/// `db.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum DbMetric implements OTelMetric {
  /// The number of connections that are currently in state described by the
  /// `state` attribute.
  ///
  /// Stability: development
  dbClientConnectionCount('db.client.connection.count',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// The time it took to create a new connection.
  ///
  /// Stability: development
  dbClientConnectionCreateTime(
      'db.client.connection.create_time', SemanticInstrument.histogram, 's'),

  /// The maximum number of idle open connections allowed.
  ///
  /// Stability: development
  dbClientConnectionIdleMax('db.client.connection.idle.max',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// The minimum number of idle open connections allowed.
  ///
  /// Stability: development
  dbClientConnectionIdleMin('db.client.connection.idle.min',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// The maximum number of open connections allowed.
  ///
  /// Stability: development
  dbClientConnectionMax('db.client.connection.max',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// The number of current pending requests for an open connection.
  ///
  /// Stability: development
  dbClientConnectionPendingRequests('db.client.connection.pending_requests',
      SemanticInstrument.upDownCounter, '{request}'),

  /// The number of connection timeouts that have occurred trying to obtain a
  /// connection from the pool.
  ///
  /// Stability: development
  dbClientConnectionTimeouts(
      'db.client.connection.timeouts', SemanticInstrument.counter, '{timeout}'),

  /// The time between borrowing a connection and returning it to the pool.
  ///
  /// Stability: development
  dbClientConnectionUseTime(
      'db.client.connection.use_time', SemanticInstrument.histogram, 's'),

  /// The time it took to obtain an open connection from the pool.
  ///
  /// Stability: development
  dbClientConnectionWaitTime(
      'db.client.connection.wait_time', SemanticInstrument.histogram, 's'),

  /// Deprecated, use `db.client.connection.create_time` instead. Note: the
  /// unit also changed from `ms` to `s`.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.create_time` with unit `s`.')
  dbClientConnectionsCreateTime(
      'db.client.connections.create_time', SemanticInstrument.histogram, 'ms'),

  /// Deprecated, use `db.client.connection.idle.max` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.idle.max`.')
  dbClientConnectionsIdleMax('db.client.connections.idle.max',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// Deprecated, use `db.client.connection.idle.min` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.idle.min`.')
  dbClientConnectionsIdleMin('db.client.connections.idle.min',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// Deprecated, use `db.client.connection.max` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.max`.')
  dbClientConnectionsMax('db.client.connections.max',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// Deprecated, use `db.client.connection.pending_requests` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.pending_requests`.')
  dbClientConnectionsPendingRequests('db.client.connections.pending_requests',
      SemanticInstrument.upDownCounter, '{request}'),

  /// Deprecated, use `db.client.connection.timeouts` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.timeouts`.')
  dbClientConnectionsTimeouts('db.client.connections.timeouts',
      SemanticInstrument.counter, '{timeout}'),

  /// Deprecated, use `db.client.connection.count` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.count`.')
  dbClientConnectionsUsage('db.client.connections.usage',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// Deprecated, use `db.client.connection.use_time` instead. Note: the unit
  /// also changed from `ms` to `s`.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.use_time` with unit `s`.')
  dbClientConnectionsUseTime(
      'db.client.connections.use_time', SemanticInstrument.histogram, 'ms'),

  /// Deprecated, use `db.client.connection.wait_time` instead. Note: the
  /// unit also changed from `ms` to `s`.
  ///
  /// Stability: development
  @Deprecated('Replaced by `db.client.connection.wait_time` with unit `s`.')
  dbClientConnectionsWaitTime(
      'db.client.connections.wait_time', SemanticInstrument.histogram, 'ms'),

  /// Deprecated, use `azure.cosmosdb.client.active_instance.count` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `azure.cosmosdb.client.active_instance.count`.')
  dbClientCosmosdbActiveInstanceCount(
      'db.client.cosmosdb.active_instance.count',
      SemanticInstrument.upDownCounter,
      '{instance}'),

  /// Deprecated, use `azure.cosmosdb.client.operation.request_charge`
  /// instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `azure.cosmosdb.client.operation.request_charge`.')
  dbClientCosmosdbOperationRequestCharge(
      'db.client.cosmosdb.operation.request_charge',
      SemanticInstrument.histogram,
      '{request_unit}'),

  /// Duration of database client operations.
  dbClientOperationDuration(
      'db.client.operation.duration', SemanticInstrument.histogram, 's'),

  /// The actual number of records returned by the database operation.
  ///
  /// Stability: development
  dbClientResponseReturnedRows('db.client.response.returned_rows',
      SemanticInstrument.histogram, '{row}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const DbMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
