// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `dns`
/// namespace.
library;

import '../../semantics_base.dart';

/// `dns.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum DnsMetric implements OTelMetric {
  /// Measures the time taken to perform a DNS lookup.
  ///
  /// Stability: development
  dnsLookupDuration('dns.lookup.duration', SemanticInstrument.histogram, 's');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const DnsMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
