// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `hw`
/// namespace.
library;

import '../../semantics_base.dart';

/// `hw.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum HwMetric implements OTelMetric {
  /// Remaining fraction of battery charge.
  ///
  /// Stability: development
  hwBatteryCharge('hw.battery.charge', SemanticInstrument.gauge, '1'),

  /// Lower limit of battery charge fraction to ensure proper operation.
  ///
  /// Stability: development
  hwBatteryChargeLimit(
      'hw.battery.charge.limit', SemanticInstrument.gauge, '1'),

  /// Time left before battery is completely charged or discharged.
  ///
  /// Stability: development
  hwBatteryTimeLeft('hw.battery.time_left', SemanticInstrument.gauge, 's'),

  /// CPU current frequency.
  ///
  /// Stability: development
  hwCpuSpeed('hw.cpu.speed', SemanticInstrument.gauge, 'Hz'),

  /// CPU maximum frequency.
  ///
  /// Stability: development
  hwCpuSpeedLimit('hw.cpu.speed.limit', SemanticInstrument.gauge, 'Hz'),

  /// Energy consumed by the component.
  ///
  /// Stability: development
  hwEnergy('hw.energy', SemanticInstrument.counter, 'J'),

  /// Number of errors encountered by the component.
  ///
  /// Stability: development
  hwErrors('hw.errors', SemanticInstrument.counter, '{error}'),

  /// Fan speed in revolutions per minute.
  ///
  /// Stability: development
  hwFanSpeed('hw.fan.speed', SemanticInstrument.gauge, 'rpm'),

  /// Speed limit in rpm.
  ///
  /// Stability: development
  hwFanSpeedLimit('hw.fan.speed.limit', SemanticInstrument.gauge, 'rpm'),

  /// Fan speed expressed as a fraction of its maximum speed.
  ///
  /// Stability: development
  hwFanSpeedRatio('hw.fan.speed_ratio', SemanticInstrument.gauge, '1'),

  /// Received and transmitted bytes by the GPU.
  ///
  /// Stability: development
  hwGpuIo('hw.gpu.io', SemanticInstrument.counter, 'By'),

  /// Size of the GPU memory.
  ///
  /// Stability: development
  hwGpuMemoryLimit(
      'hw.gpu.memory.limit', SemanticInstrument.upDownCounter, 'By'),

  /// GPU memory used.
  ///
  /// Stability: development
  hwGpuMemoryUsage(
      'hw.gpu.memory.usage', SemanticInstrument.upDownCounter, 'By'),

  /// Fraction of GPU memory used.
  ///
  /// Stability: development
  hwGpuMemoryUtilization(
      'hw.gpu.memory.utilization', SemanticInstrument.gauge, '1'),

  /// Fraction of time spent in a specific task.
  ///
  /// Stability: development
  hwGpuUtilization('hw.gpu.utilization', SemanticInstrument.gauge, '1'),

  /// Ambient (external) temperature of the physical host.
  ///
  /// Stability: development
  hwHostAmbientTemperature(
      'hw.host.ambient_temperature', SemanticInstrument.gauge, 'Cel'),

  /// Total energy consumed by the entire physical host, in joules.
  ///
  /// Stability: development
  hwHostEnergy('hw.host.energy', SemanticInstrument.counter, 'J'),

  /// By how many degrees Celsius the temperature of the physical host can be
  /// increased, before reaching a warning threshold on one of the internal
  /// sensors.
  ///
  /// Stability: development
  hwHostHeatingMargin(
      'hw.host.heating_margin', SemanticInstrument.gauge, 'Cel'),

  /// Instantaneous power consumed by the entire physical host in Watts (
  /// `hw.host.energy` is preferred).
  ///
  /// Stability: development
  hwHostPower('hw.host.power', SemanticInstrument.gauge, 'W'),

  /// Size of the logical disk.
  ///
  /// Stability: development
  hwLogicalDiskLimit(
      'hw.logical_disk.limit', SemanticInstrument.upDownCounter, 'By'),

  /// Logical disk space usage.
  ///
  /// Stability: development
  hwLogicalDiskUsage(
      'hw.logical_disk.usage', SemanticInstrument.upDownCounter, 'By'),

  /// Logical disk space utilization as a fraction.
  ///
  /// Stability: development
  hwLogicalDiskUtilization(
      'hw.logical_disk.utilization', SemanticInstrument.gauge, '1'),

  /// Size of the memory module.
  ///
  /// Stability: development
  hwMemorySize('hw.memory.size', SemanticInstrument.upDownCounter, 'By'),

  /// Link speed.
  ///
  /// Stability: development
  hwNetworkBandwidthLimit(
      'hw.network.bandwidth.limit', SemanticInstrument.upDownCounter, 'By/s'),

  /// Utilization of the network bandwidth as a fraction.
  ///
  /// Stability: development
  hwNetworkBandwidthUtilization(
      'hw.network.bandwidth.utilization', SemanticInstrument.gauge, '1'),

  /// Received and transmitted network traffic in bytes.
  ///
  /// Stability: development
  hwNetworkIo('hw.network.io', SemanticInstrument.counter, 'By'),

  /// Received and transmitted network traffic in packets (or frames).
  ///
  /// Stability: development
  hwNetworkPackets(
      'hw.network.packets', SemanticInstrument.counter, '{packet}'),

  /// Link status: `1` (up) or `0` (down).
  ///
  /// Stability: development
  hwNetworkUp('hw.network.up', SemanticInstrument.upDownCounter, '1'),

  /// Endurance remaining for this SSD disk.
  ///
  /// Stability: development
  hwPhysicalDiskEnduranceUtilization(
      'hw.physical_disk.endurance_utilization', SemanticInstrument.gauge, '1'),

  /// Size of the disk.
  ///
  /// Stability: development
  hwPhysicalDiskSize(
      'hw.physical_disk.size', SemanticInstrument.upDownCounter, 'By'),

  /// Value of the corresponding
  /// [S.M.A.R.T.](https://wikipedia.org/wiki/S.M.A.R.T.) (Self-Monitoring,
  /// Analysis, and Reporting Technology) attribute.
  ///
  /// Stability: development
  hwPhysicalDiskSmart('hw.physical_disk.smart', SemanticInstrument.gauge, '1'),

  /// Instantaneous power consumed by the component.
  ///
  /// Stability: development
  hwPower('hw.power', SemanticInstrument.gauge, 'W'),

  /// Maximum power output of the power supply.
  ///
  /// Stability: development
  hwPowerSupplyLimit(
      'hw.power_supply.limit', SemanticInstrument.upDownCounter, 'W'),

  /// Current power output of the power supply.
  ///
  /// Stability: development
  hwPowerSupplyUsage(
      'hw.power_supply.usage', SemanticInstrument.upDownCounter, 'W'),

  /// Utilization of the power supply as a fraction of its maximum output.
  ///
  /// Stability: development
  hwPowerSupplyUtilization(
      'hw.power_supply.utilization', SemanticInstrument.gauge, '1'),

  /// Operational status: `1` (true) or `0` (false) for each of the possible
  /// states.
  ///
  /// Stability: development
  hwStatus('hw.status', SemanticInstrument.upDownCounter, '1'),

  /// Operations performed by the tape drive.
  ///
  /// Stability: development
  hwTapeDriveOperations(
      'hw.tape_drive.operations', SemanticInstrument.counter, '{operation}'),

  /// Temperature in degrees Celsius.
  ///
  /// Stability: development
  hwTemperature('hw.temperature', SemanticInstrument.gauge, 'Cel'),

  /// Temperature limit in degrees Celsius.
  ///
  /// Stability: development
  hwTemperatureLimit('hw.temperature.limit', SemanticInstrument.gauge, 'Cel'),

  /// Voltage measured by the sensor.
  ///
  /// Stability: development
  hwVoltage('hw.voltage', SemanticInstrument.gauge, 'V'),

  /// Voltage limit in Volts.
  ///
  /// Stability: development
  hwVoltageLimit('hw.voltage.limit', SemanticInstrument.gauge, 'V'),

  /// Nominal (expected) voltage.
  ///
  /// Stability: development
  hwVoltageNominal('hw.voltage.nominal', SemanticInstrument.gauge, 'V');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const HwMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
