// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `jvm`
/// namespace.
library;

import '../../semantics_base.dart';

/// `jvm.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum JvmMetric implements OTelMetric {
  /// Number of buffers in the pool.
  ///
  /// Stability: development
  jvmBufferCount(
      'jvm.buffer.count', SemanticInstrument.upDownCounter, '{buffer}'),

  /// Measure of total memory capacity of buffers.
  ///
  /// Stability: development
  jvmBufferMemoryLimit(
      'jvm.buffer.memory.limit', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `jvm.buffer.memory.used` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `jvm.buffer.memory.used`.')
  jvmBufferMemoryUsage(
      'jvm.buffer.memory.usage', SemanticInstrument.upDownCounter, 'By'),

  /// Measure of memory used by buffers.
  ///
  /// Stability: development
  jvmBufferMemoryUsed(
      'jvm.buffer.memory.used', SemanticInstrument.upDownCounter, 'By'),

  /// Number of classes currently loaded.
  jvmClassCount('jvm.class.count', SemanticInstrument.upDownCounter, '{class}'),

  /// Number of classes loaded since JVM start.
  jvmClassLoaded('jvm.class.loaded', SemanticInstrument.counter, '{class}'),

  /// Number of classes unloaded since JVM start.
  jvmClassUnloaded('jvm.class.unloaded', SemanticInstrument.counter, '{class}'),

  /// Number of processors available to the Java virtual machine.
  jvmCpuCount('jvm.cpu.count', SemanticInstrument.upDownCounter, '{cpu}'),

  /// Recent CPU utilization for the process as reported by the JVM.
  jvmCpuRecentUtilization(
      'jvm.cpu.recent_utilization', SemanticInstrument.gauge, '1'),

  /// CPU time used by the process as reported by the JVM.
  jvmCpuTime('jvm.cpu.time', SemanticInstrument.counter, 's'),

  /// Number of open file descriptors as reported by the JVM.
  ///
  /// Stability: development
  jvmFileDescriptorCount('jvm.file_descriptor.count',
      SemanticInstrument.upDownCounter, '{file_descriptor}'),

  /// Measure of max open file descriptors as reported by the JVM.
  ///
  /// Stability: development
  jvmFileDescriptorLimit('jvm.file_descriptor.limit',
      SemanticInstrument.upDownCounter, '{file_descriptor}'),

  /// Duration of JVM garbage collection actions.
  jvmGcDuration('jvm.gc.duration', SemanticInstrument.histogram, 's'),

  /// Measure of memory committed.
  jvmMemoryCommitted(
      'jvm.memory.committed', SemanticInstrument.upDownCounter, 'By'),

  /// Measure of initial memory requested.
  ///
  /// Stability: development
  jvmMemoryInit('jvm.memory.init', SemanticInstrument.upDownCounter, 'By'),

  /// Measure of max obtainable memory.
  jvmMemoryLimit('jvm.memory.limit', SemanticInstrument.upDownCounter, 'By'),

  /// Measure of memory used.
  jvmMemoryUsed('jvm.memory.used', SemanticInstrument.upDownCounter, 'By'),

  /// Measure of memory used, as measured after the most recent garbage
  /// collection event on this pool.
  jvmMemoryUsedAfterLastGc(
      'jvm.memory.used_after_last_gc', SemanticInstrument.upDownCounter, 'By'),

  /// Average CPU load of the whole system for the last minute as reported by
  /// the JVM.
  ///
  /// Stability: development
  jvmSystemCpuLoad1m(
      'jvm.system.cpu.load_1m', SemanticInstrument.gauge, '{run_queue_item}'),

  /// Recent CPU utilization for the whole system as reported by the JVM.
  ///
  /// Stability: development
  jvmSystemCpuUtilization(
      'jvm.system.cpu.utilization', SemanticInstrument.gauge, '1'),

  /// Number of executing platform threads.
  jvmThreadCount(
      'jvm.thread.count', SemanticInstrument.upDownCounter, '{thread}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const JvmMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
