// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `k8s`
/// namespace.
library;

import '../../semantics_base.dart';

/// `k8s.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum K8sMetric implements OTelMetric {
  /// Deprecated, use `k8s.container.cpu.limit.desired` and
  /// `k8s.container.cpu.limit.current` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.container.cpu.limit.desired`.')
  k8sContainerCpuLimit(
      'k8s.container.cpu.limit', SemanticInstrument.upDownCounter, '{cpu}'),

  /// Maximum CPU resource limit currently configured for a running
  /// container.
  ///
  /// Stability: development
  k8sContainerCpuLimitCurrent('k8s.container.cpu.limit.current',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// Maximum CPU resource limit as defined by the container spec.
  ///
  /// Stability: development
  k8sContainerCpuLimitDesired('k8s.container.cpu.limit.desired',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The ratio of container CPU usage to its current CPU limit.
  ///
  /// Stability: development
  k8sContainerCpuLimitUtilization(
      'k8s.container.cpu.limit.utilization', SemanticInstrument.gauge, '1'),

  /// Deprecated, use `k8s.container.cpu.request.desired` and
  /// `k8s.container.cpu.request.current` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.container.cpu.request.desired`.')
  k8sContainerCpuRequest(
      'k8s.container.cpu.request', SemanticInstrument.upDownCounter, '{cpu}'),

  /// CPU resource requested currently configured for a running container.
  ///
  /// Stability: development
  k8sContainerCpuRequestCurrent('k8s.container.cpu.request.current',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// CPU resource requested as defined by the container spec.
  ///
  /// Stability: development
  k8sContainerCpuRequestDesired('k8s.container.cpu.request.desired',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The ratio of container CPU usage to its current CPU request.
  ///
  /// Stability: development
  k8sContainerCpuRequestUtilization(
      'k8s.container.cpu.request.utilization', SemanticInstrument.gauge, '1'),

  /// Maximum ephemeral storage resource limit set for the container.
  ///
  /// Stability: development
  k8sContainerEphemeralStorageLimit('k8s.container.ephemeral_storage.limit',
      SemanticInstrument.upDownCounter, 'By'),

  /// Ephemeral storage resource requested for the container.
  ///
  /// Stability: development
  k8sContainerEphemeralStorageRequest('k8s.container.ephemeral_storage.request',
      SemanticInstrument.upDownCounter, 'By'),

  /// The ephemeral storage used by a container.
  ///
  /// Stability: development
  k8sContainerEphemeralStorageUsage('k8s.container.ephemeral_storage.usage',
      SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.container.memory.limit.desired` and
  /// `k8s.container.memory.limit.current` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.container.memory.limit.desired`.')
  k8sContainerMemoryLimit(
      'k8s.container.memory.limit', SemanticInstrument.upDownCounter, 'By'),

  /// Maximum memory resource limit currently configured for a running
  /// container.
  ///
  /// Stability: development
  k8sContainerMemoryLimitCurrent('k8s.container.memory.limit.current',
      SemanticInstrument.upDownCounter, 'By'),

  /// Maximum memory resource limit as defined by the container spec.
  ///
  /// Stability: development
  k8sContainerMemoryLimitDesired('k8s.container.memory.limit.desired',
      SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.container.memory.request.desired` and
  /// `k8s.container.memory.request.current` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.container.memory.request.desired`.')
  k8sContainerMemoryRequest(
      'k8s.container.memory.request', SemanticInstrument.upDownCounter, 'By'),

  /// Memory resource request currently configured for a running container.
  ///
  /// Stability: development
  k8sContainerMemoryRequestCurrent('k8s.container.memory.request.current',
      SemanticInstrument.upDownCounter, 'By'),

  /// Memory resource requested as defined by the container spec.
  ///
  /// Stability: development
  k8sContainerMemoryRequestDesired('k8s.container.memory.request.desired',
      SemanticInstrument.upDownCounter, 'By'),

  /// Indicates whether the container is currently marked as ready to accept
  /// traffic, based on its readiness probe (1 = ready, 0 = not ready).
  ///
  /// Stability: development
  k8sContainerReady(
      'k8s.container.ready', SemanticInstrument.upDownCounter, '{container}'),

  /// Describes how many times the container has restarted (since the last
  /// counter reset).
  ///
  /// Stability: development
  k8sContainerRestartCount('k8s.container.restart.count',
      SemanticInstrument.upDownCounter, '{restart}'),

  /// Describes the number of K8s containers that are currently in a state
  /// for a given reason.
  ///
  /// Stability: development
  k8sContainerStatusReason('k8s.container.status.reason',
      SemanticInstrument.upDownCounter, '{container}'),

  /// Describes the number of K8s containers that are currently in a given
  /// state.
  ///
  /// Stability: development
  k8sContainerStatusState('k8s.container.status.state',
      SemanticInstrument.upDownCounter, '{container}'),

  /// Maximum storage resource limit set for the container.
  ///
  /// Stability: development
  k8sContainerStorageLimit(
      'k8s.container.storage.limit', SemanticInstrument.upDownCounter, 'By'),

  /// Storage resource requested for the container.
  ///
  /// Stability: development
  k8sContainerStorageRequest(
      'k8s.container.storage.request', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.cronjob.job.active` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.cronjob.job.active`.')
  k8sCronjobActiveJobs(
      'k8s.cronjob.active_jobs', SemanticInstrument.upDownCounter, '{job}'),

  /// The number of actively running jobs for a cronjob.
  ///
  /// Stability: development
  k8sCronjobJobActive(
      'k8s.cronjob.job.active', SemanticInstrument.upDownCounter, '{job}'),

  /// Deprecated, use `k8s.daemonset.node.current_scheduled` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.daemonset.node.current_scheduled`.')
  k8sDaemonsetCurrentScheduledNodes('k8s.daemonset.current_scheduled_nodes',
      SemanticInstrument.upDownCounter, '{node}'),

  /// Deprecated, use `k8s.daemonset.node.desired_scheduled` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.daemonset.node.desired_scheduled`.')
  k8sDaemonsetDesiredScheduledNodes('k8s.daemonset.desired_scheduled_nodes',
      SemanticInstrument.upDownCounter, '{node}'),

  /// Deprecated, use `k8s.daemonset.node.misscheduled` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.daemonset.node.misscheduled`.')
  k8sDaemonsetMisscheduledNodes('k8s.daemonset.misscheduled_nodes',
      SemanticInstrument.upDownCounter, '{node}'),

  /// Number of nodes that are running at least 1 daemon pod and are supposed
  /// to run the daemon pod.
  ///
  /// Stability: development
  k8sDaemonsetNodeCurrentScheduled('k8s.daemonset.node.current_scheduled',
      SemanticInstrument.upDownCounter, '{node}'),

  /// Number of nodes that should be running the daemon pod (including nodes
  /// currently running the daemon pod).
  ///
  /// Stability: development
  k8sDaemonsetNodeDesiredScheduled('k8s.daemonset.node.desired_scheduled',
      SemanticInstrument.upDownCounter, '{node}'),

  /// Number of nodes that are running the daemon pod, but are not supposed
  /// to run the daemon pod.
  ///
  /// Stability: development
  k8sDaemonsetNodeMisscheduled('k8s.daemonset.node.misscheduled',
      SemanticInstrument.upDownCounter, '{node}'),

  /// Number of nodes that should be running the daemon pod and have one or
  /// more of the daemon pod running and ready.
  ///
  /// Stability: development
  k8sDaemonsetNodeReady(
      'k8s.daemonset.node.ready', SemanticInstrument.upDownCounter, '{node}'),

  /// Deprecated, use `k8s.daemonset.node.ready` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.daemonset.node.ready`.')
  k8sDaemonsetReadyNodes(
      'k8s.daemonset.ready_nodes', SemanticInstrument.upDownCounter, '{node}'),

  /// Deprecated, use `k8s.deployment.pod.available` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.deployment.pod.available`.')
  k8sDeploymentAvailablePods('k8s.deployment.available_pods',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.deployment.pod.desired` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.deployment.pod.desired`.')
  k8sDeploymentDesiredPods(
      'k8s.deployment.desired_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Total number of available replica pods (ready for at least
  /// minReadySeconds) targeted by this deployment.
  ///
  /// Stability: development
  k8sDeploymentPodAvailable('k8s.deployment.pod.available',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Number of desired replica pods in this deployment.
  ///
  /// Stability: development
  k8sDeploymentPodDesired(
      'k8s.deployment.pod.desired', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.hpa.pod.current` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.hpa.pod.current`.')
  k8sHpaCurrentPods(
      'k8s.hpa.current_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.hpa.pod.desired` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.hpa.pod.desired`.')
  k8sHpaDesiredPods(
      'k8s.hpa.desired_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.hpa.pod.max` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.hpa.pod.max`.')
  k8sHpaMaxPods('k8s.hpa.max_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Target average utilization, in percentage, for CPU resource in HPA
  /// config.
  ///
  /// Stability: development
  k8sHpaMetricTargetCpuAverageUtilization(
      'k8s.hpa.metric.target.cpu.average_utilization',
      SemanticInstrument.gauge,
      '1'),

  /// Target average value for CPU resource in HPA config.
  ///
  /// Stability: development
  k8sHpaMetricTargetCpuAverageValue('k8s.hpa.metric.target.cpu.average_value',
      SemanticInstrument.gauge, '{cpu}'),

  /// Target value for CPU resource in HPA config.
  ///
  /// Stability: development
  k8sHpaMetricTargetCpuValue(
      'k8s.hpa.metric.target.cpu.value', SemanticInstrument.gauge, '{cpu}'),

  /// Deprecated, use `k8s.hpa.pod.min` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.hpa.pod.min`.')
  k8sHpaMinPods('k8s.hpa.min_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Current number of replica pods managed by this horizontal pod
  /// autoscaler, as last seen by the autoscaler.
  ///
  /// Stability: development
  k8sHpaPodCurrent(
      'k8s.hpa.pod.current', SemanticInstrument.upDownCounter, '{pod}'),

  /// Desired number of replica pods managed by this horizontal pod
  /// autoscaler, as last calculated by the autoscaler.
  ///
  /// Stability: development
  k8sHpaPodDesired(
      'k8s.hpa.pod.desired', SemanticInstrument.upDownCounter, '{pod}'),

  /// The upper limit for the number of replica pods to which the autoscaler
  /// can scale up.
  ///
  /// Stability: development
  k8sHpaPodMax('k8s.hpa.pod.max', SemanticInstrument.upDownCounter, '{pod}'),

  /// The lower limit for the number of replica pods to which the autoscaler
  /// can scale down.
  ///
  /// Stability: development
  k8sHpaPodMin('k8s.hpa.pod.min', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.job.pod.active` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.job.pod.active`.')
  k8sJobActivePods(
      'k8s.job.active_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.job.pod.desired_successful` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.job.pod.desired_successful`.')
  k8sJobDesiredSuccessfulPods('k8s.job.desired_successful_pods',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.job.pod.failed` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.job.pod.failed`.')
  k8sJobFailedPods(
      'k8s.job.failed_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.job.pod.max_parallel` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.job.pod.max_parallel`.')
  k8sJobMaxParallelPods(
      'k8s.job.max_parallel_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// The number of pending and actively running pods for a job.
  ///
  /// Stability: development
  k8sJobPodActive(
      'k8s.job.pod.active', SemanticInstrument.upDownCounter, '{pod}'),

  /// The desired number of successfully finished pods the job should be run
  /// with.
  ///
  /// Stability: development
  k8sJobPodDesiredSuccessful('k8s.job.pod.desired_successful',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// The number of pods which reached phase Failed for a job.
  ///
  /// Stability: development
  k8sJobPodFailed(
      'k8s.job.pod.failed', SemanticInstrument.upDownCounter, '{pod}'),

  /// The max desired number of pods the job should run at any given time.
  ///
  /// Stability: development
  k8sJobPodMaxParallel(
      'k8s.job.pod.max_parallel', SemanticInstrument.upDownCounter, '{pod}'),

  /// The number of pods which reached phase Succeeded for a job.
  ///
  /// Stability: development
  k8sJobPodSuccessful(
      'k8s.job.pod.successful', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.job.pod.successful` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.job.pod.successful`.')
  k8sJobSuccessfulPods(
      'k8s.job.successful_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Describes number of K8s namespaces that are currently in a given phase.
  ///
  /// Stability: development
  k8sNamespacePhase(
      'k8s.namespace.phase', SemanticInstrument.upDownCounter, '{namespace}'),

  /// Deprecated, use `k8s.node.cpu.allocatable` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.node.cpu.allocatable`.')
  k8sNodeAllocatableCpu(
      'k8s.node.allocatable.cpu', SemanticInstrument.upDownCounter, '{cpu}'),

  /// Deprecated, use `k8s.node.ephemeral_storage.allocatable` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.node.ephemeral_storage.allocatable`.')
  k8sNodeAllocatableEphemeralStorage('k8s.node.allocatable.ephemeral_storage',
      SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.node.memory.allocatable` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.node.memory.allocatable`.')
  k8sNodeAllocatableMemory(
      'k8s.node.allocatable.memory', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.node.pod.allocatable` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.node.pod.allocatable`.')
  k8sNodeAllocatablePods(
      'k8s.node.allocatable.pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Describes the condition of a particular Node.
  ///
  /// Stability: development
  k8sNodeConditionStatus(
      'k8s.node.condition.status', SemanticInstrument.upDownCounter, '{node}'),

  /// Amount of cpu allocatable on the node.
  ///
  /// Stability: development
  k8sNodeCpuAllocatable(
      'k8s.node.cpu.allocatable', SemanticInstrument.upDownCounter, '{cpu}'),

  /// Total CPU time consumed.
  ///
  /// Stability: release_candidate
  k8sNodeCpuTime('k8s.node.cpu.time', SemanticInstrument.counter, 's'),

  /// Node's CPU usage, measured in cpus. Range from 0 to the number of
  /// allocatable CPUs.
  ///
  /// Stability: development
  k8sNodeCpuUsage('k8s.node.cpu.usage', SemanticInstrument.gauge, '{cpu}'),

  /// Amount of ephemeral-storage allocatable on the node.
  ///
  /// Stability: development
  k8sNodeEphemeralStorageAllocatable('k8s.node.ephemeral_storage.allocatable',
      SemanticInstrument.upDownCounter, 'By'),

  /// Node filesystem available bytes.
  ///
  /// Stability: development
  k8sNodeFilesystemAvailable(
      'k8s.node.filesystem.available', SemanticInstrument.upDownCounter, 'By'),

  /// Node filesystem capacity.
  ///
  /// Stability: development
  k8sNodeFilesystemCapacity(
      'k8s.node.filesystem.capacity', SemanticInstrument.upDownCounter, 'By'),

  /// Node filesystem usage.
  ///
  /// Stability: development
  k8sNodeFilesystemUsage(
      'k8s.node.filesystem.usage', SemanticInstrument.upDownCounter, 'By'),

  /// Amount of memory allocatable on the node.
  ///
  /// Stability: development
  k8sNodeMemoryAllocatable(
      'k8s.node.memory.allocatable', SemanticInstrument.upDownCounter, 'By'),

  /// Node memory available.
  ///
  /// Stability: development
  k8sNodeMemoryAvailable(
      'k8s.node.memory.available', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.node.paging.faults` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.node.paging.faults`.')
  k8sNodeMemoryPagingFaults(
      'k8s.node.memory.paging.faults', SemanticInstrument.counter, '{fault}'),

  /// Node memory RSS.
  ///
  /// Stability: development
  k8sNodeMemoryRss(
      'k8s.node.memory.rss', SemanticInstrument.upDownCounter, 'By'),

  /// Memory usage of the Node.
  ///
  /// Stability: development
  k8sNodeMemoryUsage('k8s.node.memory.usage', SemanticInstrument.gauge, 'By'),

  /// Node memory working set.
  ///
  /// Stability: development
  k8sNodeMemoryWorkingSet(
      'k8s.node.memory.working_set', SemanticInstrument.upDownCounter, 'By'),

  /// Node network errors.
  ///
  /// Stability: development
  k8sNodeNetworkErrors(
      'k8s.node.network.errors', SemanticInstrument.counter, '{error}'),

  /// Network bytes for the Node.
  ///
  /// Stability: development
  k8sNodeNetworkIo('k8s.node.network.io', SemanticInstrument.counter, 'By'),

  /// Node memory paging faults.
  ///
  /// Stability: development
  k8sNodePagingFaults(
      'k8s.node.paging.faults', SemanticInstrument.counter, '{fault}'),

  /// Amount of pods allocatable on the node.
  ///
  /// Stability: development
  k8sNodePodAllocatable(
      'k8s.node.pod.allocatable', SemanticInstrument.upDownCounter, '{pod}'),

  /// Node's system container CPU time.
  ///
  /// Stability: development
  k8sNodeSystemContainerCpuTime(
      'k8s.node.system_container.cpu.time', SemanticInstrument.counter, 's'),

  /// Node's system container CPU usage, measured in cpus.
  ///
  /// Stability: development
  k8sNodeSystemContainerCpuUsage(
      'k8s.node.system_container.cpu.usage', SemanticInstrument.gauge, '{cpu}'),

  /// Node's system container memory usage.
  ///
  /// Stability: development
  k8sNodeSystemContainerMemoryUsage('k8s.node.system_container.memory.usage',
      SemanticInstrument.upDownCounter, 'By'),

  /// The amount of working set memory.
  ///
  /// Stability: development
  k8sNodeSystemContainerMemoryWorkingSet(
      'k8s.node.system_container.memory.working_set',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The time the Node has been running.
  ///
  /// Stability: development
  k8sNodeUptime('k8s.node.uptime', SemanticInstrument.gauge, 's'),

  /// Number of PersistentVolumes in a given phase.
  ///
  /// Stability: development
  k8sPersistentvolumeStatusPhase('k8s.persistentvolume.status.phase',
      SemanticInstrument.upDownCounter, '{persistentvolume}'),

  /// The storage capacity of the PersistentVolume.
  ///
  /// Stability: development
  k8sPersistentvolumeStorageCapacity('k8s.persistentvolume.storage.capacity',
      SemanticInstrument.upDownCounter, 'By'),

  /// Number of PersistentVolumeClaims in a given phase.
  ///
  /// Stability: development
  k8sPersistentvolumeclaimStatusPhase('k8s.persistentvolumeclaim.status.phase',
      SemanticInstrument.upDownCounter, '{persistentvolumeclaim}'),

  /// The actual storage capacity provisioned for the PersistentVolumeClaim.
  ///
  /// Stability: development
  k8sPersistentvolumeclaimStorageCapacity(
      'k8s.persistentvolumeclaim.storage.capacity',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The storage requested by the PersistentVolumeClaim.
  ///
  /// Stability: development
  k8sPersistentvolumeclaimStorageRequest(
      'k8s.persistentvolumeclaim.storage.request',
      SemanticInstrument.upDownCounter,
      'By'),

  /// Total CPU time consumed.
  ///
  /// Stability: release_candidate
  k8sPodCpuTime('k8s.pod.cpu.time', SemanticInstrument.counter, 's'),

  /// Pod's CPU usage, measured in cpus. Range from 0 to the number of
  /// allocatable CPUs.
  ///
  /// Stability: development
  k8sPodCpuUsage('k8s.pod.cpu.usage', SemanticInstrument.gauge, '{cpu}'),

  /// Pod filesystem available bytes.
  ///
  /// Stability: development
  k8sPodFilesystemAvailable(
      'k8s.pod.filesystem.available', SemanticInstrument.upDownCounter, 'By'),

  /// Pod filesystem capacity.
  ///
  /// Stability: development
  k8sPodFilesystemCapacity(
      'k8s.pod.filesystem.capacity', SemanticInstrument.upDownCounter, 'By'),

  /// Pod filesystem usage.
  ///
  /// Stability: development
  k8sPodFilesystemUsage(
      'k8s.pod.filesystem.usage', SemanticInstrument.upDownCounter, 'By'),

  /// Pod memory available.
  ///
  /// Stability: development
  k8sPodMemoryAvailable(
      'k8s.pod.memory.available', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.pod.paging.faults` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.pod.paging.faults`.')
  k8sPodMemoryPagingFaults(
      'k8s.pod.memory.paging.faults', SemanticInstrument.counter, '{fault}'),

  /// Pod memory RSS.
  ///
  /// Stability: development
  k8sPodMemoryRss('k8s.pod.memory.rss', SemanticInstrument.upDownCounter, 'By'),

  /// Memory usage of the Pod.
  ///
  /// Stability: development
  k8sPodMemoryUsage('k8s.pod.memory.usage', SemanticInstrument.gauge, 'By'),

  /// Pod memory working set.
  ///
  /// Stability: development
  k8sPodMemoryWorkingSet(
      'k8s.pod.memory.working_set', SemanticInstrument.upDownCounter, 'By'),

  /// Pod network errors.
  ///
  /// Stability: development
  k8sPodNetworkErrors(
      'k8s.pod.network.errors', SemanticInstrument.counter, '{error}'),

  /// Network bytes for the Pod.
  ///
  /// Stability: development
  k8sPodNetworkIo('k8s.pod.network.io', SemanticInstrument.counter, 'By'),

  /// Pod memory paging faults.
  ///
  /// Stability: development
  k8sPodPagingFaults(
      'k8s.pod.paging.faults', SemanticInstrument.counter, '{fault}'),

  /// Describes number of K8s Pods that are currently in a given phase.
  ///
  /// Stability: development
  k8sPodStatusPhase(
      'k8s.pod.status.phase', SemanticInstrument.upDownCounter, '{pod}'),

  /// Describes the number of K8s Pods that are currently in a state for a
  /// given reason.
  ///
  /// Stability: development
  k8sPodStatusReason(
      'k8s.pod.status.reason', SemanticInstrument.upDownCounter, '{pod}'),

  /// The time the Pod has been running.
  ///
  /// Stability: development
  k8sPodUptime('k8s.pod.uptime', SemanticInstrument.gauge, 's'),

  /// Pod volume storage space available.
  ///
  /// Stability: development
  k8sPodVolumeAvailable(
      'k8s.pod.volume.available', SemanticInstrument.upDownCounter, 'By'),

  /// Pod volume total capacity.
  ///
  /// Stability: development
  k8sPodVolumeCapacity(
      'k8s.pod.volume.capacity', SemanticInstrument.upDownCounter, 'By'),

  /// The total inodes in the filesystem of the Pod's volume.
  ///
  /// Stability: development
  k8sPodVolumeInodeCount('k8s.pod.volume.inode.count',
      SemanticInstrument.upDownCounter, '{inode}'),

  /// The free inodes in the filesystem of the Pod's volume.
  ///
  /// Stability: development
  k8sPodVolumeInodeFree(
      'k8s.pod.volume.inode.free', SemanticInstrument.upDownCounter, '{inode}'),

  /// The inodes used by the filesystem of the Pod's volume.
  ///
  /// Stability: development
  k8sPodVolumeInodeUsed(
      'k8s.pod.volume.inode.used', SemanticInstrument.upDownCounter, '{inode}'),

  /// Pod volume usage.
  ///
  /// Stability: development
  k8sPodVolumeUsage(
      'k8s.pod.volume.usage', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `k8s.replicaset.pod.available` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.replicaset.pod.available`.')
  k8sReplicasetAvailablePods('k8s.replicaset.available_pods',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.replicaset.pod.desired` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.replicaset.pod.desired`.')
  k8sReplicasetDesiredPods(
      'k8s.replicaset.desired_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Total number of available replica pods (ready for at least
  /// minReadySeconds) targeted by this replicaset.
  ///
  /// Stability: development
  k8sReplicasetPodAvailable('k8s.replicaset.pod.available',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Number of desired replica pods in this replicaset.
  ///
  /// Stability: development
  k8sReplicasetPodDesired(
      'k8s.replicaset.pod.desired', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.replicationcontroller.pod.available` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.replicationcontroller.pod.available`.')
  k8sReplicationControllerAvailablePods(
      'k8s.replication_controller.available_pods',
      SemanticInstrument.upDownCounter,
      '{pod}'),

  /// Deprecated, use `k8s.replicationcontroller.pod.desired` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.replicationcontroller.pod.desired`.')
  k8sReplicationControllerDesiredPods('k8s.replication_controller.desired_pods',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.replicationcontroller.pod.available` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.replicationcontroller.pod.available`.')
  k8sReplicationcontrollerAvailablePods(
      'k8s.replicationcontroller.available_pods',
      SemanticInstrument.upDownCounter,
      '{pod}'),

  /// Deprecated, use `k8s.replicationcontroller.pod.desired` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.replicationcontroller.pod.desired`.')
  k8sReplicationcontrollerDesiredPods('k8s.replicationcontroller.desired_pods',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Total number of available replica pods (ready for at least
  /// minReadySeconds) targeted by this replication controller.
  ///
  /// Stability: development
  k8sReplicationcontrollerPodAvailable(
      'k8s.replicationcontroller.pod.available',
      SemanticInstrument.upDownCounter,
      '{pod}'),

  /// Number of desired replica pods in this replication controller.
  ///
  /// Stability: development
  k8sReplicationcontrollerPodDesired('k8s.replicationcontroller.pod.desired',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// The CPU limits in a specific namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaCpuLimitHard('k8s.resourcequota.cpu.limit.hard',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The CPU limits in a specific namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaCpuLimitUsed('k8s.resourcequota.cpu.limit.used',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The CPU requests in a specific namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaCpuRequestHard('k8s.resourcequota.cpu.request.hard',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The CPU requests in a specific namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaCpuRequestUsed('k8s.resourcequota.cpu.request.used',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The sum of local ephemeral storage limits in the namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaEphemeralStorageLimitHard(
      'k8s.resourcequota.ephemeral_storage.limit.hard',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The sum of local ephemeral storage limits in the namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaEphemeralStorageLimitUsed(
      'k8s.resourcequota.ephemeral_storage.limit.used',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The sum of local ephemeral storage requests in the namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaEphemeralStorageRequestHard(
      'k8s.resourcequota.ephemeral_storage.request.hard',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The sum of local ephemeral storage requests in the namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaEphemeralStorageRequestUsed(
      'k8s.resourcequota.ephemeral_storage.request.used',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The huge page requests in a specific namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaHugepageCountRequestHard(
      'k8s.resourcequota.hugepage_count.request.hard',
      SemanticInstrument.upDownCounter,
      '{hugepage}'),

  /// The huge page requests in a specific namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaHugepageCountRequestUsed(
      'k8s.resourcequota.hugepage_count.request.used',
      SemanticInstrument.upDownCounter,
      '{hugepage}'),

  /// The memory limits in a specific namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaMemoryLimitHard('k8s.resourcequota.memory.limit.hard',
      SemanticInstrument.upDownCounter, 'By'),

  /// The memory limits in a specific namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaMemoryLimitUsed('k8s.resourcequota.memory.limit.used',
      SemanticInstrument.upDownCounter, 'By'),

  /// The memory requests in a specific namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaMemoryRequestHard('k8s.resourcequota.memory.request.hard',
      SemanticInstrument.upDownCounter, 'By'),

  /// The memory requests in a specific namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaMemoryRequestUsed('k8s.resourcequota.memory.request.used',
      SemanticInstrument.upDownCounter, 'By'),

  /// The object count limits in a specific namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaObjectCountHard('k8s.resourcequota.object_count.hard',
      SemanticInstrument.upDownCounter, '{object}'),

  /// The object count limits in a specific namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaObjectCountUsed('k8s.resourcequota.object_count.used',
      SemanticInstrument.upDownCounter, '{object}'),

  /// The total number of PersistentVolumeClaims that can exist in the
  /// namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaPersistentvolumeclaimCountHard(
      'k8s.resourcequota.persistentvolumeclaim_count.hard',
      SemanticInstrument.upDownCounter,
      '{persistentvolumeclaim}'),

  /// The total number of PersistentVolumeClaims that can exist in the
  /// namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaPersistentvolumeclaimCountUsed(
      'k8s.resourcequota.persistentvolumeclaim_count.used',
      SemanticInstrument.upDownCounter,
      '{persistentvolumeclaim}'),

  /// The storage requests in a specific namespace.
  /// The value represents the configured quota limit of the resource in the
  /// namespace.
  ///
  /// Stability: development
  k8sResourcequotaStorageRequestHard('k8s.resourcequota.storage.request.hard',
      SemanticInstrument.upDownCounter, 'By'),

  /// The storage requests in a specific namespace.
  /// The value represents the current observed total usage of the resource
  /// in the namespace.
  ///
  /// Stability: development
  k8sResourcequotaStorageRequestUsed('k8s.resourcequota.storage.request.used',
      SemanticInstrument.upDownCounter, 'By'),

  /// Number of endpoints for a service by condition and address type.
  ///
  /// Stability: development
  k8sServiceEndpointCount(
      'k8s.service.endpoint.count', SemanticInstrument.gauge, '{endpoint}'),

  /// Number of load balancer ingress points (external IPs/hostnames)
  /// assigned to the service.
  ///
  /// Stability: development
  k8sServiceLoadBalancerIngressCount('k8s.service.load_balancer.ingress.count',
      SemanticInstrument.gauge, '{ingress}'),

  /// Deprecated, use `k8s.statefulset.pod.current` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.statefulset.pod.current`.')
  k8sStatefulsetCurrentPods('k8s.statefulset.current_pods',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.statefulset.pod.desired` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.statefulset.pod.desired`.')
  k8sStatefulsetDesiredPods('k8s.statefulset.desired_pods',
      SemanticInstrument.upDownCounter, '{pod}'),

  /// The number of replica pods created by the statefulset controller from
  /// the statefulset version indicated by currentRevision.
  ///
  /// Stability: development
  k8sStatefulsetPodCurrent(
      'k8s.statefulset.pod.current', SemanticInstrument.upDownCounter, '{pod}'),

  /// Number of desired replica pods in this statefulset.
  ///
  /// Stability: development
  k8sStatefulsetPodDesired(
      'k8s.statefulset.pod.desired', SemanticInstrument.upDownCounter, '{pod}'),

  /// The number of replica pods created for this statefulset with a Ready
  /// Condition.
  ///
  /// Stability: development
  k8sStatefulsetPodReady(
      'k8s.statefulset.pod.ready', SemanticInstrument.upDownCounter, '{pod}'),

  /// Number of replica pods created by the statefulset controller from the
  /// statefulset version indicated by updateRevision.
  ///
  /// Stability: development
  k8sStatefulsetPodUpdated(
      'k8s.statefulset.pod.updated', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.statefulset.pod.ready` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.statefulset.pod.ready`.')
  k8sStatefulsetReadyPods(
      'k8s.statefulset.ready_pods', SemanticInstrument.upDownCounter, '{pod}'),

  /// Deprecated, use `k8s.statefulset.pod.updated` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `k8s.statefulset.pod.updated`.')
  k8sStatefulsetUpdatedPods('k8s.statefulset.updated_pods',
      SemanticInstrument.upDownCounter, '{pod}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const K8sMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
