// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `messaging`
/// namespace.
library;

import '../../semantics_base.dart';

/// `messaging.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum MessagingMetric implements OTelMetric {
  /// Number of messages that were delivered to the application.
  ///
  /// Stability: development
  messagingClientConsumedMessages('messaging.client.consumed.messages',
      SemanticInstrument.counter, '{message}'),

  /// Duration of messaging operation initiated by a producer or consumer
  /// client.
  ///
  /// Stability: development
  messagingClientOperationDuration(
      'messaging.client.operation.duration', SemanticInstrument.histogram, 's'),

  /// Deprecated. Use `messaging.client.sent.messages` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.client.sent.messages`.')
  messagingClientPublishedMessages('messaging.client.published.messages',
      SemanticInstrument.counter, '{message}'),

  /// Number of messages producer attempted to send to the broker.
  ///
  /// Stability: development
  messagingClientSentMessages('messaging.client.sent.messages',
      SemanticInstrument.counter, '{message}'),

  /// Duration of processing operation.
  ///
  /// Stability: development
  messagingProcessDuration(
      'messaging.process.duration', SemanticInstrument.histogram, 's'),

  /// Deprecated. Use `messaging.client.consumed.messages` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.client.consumed.messages`.')
  messagingProcessMessages(
      'messaging.process.messages', SemanticInstrument.counter, '{message}'),

  /// Deprecated. Use `messaging.client.operation.duration` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.client.operation.duration`.')
  messagingPublishDuration(
      'messaging.publish.duration', SemanticInstrument.histogram, 's'),

  /// Deprecated. Use `messaging.client.sent.messages` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.client.sent.messages`.')
  messagingPublishMessages(
      'messaging.publish.messages', SemanticInstrument.counter, '{message}'),

  /// Deprecated. Use `messaging.client.operation.duration` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.client.operation.duration`.')
  messagingReceiveDuration(
      'messaging.receive.duration', SemanticInstrument.histogram, 's'),

  /// Deprecated. Use `messaging.client.consumed.messages` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `messaging.client.consumed.messages`.')
  messagingReceiveMessages(
      'messaging.receive.messages', SemanticInstrument.counter, '{message}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const MessagingMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
