// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `nfs`
/// namespace.
library;

import '../../semantics_base.dart';

/// `nfs.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum NfsMetric implements OTelMetric {
  /// Reports the count of kernel NFS client TCP segments and UDP datagrams
  /// handled.
  ///
  /// Stability: development
  nfsClientNetCount(
      'nfs.client.net.count', SemanticInstrument.counter, '{record}'),

  /// Reports the count of kernel NFS client TCP connections accepted.
  ///
  /// Stability: development
  nfsClientNetTcpConnectionAccepted('nfs.client.net.tcp.connection.accepted',
      SemanticInstrument.counter, '{connection}'),

  /// Reports the count of kernel NFSv4+ client operations.
  ///
  /// Stability: development
  nfsClientOperationCount(
      'nfs.client.operation.count', SemanticInstrument.counter, '{operation}'),

  /// Reports the count of kernel NFS client procedures.
  ///
  /// Stability: development
  nfsClientProcedureCount(
      'nfs.client.procedure.count', SemanticInstrument.counter, '{procedure}'),

  /// Reports the count of kernel NFS client RPC authentication refreshes.
  ///
  /// Stability: development
  nfsClientRpcAuthrefreshCount('nfs.client.rpc.authrefresh.count',
      SemanticInstrument.counter, '{authrefresh}'),

  /// Reports the count of kernel NFS client RPCs sent, regardless of whether
  /// they're accepted/rejected by the server.
  ///
  /// Stability: development
  nfsClientRpcCount(
      'nfs.client.rpc.count', SemanticInstrument.counter, '{request}'),

  /// Reports the count of kernel NFS client RPC retransmits.
  ///
  /// Stability: development
  nfsClientRpcRetransmitCount('nfs.client.rpc.retransmit.count',
      SemanticInstrument.counter, '{retransmit}'),

  /// Reports the count of kernel NFS server stale file handles.
  ///
  /// Stability: development
  nfsServerFhStaleCount(
      'nfs.server.fh.stale.count', SemanticInstrument.counter, '{fh}'),

  /// Reports the count of kernel NFS server bytes returned to receive and
  /// transmit (read and write) requests.
  ///
  /// Stability: development
  nfsServerIo('nfs.server.io', SemanticInstrument.counter, 'By'),

  /// Reports the count of kernel NFS server TCP segments and UDP datagrams
  /// handled.
  ///
  /// Stability: development
  nfsServerNetCount(
      'nfs.server.net.count', SemanticInstrument.counter, '{record}'),

  /// Reports the count of kernel NFS server TCP connections accepted.
  ///
  /// Stability: development
  nfsServerNetTcpConnectionAccepted('nfs.server.net.tcp.connection.accepted',
      SemanticInstrument.counter, '{connection}'),

  /// Reports the count of kernel NFSv4+ server operations.
  ///
  /// Stability: development
  nfsServerOperationCount(
      'nfs.server.operation.count', SemanticInstrument.counter, '{operation}'),

  /// Reports the count of kernel NFS server procedures.
  ///
  /// Stability: development
  nfsServerProcedureCount(
      'nfs.server.procedure.count', SemanticInstrument.counter, '{procedure}'),

  /// Reports the kernel NFS server reply cache request count by cache hit
  /// status.
  ///
  /// Stability: development
  nfsServerRepcacheRequests(
      'nfs.server.repcache.requests', SemanticInstrument.counter, '{request}'),

  /// Reports the count of kernel NFS server RPCs handled.
  ///
  /// Stability: development
  nfsServerRpcCount(
      'nfs.server.rpc.count', SemanticInstrument.counter, '{request}'),

  /// Reports the count of kernel NFS server available threads.
  ///
  /// Stability: development
  nfsServerThreadCount(
      'nfs.server.thread.count', SemanticInstrument.upDownCounter, '{thread}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const NfsMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
