// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `nodejs`
/// namespace.
library;

import '../../semantics_base.dart';

/// `nodejs.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum NodejsMetric implements OTelMetric {
  /// Event loop maximum delay.
  ///
  /// Stability: development
  nodejsEventloopDelayMax(
      'nodejs.eventloop.delay.max', SemanticInstrument.gauge, 's'),

  /// Event loop mean delay.
  ///
  /// Stability: development
  nodejsEventloopDelayMean(
      'nodejs.eventloop.delay.mean', SemanticInstrument.gauge, 's'),

  /// Event loop minimum delay.
  ///
  /// Stability: development
  nodejsEventloopDelayMin(
      'nodejs.eventloop.delay.min', SemanticInstrument.gauge, 's'),

  /// Event loop 50 percentile delay.
  ///
  /// Stability: development
  nodejsEventloopDelayP50(
      'nodejs.eventloop.delay.p50', SemanticInstrument.gauge, 's'),

  /// Event loop 90 percentile delay.
  ///
  /// Stability: development
  nodejsEventloopDelayP90(
      'nodejs.eventloop.delay.p90', SemanticInstrument.gauge, 's'),

  /// Event loop 99 percentile delay.
  ///
  /// Stability: development
  nodejsEventloopDelayP99(
      'nodejs.eventloop.delay.p99', SemanticInstrument.gauge, 's'),

  /// Event loop standard deviation delay.
  ///
  /// Stability: development
  nodejsEventloopDelayStddev(
      'nodejs.eventloop.delay.stddev', SemanticInstrument.gauge, 's'),

  /// Cumulative duration of time the event loop has been in each state.
  ///
  /// Stability: development
  nodejsEventloopTime('nodejs.eventloop.time', SemanticInstrument.counter, 's'),

  /// Event loop utilization.
  ///
  /// Stability: development
  nodejsEventloopUtilization(
      'nodejs.eventloop.utilization', SemanticInstrument.gauge, '1');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const NodejsMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
