// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `openshift`
/// namespace.
library;

import '../../semantics_base.dart';

/// `openshift.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum OpenshiftMetric implements OTelMetric {
  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaCpuLimitHard('openshift.clusterquota.cpu.limit.hard',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaCpuLimitUsed('openshift.clusterquota.cpu.limit.used',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaCpuRequestHard('openshift.clusterquota.cpu.request.hard',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaCpuRequestUsed('openshift.clusterquota.cpu.request.used',
      SemanticInstrument.upDownCounter, '{cpu}'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaEphemeralStorageLimitHard(
      'openshift.clusterquota.ephemeral_storage.limit.hard',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaEphemeralStorageLimitUsed(
      'openshift.clusterquota.ephemeral_storage.limit.used',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaEphemeralStorageRequestHard(
      'openshift.clusterquota.ephemeral_storage.request.hard',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaEphemeralStorageRequestUsed(
      'openshift.clusterquota.ephemeral_storage.request.used',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaHugepageCountRequestHard(
      'openshift.clusterquota.hugepage_count.request.hard',
      SemanticInstrument.upDownCounter,
      '{hugepage}'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaHugepageCountRequestUsed(
      'openshift.clusterquota.hugepage_count.request.used',
      SemanticInstrument.upDownCounter,
      '{hugepage}'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaMemoryLimitHard(
      'openshift.clusterquota.memory.limit.hard',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaMemoryLimitUsed(
      'openshift.clusterquota.memory.limit.used',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaMemoryRequestHard(
      'openshift.clusterquota.memory.request.hard',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaMemoryRequestUsed(
      'openshift.clusterquota.memory.request.used',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaObjectCountHard(
      'openshift.clusterquota.object_count.hard',
      SemanticInstrument.upDownCounter,
      '{object}'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaObjectCountUsed(
      'openshift.clusterquota.object_count.used',
      SemanticInstrument.upDownCounter,
      '{object}'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaPersistentvolumeclaimCountHard(
      'openshift.clusterquota.persistentvolumeclaim_count.hard',
      SemanticInstrument.upDownCounter,
      '{persistentvolumeclaim}'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaPersistentvolumeclaimCountUsed(
      'openshift.clusterquota.persistentvolumeclaim_count.used',
      SemanticInstrument.upDownCounter,
      '{persistentvolumeclaim}'),

  /// The enforced hard limit of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaStorageRequestHard(
      'openshift.clusterquota.storage.request.hard',
      SemanticInstrument.upDownCounter,
      'By'),

  /// The current observed total usage of the resource across all projects.
  ///
  /// Stability: development
  openshiftClusterquotaStorageRequestUsed(
      'openshift.clusterquota.storage.request.used',
      SemanticInstrument.upDownCounter,
      'By');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const OpenshiftMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
