// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `otel`
/// namespace.
library;

import '../../semantics_base.dart';

/// `otel.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum OtelMetric implements OTelMetric {
  /// The number of log records for which the export has finished, either
  /// successful or failed.
  ///
  /// Stability: development
  otelSdkExporterLogExported('otel.sdk.exporter.log.exported',
      SemanticInstrument.counter, '{log_record}'),

  /// The number of log records which were passed to the exporter, but that
  /// have not been exported yet (neither successful, nor failed).
  ///
  /// Stability: development
  otelSdkExporterLogInflight('otel.sdk.exporter.log.inflight',
      SemanticInstrument.upDownCounter, '{log_record}'),

  /// The number of metric data points for which the export has finished,
  /// either successful or failed.
  ///
  /// Stability: development
  otelSdkExporterMetricDataPointExported(
      'otel.sdk.exporter.metric_data_point.exported',
      SemanticInstrument.counter,
      '{data_point}'),

  /// The number of metric data points which were passed to the exporter, but
  /// that have not been exported yet (neither successful, nor failed).
  ///
  /// Stability: development
  otelSdkExporterMetricDataPointInflight(
      'otel.sdk.exporter.metric_data_point.inflight',
      SemanticInstrument.upDownCounter,
      '{data_point}'),

  /// The duration of exporting a batch of telemetry records.
  ///
  /// Stability: development
  otelSdkExporterOperationDuration('otel.sdk.exporter.operation.duration',
      SemanticInstrument.histogram, 's'),

  /// The number of spans for which the export has finished, either
  /// successful or failed.
  ///
  /// Stability: development
  otelSdkExporterSpanExported(
      'otel.sdk.exporter.span.exported', SemanticInstrument.counter, '{span}'),

  /// Deprecated, use `otel.sdk.exporter.span.exported` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `otel.sdk.exporter.span.exported`.')
  otelSdkExporterSpanExportedCount('otel.sdk.exporter.span.exported.count',
      SemanticInstrument.upDownCounter, '{span}'),

  /// The number of spans which were passed to the exporter, but that have
  /// not been exported yet (neither successful, nor failed).
  ///
  /// Stability: development
  otelSdkExporterSpanInflight('otel.sdk.exporter.span.inflight',
      SemanticInstrument.upDownCounter, '{span}'),

  /// Deprecated, use `otel.sdk.exporter.span.inflight` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `otel.sdk.exporter.span.inflight`.')
  otelSdkExporterSpanInflightCount('otel.sdk.exporter.span.inflight.count',
      SemanticInstrument.upDownCounter, '{span}'),

  /// The number of logs submitted to enabled SDK Loggers.
  ///
  /// Stability: development
  otelSdkLogCreated(
      'otel.sdk.log.created', SemanticInstrument.counter, '{log_record}'),

  /// The duration of the collect operation of the metric reader.
  ///
  /// Stability: development
  otelSdkMetricReaderCollectionDuration(
      'otel.sdk.metric_reader.collection.duration',
      SemanticInstrument.histogram,
      's'),

  /// The number of log records for which the processing has finished, either
  /// successful or failed.
  ///
  /// Stability: development
  otelSdkProcessorLogProcessed('otel.sdk.processor.log.processed',
      SemanticInstrument.counter, '{log_record}'),

  /// The maximum number of log records the queue of a given instance of an
  /// SDK Log Record processor can hold.
  ///
  /// Stability: development
  otelSdkProcessorLogQueueCapacity('otel.sdk.processor.log.queue.capacity',
      SemanticInstrument.upDownCounter, '{log_record}'),

  /// The number of log records in the queue of a given instance of an SDK
  /// log processor.
  ///
  /// Stability: development
  otelSdkProcessorLogQueueSize('otel.sdk.processor.log.queue.size',
      SemanticInstrument.upDownCounter, '{log_record}'),

  /// The number of spans for which the processing has finished, either
  /// successful or failed.
  ///
  /// Stability: development
  otelSdkProcessorSpanProcessed('otel.sdk.processor.span.processed',
      SemanticInstrument.counter, '{span}'),

  /// Deprecated, use `otel.sdk.processor.span.processed` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `otel.sdk.processor.span.processed`.')
  otelSdkProcessorSpanProcessedCount('otel.sdk.processor.span.processed.count',
      SemanticInstrument.upDownCounter, '{span}'),

  /// The maximum number of spans the queue of a given instance of an SDK
  /// span processor can hold.
  ///
  /// Stability: development
  otelSdkProcessorSpanQueueCapacity('otel.sdk.processor.span.queue.capacity',
      SemanticInstrument.upDownCounter, '{span}'),

  /// The number of spans in the queue of a given instance of an SDK span
  /// processor.
  ///
  /// Stability: development
  otelSdkProcessorSpanQueueSize('otel.sdk.processor.span.queue.size',
      SemanticInstrument.upDownCounter, '{span}'),

  /// Use `otel.sdk.span.started` minus `otel.sdk.span.live` to derive this
  /// value.
  ///
  /// Stability: development
  @Deprecated('Obsoleted.')
  otelSdkSpanEnded('otel.sdk.span.ended', SemanticInstrument.counter, '{span}'),

  /// Use `otel.sdk.span.started` minus `otel.sdk.span.live` to derive this
  /// value.
  ///
  /// Stability: development
  @Deprecated('Obsoleted.')
  otelSdkSpanEndedCount(
      'otel.sdk.span.ended.count', SemanticInstrument.counter, '{span}'),

  /// The number of created spans with `recording=true` for which the end
  /// operation has not been called yet.
  ///
  /// Stability: development
  otelSdkSpanLive(
      'otel.sdk.span.live', SemanticInstrument.upDownCounter, '{span}'),

  /// Deprecated, use `otel.sdk.span.live` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `otel.sdk.span.live`.')
  otelSdkSpanLiveCount(
      'otel.sdk.span.live.count', SemanticInstrument.upDownCounter, '{span}'),

  /// The number of created spans.
  ///
  /// Stability: development
  otelSdkSpanStarted(
      'otel.sdk.span.started', SemanticInstrument.counter, '{span}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const OtelMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
