// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0
// (registry v1.44.0 @ e10a9308).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `process`
/// namespace.
library;

import '../../semantics_base.dart';

/// `process.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum ProcessMetric implements OTelMetric {
  /// Number of times the process has been context switched.
  ///
  /// Stability: release_candidate
  processContextSwitches('process.context_switches', SemanticInstrument.counter,
      '{context_switch}'),

  /// Total CPU seconds broken down by different CPU modes.
  ///
  /// Stability: release_candidate
  processCpuTime('process.cpu.time', SemanticInstrument.counter, 's'),

  /// Difference in process.cpu.time since the last measurement, divided by
  /// the elapsed time and number of CPUs available to the process.
  ///
  /// Stability: release_candidate
  processCpuUtilization(
      'process.cpu.utilization', SemanticInstrument.gauge, '1'),

  /// Disk bytes transferred.
  ///
  /// Stability: release_candidate
  processDiskIo('process.disk.io', SemanticInstrument.counter, 'By'),

  /// Number of disk operations performed by the process.
  ///
  /// Stability: development
  processDiskOperations(
      'process.disk.operations', SemanticInstrument.counter, '{operation}'),

  /// The amount of physical memory in use.
  ///
  /// Stability: release_candidate
  processMemoryUsage(
      'process.memory.usage', SemanticInstrument.upDownCounter, 'By'),

  /// Percentage of total physical memory that is used by the process.
  ///
  /// Stability: development
  processMemoryUtilization(
      'process.memory.utilization', SemanticInstrument.gauge, '1'),

  /// The amount of committed virtual memory.
  ///
  /// Stability: release_candidate
  processMemoryVirtual(
      'process.memory.virtual', SemanticInstrument.upDownCounter, 'By'),

  /// Network bytes transferred.
  ///
  /// Stability: release_candidate
  processNetworkIo('process.network.io', SemanticInstrument.counter, 'By'),

  /// Deprecated, use `process.unix.file_descriptor.count` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `process.unix.file_descriptor.count`.')
  processOpenFileDescriptorCount('process.open_file_descriptor.count',
      SemanticInstrument.upDownCounter, '{file_descriptor}'),

  /// Number of page faults the process has made.
  ///
  /// Stability: release_candidate
  processPagingFaults(
      'process.paging.faults', SemanticInstrument.counter, '{fault}'),

  /// Number of pending signals for the process.
  ///
  /// Stability: development
  processSignalsPending(
      'process.signals_pending', SemanticInstrument.upDownCounter, '{signal}'),

  /// Process threads count.
  ///
  /// Stability: release_candidate
  processThreadCount(
      'process.thread.count', SemanticInstrument.upDownCounter, '{thread}'),

  /// Number of UNIX file descriptors in use by the process.
  ///
  /// Stability: release_candidate
  processUnixFileDescriptorCount('process.unix.file_descriptor.count',
      SemanticInstrument.upDownCounter, '{file_descriptor}'),

  /// The time the process has been running.
  ///
  /// Stability: release_candidate
  processUptime('process.uptime', SemanticInstrument.gauge, 's'),

  /// Number of handles held by the process.
  ///
  /// Stability: release_candidate
  processWindowsHandleCount('process.windows.handle.count',
      SemanticInstrument.upDownCounter, '{handle}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const ProcessMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
