// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `signalr`
/// namespace.
library;

import '../../semantics_base.dart';

/// `signalr.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum SignalrMetric implements OTelMetric {
  /// Number of connections that are currently active on the server.
  signalrServerActiveConnections('signalr.server.active_connections',
      SemanticInstrument.upDownCounter, '{connection}'),

  /// The duration of connections on the server.
  signalrServerConnectionDuration(
      'signalr.server.connection.duration', SemanticInstrument.histogram, 's');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const SignalrMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
