// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `v8js`
/// namespace.
library;

import '../../semantics_base.dart';

/// `v8js.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum V8jsMetric implements OTelMetric {
  /// Garbage collection duration.
  ///
  /// Stability: development
  v8jsGcDuration('v8js.gc.duration', SemanticInstrument.histogram, 's'),

  /// Deprecated, use `v8js.memory.heap.space.available_size` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `v8js.memory.heap.space.available_size`.')
  v8jsHeapSpaceAvailableSize(
      'v8js.heap.space.available_size', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `v8js.memory.heap.space.physical_size` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `v8js.memory.heap.space.physical_size`.')
  v8jsHeapSpacePhysicalSize(
      'v8js.heap.space.physical_size', SemanticInstrument.upDownCounter, 'By'),

  /// Deprecated, use `v8js.memory.heap.space.size` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `v8js.memory.heap.space.size`.')
  v8jsMemoryHeapLimit(
      'v8js.memory.heap.limit', SemanticInstrument.upDownCounter, 'By'),

  /// Heap space available size.
  ///
  /// Stability: development
  v8jsMemoryHeapSpaceAvailableSize('v8js.memory.heap.space.available_size',
      SemanticInstrument.upDownCounter, 'By'),

  /// Committed size of a heap space.
  ///
  /// Stability: development
  v8jsMemoryHeapSpacePhysicalSize('v8js.memory.heap.space.physical_size',
      SemanticInstrument.upDownCounter, 'By'),

  /// Total heap memory size pre-allocated for a heap space.
  ///
  /// Stability: development
  v8jsMemoryHeapSpaceSize(
      'v8js.memory.heap.space.size', SemanticInstrument.upDownCounter, 'By'),

  /// Heap Memory size allocated.
  ///
  /// Stability: development
  v8jsMemoryHeapUsed(
      'v8js.memory.heap.used', SemanticInstrument.upDownCounter, 'By'),

  /// Gauge of the active resources that are currently keeping the event loop
  /// alive.
  ///
  /// Stability: development
  v8jsResourceActive(
      'v8js.resource.active', SemanticInstrument.gauge, '{resource}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const V8jsMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
