// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention metric instruments for the `vcs`
/// namespace.
library;

import '../../semantics_base.dart';

/// `vcs.*` metric instruments from the OpenTelemetry
/// semantic conventions.
enum VcsMetric implements OTelMetric {
  /// The number of changes (pull requests/merge requests/changelists) in a
  /// repository, categorized by their state (e.g. open or merged).
  ///
  /// Stability: release_candidate
  vcsChangeCount(
      'vcs.change.count', SemanticInstrument.upDownCounter, '{change}'),

  /// The time duration a change (pull request/merge request/changelist) has
  /// been in a given state.
  ///
  /// Stability: release_candidate
  vcsChangeDuration('vcs.change.duration', SemanticInstrument.gauge, 's'),

  /// The amount of time since its creation it took a change (pull
  /// request/merge request/changelist) to get the first approval.
  ///
  /// Stability: development
  vcsChangeTimeToApproval(
      'vcs.change.time_to_approval', SemanticInstrument.gauge, 's'),

  /// The amount of time since its creation it took a change (pull
  /// request/merge request/changelist) to get merged into the target(base)
  /// ref.
  ///
  /// Stability: development
  vcsChangeTimeToMerge(
      'vcs.change.time_to_merge', SemanticInstrument.gauge, 's'),

  /// The number of unique contributors to a repository.
  ///
  /// Stability: release_candidate
  vcsContributorCount(
      'vcs.contributor.count', SemanticInstrument.gauge, '{contributor}'),

  /// The number of refs of type branch or tag in a repository.
  ///
  /// Stability: release_candidate
  vcsRefCount('vcs.ref.count', SemanticInstrument.upDownCounter, '{ref}'),

  /// The number of lines added/removed in a ref (branch) relative to the ref
  /// from the `vcs.ref.base.name` attribute.
  ///
  /// Stability: release_candidate
  vcsRefLinesDelta('vcs.ref.lines_delta', SemanticInstrument.gauge, '{line}'),

  /// The number of revisions (commits) a ref (branch) is ahead/behind the
  /// branch from the `vcs.ref.base.name` attribute.
  ///
  /// Stability: release_candidate
  vcsRefRevisionsDelta(
      'vcs.ref.revisions_delta', SemanticInstrument.gauge, '{revision}'),

  /// Time a ref (branch) created from the default branch (trunk) has
  /// existed. The `ref.type` attribute will always be `branch`.
  ///
  /// Stability: release_candidate
  vcsRefTime('vcs.ref.time', SemanticInstrument.gauge, 's'),

  /// The number of repositories in an organization.
  ///
  /// Stability: release_candidate
  vcsRepositoryCount(
      'vcs.repository.count', SemanticInstrument.upDownCounter, '{repository}');

  @override
  final String name;

  @override
  final SemanticInstrument instrument;

  @override
  final String unit;

  const VcsMetric(this.name, this.instrument, this.unit);

  @override
  String toString() => name;
}
