// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `app`
/// namespace.
library;

import '../../semantics_base.dart';

/// `app` event names from the OpenTelemetry semantic
/// conventions.
enum AppEvent implements OTelEvent {
  /// This event represents a termination of a user-facing application due to
  /// unrecoverable programming errors such as exceptions or signals that
  /// indicate an error has happened at a lower level.
  ///
  /// Stability: development
  appCrash('app.crash'),

  /// This event indicates that the application has detected substandard UI
  /// rendering performance.
  ///
  /// Stability: development
  appJank('app.jank'),

  /// This event represents an instantaneous click on the screen of an
  /// application.
  ///
  /// Stability: development
  appScreenClick('app.screen.click'),

  /// This event indicates that an application widget has been clicked.
  ///
  /// Stability: development
  appWidgetClick('app.widget.click');

  @override
  final String name;

  const AppEvent(this.name);

  @override
  String toString() => name;
}
