// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0
// (registry v1.44.0 @ e10a9308).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `az`
/// namespace.
library;

import '../../semantics_base.dart';

/// `az` event names from the OpenTelemetry semantic
/// conventions.
enum AzEvent implements OTelEvent {
  /// Deprecated. Use `azure.resource.log` instead.
  ///
  /// Stability: development
  @Deprecated('Replaced by `azure.resource.log`.')
  azResourceLog('az.resource.log');

  @override
  final String name;

  const AzEvent(this.name);

  @override
  String toString() => name;
}
