// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0
// (registry v1.44.0 @ e10a9308).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `browser`
/// namespace.
library;

import '../../semantics_base.dart';

/// `browser` event names from the OpenTelemetry semantic
/// conventions.
enum BrowserEvent implements OTelEvent {
  /// This event describes the website performance metrics introduced by
  /// Google, See [web vitals](https://web.dev/vitals).
  ///
  /// Stability: development
  browserWebVital('browser.web_vital');

  @override
  final String name;

  const BrowserEvent(this.name);

  @override
  String toString() => name;
}
