// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `db`
/// namespace.
library;

import '../../semantics_base.dart';

/// `db` event names from the OpenTelemetry semantic
/// conventions.
enum DbEvent implements OTelEvent {
  /// This event represents an exception that occurred during a database
  /// client operation, such as connection failures, query errors, timeouts,
  /// or other errors that prevent the operation from completing
  /// successfully.
  ///
  /// Stability: development
  dbClientOperationException('db.client.operation.exception');

  @override
  final String name;

  const DbEvent(this.name);

  @override
  String toString() => name;
}
