// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0
// (registry v1.44.0 @ e10a9308).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `device`
/// namespace.
library;

import '../../semantics_base.dart';

/// `device` event names from the OpenTelemetry semantic
/// conventions.
enum DeviceEvent implements OTelEvent {
  /// This event represents an occurrence of a lifecycle transition on
  /// Android or iOS platform.
  ///
  /// Stability: development
  deviceAppLifecycle('device.app.lifecycle');

  @override
  final String name;

  const DeviceEvent(this.name);

  @override
  String toString() => name;
}
