// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `feature_flag`
/// namespace.
library;

import '../../semantics_base.dart';

/// `feature_flag` event names from the OpenTelemetry semantic
/// conventions.
enum FeatureFlagEvent implements OTelEvent {
  /// Defines feature flag evaluation as an event.
  ///
  /// Stability: release_candidate
  featureFlagEvaluation('feature_flag.evaluation');

  @override
  final String name;

  const FeatureFlagEvent(this.name);

  @override
  String toString() => name;
}
