// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `gen_ai`
/// namespace.
library;

import '../../semantics_base.dart';

/// `gen_ai` event names from the OpenTelemetry semantic
/// conventions.
enum GenAiEvent implements OTelEvent {
  /// This event describes the assistant message passed to GenAI system.
  ///
  /// Stability: development
  @Deprecated(
      'Chat history is reported on `gen_ai.input.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.')
  genAiAssistantMessage('gen_ai.assistant.message'),

  /// This event describes the Gen AI response message.
  ///
  /// Stability: development
  @Deprecated(
      'Chat history is reported on `gen_ai.output.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.')
  genAiChoice('gen_ai.choice'),

  /// Describes the details of a GenAI completion request including chat
  /// history and parameters.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiClientInferenceOperationDetails(
      'gen_ai.client.inference.operation.details'),

  /// This event represents an exception that occurred during a Generative AI
  /// client operation, such as API errors, rate limiting, model errors,
  /// timeouts, or other errors that prevent the operation from completing
  /// successfully.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiClientOperationException('gen_ai.client.operation.exception'),

  /// This event captures the result of evaluating GenAI output for quality,
  /// accuracy, or other characteristics. This event SHOULD be parented to
  /// GenAI operation span being evaluated when possible or set
  /// `gen_ai.response.id` when span id is not available.
  ///
  /// Stability: development
  @Deprecated(
      'Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).')
  genAiEvaluationResult('gen_ai.evaluation.result'),

  /// This event describes the system instructions passed to the GenAI model.
  ///
  /// Stability: development
  @Deprecated(
      'Chat history is reported on `gen_ai.system_instructions` attribute on spans or `gen_ai.client.inference.operation.details` event.')
  genAiSystemMessage('gen_ai.system.message'),

  /// This event describes the response from a tool or function call passed
  /// to the GenAI model.
  ///
  /// Stability: development
  @Deprecated(
      'Chat history is reported on `gen_ai.input.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.')
  genAiToolMessage('gen_ai.tool.message'),

  /// This event describes the user message passed to the GenAI model.
  ///
  /// Stability: development
  @Deprecated(
      'Chat history is reported on `gen_ai.input.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.')
  genAiUserMessage('gen_ai.user.message');

  @override
  final String name;

  const GenAiEvent(this.name);

  @override
  String toString() => name;
}
