// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `http`
/// namespace.
library;

import '../../semantics_base.dart';

/// `http` event names from the OpenTelemetry semantic
/// conventions.
enum HttpEvent implements OTelEvent {
  /// This event represents an exception that occurred during an HTTP client
  /// request, such as network failures, timeouts, or other errors that
  /// prevent the request from completing successfully.
  ///
  /// Stability: development
  httpClientRequestException('http.client.request.exception'),

  /// This event represents an exception that occurred during HTTP server
  /// request processing, such as application errors, internal failures, or
  /// other exceptions that prevent the server from successfully handling the
  /// request.
  ///
  /// Stability: development
  httpServerRequestException('http.server.request.exception');

  @override
  final String name;

  const HttpEvent(this.name);

  @override
  String toString() => name;
}
