// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `messaging`
/// namespace.
library;

import '../../semantics_base.dart';

/// `messaging` event names from the OpenTelemetry semantic
/// conventions.
enum MessagingEvent implements OTelEvent {
  /// This event represents an exception that occurred during a messaging
  /// create operation.
  ///
  /// Stability: development
  messagingCreateException('messaging.create.exception'),

  /// This event represents an exception that occurred during messaging
  /// process operations.
  ///
  /// Stability: development
  messagingProcessException('messaging.process.exception'),

  /// This event represents an exception that occurred during a messaging
  /// receive operation.
  ///
  /// Stability: development
  messagingReceiveException('messaging.receive.exception'),

  /// This event represents an exception that occurred during a messaging
  /// send operation.
  ///
  /// Stability: development
  messagingSendException('messaging.send.exception'),

  /// This event represents an exception that occurred during a messaging
  /// settle operation.
  ///
  /// Stability: development
  messagingSettleException('messaging.settle.exception');

  @override
  final String name;

  const MessagingEvent(this.name);

  @override
  String toString() => name;
}
