// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// AUTOGENERATED by OTel Weaver from the OpenTelemetry semantic
// conventions, schema version 1.44.0-unreleased
// (registry v1.43.0-21-g436fa257 @ 436fa257).
// DO NOT EDIT. Regenerate with: tool/semconv/generate.sh

/// Semantic-convention event names for the `rpc`
/// namespace.
library;

import '../../semantics_base.dart';

/// `rpc` event names from the OpenTelemetry semantic
/// conventions.
enum RpcEvent implements OTelEvent {
  /// This event represents an exception that occurred during an outgoing RPC
  /// call, such as network failures, timeouts, serialization errors, or
  /// other errors that prevent the call from completing successfully.
  ///
  /// Stability: development
  rpcClientCallException('rpc.client.call.exception'),

  /// Describes a message sent or received within the context of an RPC call.
  ///
  /// Stability: development
  @Deprecated('Deprecated, no replacement at this time.')
  rpcMessage('rpc.message'),

  /// This event represents an exception that occurred during incoming RPC
  /// call processing, such as application errors, internal failures, or
  /// other exceptions that prevent the server from successfully handling the
  /// call.
  ///
  /// Stability: development
  rpcServerCallException('rpc.server.call.exception');

  @override
  final String name;

  const RpcEvent(this.name);

  @override
  String toString() => name;
}
